src/objects/AccountMaster__c.object
<CustomObject>
    <description>Master of account items</description>
    <fields>
        <fullName>ServiceRate__c</fullName>
        <description>サービス料金（％）</description>
        <label>サービス料(%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TankawithoutTaxSys__c</fullName>
        <inlineHelpText>画面、レポートなど使わない、システム内部利用項目</inlineHelpText>
        <label>単価(税抜)（システム用）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>会計商品</label>
    <nameField>
        <label>商品名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Approvaldocuments__c.object
<CustomObject>
    <fields>
        <fullName>AmountExc__c</fullName>
        <label>金額(税抜)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ApprovalProgress__c</fullName>
        <label>承認申請進捗</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>１次承認中</fullName>
                </value>
                <value>
                    <fullName>２次承認中</fullName>
                </value>
                <value>
                    <fullName>３次承認中</fullName>
                </value>
                <value>
                    <fullName>４次承認中</fullName>
                </value>
                <value>
                    <fullName>５次承認中</fullName>
                </value>
                <value>
                    <fullName>最終承認済</fullName>
                </value>
                <value>
                    <fullName>却下</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DraftDepart__c</fullName>
        <formula>DraftUser__r.Department</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>起案部署</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DraftDt__c</fullName>
        <label>起案日</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DraftUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>起案者</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ApprovalRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Kamoku__c</fullName>
        <label>科目</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>材料仕入</fullName>
                </value>
                <value>
                    <fullName>売店仕入</fullName>
                </value>
                <value>
                    <fullName>飲料仕入</fullName>
                </value>
                <value>
                    <fullName>室料経費</fullName>
                </value>
                <value>
                    <fullName>ブライダル仕入</fullName>
                </value>
                <value>
                    <fullName>旅館外注費</fullName>
                </value>
                <value>
                    <fullName>役員報酬</fullName>
                </value>
                <value>
                    <fullName>給与手当</fullName>
                </value>
                <value>
                    <fullName>雑給</fullName>
                </value>
                <value>
                    <fullName>法定福利費</fullName>
                </value>
                <value>
                    <fullName>福利厚生費</fullName>
                </value>
                <value>
                    <fullName>旅費交通費</fullName>
                </value>
                <value>
                    <fullName>通信費</fullName>
                </value>
                <value>
                    <fullName>接待交際費</fullName>
                </value>
                <value>
                    <fullName>減価償却費</fullName>
                </value>
                <value>
                    <fullName>販売手数料</fullName>
                </value>
                <value>
                    <fullName>保険料</fullName>
                </value>
                <value>
                    <fullName>修繕費</fullName>
                </value>
                <value>
                    <fullName>消耗品費</fullName>
                </value>
                <value>
                    <fullName>設備消耗品</fullName>
                </value>
                <value>
                    <fullName>支払手数料</fullName>
                </value>
                <value>
                    <fullName>広告宣伝費</fullName>
                </value>
                <value>
                    <fullName>租税公課</fullName>
                </value>
                <value>
                    <fullName>諸会費</fullName>
                </value>
                <value>
                    <fullName>研究研修費</fullName>
                </value>
                <value>
                    <fullName>地代</fullName>
                </value>
                <value>
                    <fullName>リース料</fullName>
                </value>
                <value>
                    <fullName>電力料</fullName>
                </value>
                <value>
                    <fullName>ガス代</fullName>
                </value>
                <value>
                    <fullName>水道料</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LastProcessDt__c</fullName>
        <label>最終承認日</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <inlineHelpText>１行39文字、13行以内入力ください。</inlineHelpText>
        <label>趣旨</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RowNo__c</fullName>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </fields>
    <label>稟議</label>
    <nameField>
        <label>稟議名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ApprovalItem__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>数量</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GoukeinoneTax__c</fullName>
        <formula>Tankanonetax__c * Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>$合計金額（税抜）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductName__c</fullName>
        <label>商品名称（または券名称）</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RowNo__c</fullName>
        <label>RowNo.</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ServiceRate__c</fullName>
        <label>サービス料(%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SpTotal__c</fullName>
        <label>#合計金額</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tankanonetax__c</fullName>
        <formula>/*if ( OR(ISNULL(TaxRate__c), TaxRate__c == 0), UnitPrice__c , CEILING(UnitPrice__c/(1 + TaxRate__c)) )*/ 
/* 
// 1:税込、サービス料抜き 
// 2:税込、サービス料込 
// 3:税抜、サービス料抜き 
// 4:税抜、サビース料込 
*/ 
/* 2014/08/06 EDIT 
Case ($Setup.CommDefine__c.UnitPriceDefKb__c , 
1, CEILING( UnitPrice__c / ( 1 + NULLVALUE (TaxRate__c, 0) ) ), 
2, CEILING( UnitPrice__c / ( (1 + NULLVALUE (TaxRate__c, 0) ) * ( 1 + NULLVALUE (ServiceRate__c, 0) ) ) ), 
3, UnitPrice__c , 
0) 
*/ 
/* 2015/10/15 EDIT 
Case ( 
VALUE( UnitPriceDefKbCal__c) , 
1, CEILING( UnitPrice__c * ( 1 + NULLVALUE (ServiceRate__c, 0) ) / ( 1 + NULLVALUE (TaxRate__c, 0) ) ), 
2, CEILING( UnitPrice__c / ( 1 + NULLVALUE (TaxRate__c, 0) ) ), 
3, CEILING( UnitPrice__c * ( 1 + NULLVALUE (ServiceRate__c, 0) ) ), 
0) 
*/ 
/* 2016/04/13 EDIT 
Case ( 
VALUE( UnitPriceDefKbCal__c) , 
1, CEILING( UnitPrice__c * ( 1 + NULLVALUE (ServiceRate__c, 0) ) / ( 1 + NULLVALUE (TaxRate__c, 0) ) ), 
2, CEILING( UnitPrice__c / ( 1 + NULLVALUE (TaxRate__c, 0) ) ), 
3, CEILING( UnitPrice__c * ( 1 + NULLVALUE (ServiceRate__c, 0) ) ), 
4, UnitPrice__c, 
0) 
*/ 
IF (NULLVALUE (TankawithoutTaxSys__c, 0) != 0, TankawithoutTaxSys__c, 

IF ( 
$Setup.CommDefine__c.AccountNoTaxCalFlg__c != true || 
$Setup.CommDefine__c.RoundType__c = 2, 
Case ( 
VALUE( UnitPriceDefKbCal__c ) , 
1, CEILING( UnitPrice__c * ( 1 + NULLVALUE (ServiceRate__c, 0) ) / ( 1 + NULLVALUE (TaxRate__c, 0) ) ), 
2, CEILING( UnitPrice__c / ( 1 + NULLVALUE (TaxRate__c, 0) ) ), 
3, CEILING( UnitPrice__c * ( 1 + NULLVALUE (ServiceRate__c, 0) ) ), 
4, CEILING( UnitPrice__c), 
0) 
, 
IF($Setup.CommDefine__c.RoundType__c = 0, 
Case ( 
VALUE( UnitPriceDefKbCal__c ) , 
1, FLOOR( UnitPrice__c * ( 1 + NULLVALUE (ServiceRate__c, 0) ) / ( 1 + NULLVALUE (TaxRate__c, 0) ) ), 
2, FLOOR( UnitPrice__c / ( 1 + NULLVALUE (TaxRate__c, 0) ) ), 
3, FLOOR( UnitPrice__c * ( 1 + NULLVALUE (ServiceRate__c, 0) ) ), 
4, FLOOR( UnitPrice__c ), 
0) 
, 
Case ( 
VALUE( UnitPriceDefKbCal__c ) , 
1, ROUND( UnitPrice__c * ( 1 + NULLVALUE (ServiceRate__c, 0) ) / ( 1 + NULLVALUE (TaxRate__c, 0) ) , 0), 
2, ROUND( UnitPrice__c / ( 1 + NULLVALUE (TaxRate__c, 0) ) , 0), 
3, ROUND( UnitPrice__c * ( 1 + NULLVALUE (ServiceRate__c, 0) ) , 0), 
4, ROUND( UnitPrice__c , 0), 
0) 
) 
) 

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>$単価(税抜)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TankawithoutTaxSys__c</fullName>
        <inlineHelpText>画面、レポートなど使わない、システム内部利用項目</inlineHelpText>
        <label>単価(税抜)（システム用）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TaxRate__c</fullName>
        <label>消費税</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>UnitPriceDefKbCal__c</fullName>
        <formula>UnitPriceDefKb__c</formula>
        <label>$会計商品単価定義区分</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitPriceDefKb__c</fullName>
        <defaultValue>TEXT($Setup.CommDefine__c.UnitPriceDefKb__c)</defaultValue>
        <label>会計商品単価定義区分</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitPriceTax__c</fullName>
        <label>単価(税込)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>単価</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>refAccountMaster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>商品名</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipLabel>稟議明細</relationshipLabel>
        <relationshipName>refAccountMasternsYV</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>refApproval__c</fullName>
        <label>稟議</label>
        <referenceTo>Approvaldocuments__c</referenceTo>
        <relationshipLabel>稟議明細</relationshipLabel>
        <relationshipName>refApprovalQEE7</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>稟議明細</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>稟議明細#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PrintInfo__c.object
<CustomObject>
    <fields>
        <fullName>AccountMasterRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会計商品</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipName>RefAccountMaster</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>印刷情報</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>No#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApprovalPDFCtrl.cls
public with sharing class ApprovalPDFCtrl {
	public id approvalId{get;set;}
	// 2019/07/30 軽減税率機能対応 WGCH BEGIN
	public static boolean isReducedTaxFlg{get{ return CommConst.REDUCED_TAXRATE_FLG;} private set;}
	// 2019/07/30 軽減税率機能対応 WGCH END
    public ApprovalPDFCtrl(ApexPages.StandardController controller){
    	bulkPageList = new list<OneStamp>();
    	allPageLst = new list<PageItem>();
    	// 対象データID
    	approvalId = controller.getId();
    	// 既存データを取得する
    	list<Approvaldocuments__c> ApprovalList = [select Id,Name,CreatedDate,
		        										RowNo__c,Kamoku__c,DraftUser__c,DraftDt__c,DraftDepart__c,
		        										AmountExc__c,LastProcessDt__c,Purpose__c,ApprovalProgress__c,
		        										DraftUser__r.Name
		        										from Approvaldocuments__c where Id =:approvalId];
		if (ApprovalList.isEmpty()) {
			Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'レコードは削除されました。'));
			return;
		}
		// 稟議明細
		getApprovalDetail();
		// 既存データ
		for(Approvaldocuments__c a : ApprovalList){
			for (Integer index =0; index < purLst.size(); index++) {
				Integer breakLine = index - (allPageLst.isEmpty() ? 0 : 1) * 7 - (allPageLst.size() > 1 ? allPageLst.size() -1 : 0 ) * 28;
				if(breakLine == 0){
	                PageItem prodRep = new PageItem(a);
	                prodRep.addItem(purLst[index]);
					allPageLst.add(prodRep);
					prodRep.currPages = allPageLst.size();
				}else{
					PageItem prodRep = allPageLst[allPageLst.size() - 1];
	                prodRep.addItem(purLst[index]);
				}
			}
	        if (allPageLst.isEmpty()) {
	        	PageItem prodRep = new PageItem(a);
	        	allPageLst.add(prodRep);
	        }
	        PageItem lastPage = allPageLst[allPageLst.size()-1];
	        // 明細行数確認する
	        Integer breakNum = (lastPage.currPages == 1 ? 7 :28);
	        if (lastPage.onePageList.size() < breakNum) {
	            Integer dumyLen =breakNum - lastPage.onePageList.size();
	            for (Integer i = 0; i < dumyLen; i++) {
	                purItem dumyItem = new purItem(new ApprovalItem__c(),purLst.size()+i+1, pointlen);
	                lastPage.addItem(dumyItem);
	            }
	        }
		}
		// 申請中と承認済みのデータを取得する
		set<id> processIdSet = new set<id>();
		list<ProcessInstance>  processlist= [select id,CreatedDate,LastModifiedById,ProcessDefinitionId,SubmittedById,SubmittedBy.Name,SubmittedBy.Department,SystemModstamp,Status from ProcessInstance where TargetObjectId =: approvalId order by CreatedDate desc limit 1];
		for(ProcessInstance p : processlist){
			if(p.Status !='Rejected') processIdSet.add(p.Id);
		}
		if (processIdSet.isEmpty()) return;
		// 承認プロセスの内容詳細を取得する
		list<ProcessInstanceStep>  processSteplist= [SELECT Actor.Name,CreatedDate,CreatedBy.Department,SystemModstamp,ProcessInstance.Status FROM ProcessInstanceStep where ProcessInstanceId =:processIdSet AND StepStatus =:'Approved' order by SystemModstamp asc];
		PageItem onePage = allPageLst[0];
		Integer valNum = 1;
		for(ProcessInstanceStep s : processSteplist){
			if(s.ProcessInstance.Status != 'Approved') valNum = 0;
			String timeStr = s.SystemModstamp.format('yyyy.MM.dd HH:mm:ss');
			onePage.addStamp(new StampItem(s.Actor.Name,timeStr,s.CreatedBy.Department,valNum));
			valNum++;
		}  	
		
    }
    // 数据取舍处理
    private Integer pointlen{get; private set;}
    private void getApprovalDetail(){
    	// 根据稟議获取稟議明細
		list<ApprovalItem__c> queryList = [select Id,Name,refApproval__c,TankawithoutTaxSys__c,GoukeinoneTax__c,
												UnitPriceDefKbCal__c,Tankanonetax__c,ProductName__c,
												RowNo__c,ServiceRate__c,UnitPriceDefKb__c,SpTotal__c,UnitPriceTax__c,
												refAccountMaster__c,refAccountMaster__r.Name,TaxRate__c,Amount__c,UnitPrice__c
												from ApprovalItem__c where refApproval__c=:approvalId order By RowNo__c,Name];
    	String currencyInf = UserInfo.getDefaultCurrency();
    	pointlen = CommUtils.getPointLen(currencyInf);
    	purLst = new List<purItem>();
    	amountExc = 0;
    	// 计算消费税使用 taxRate:取得的第一个不为0的税率，amountTax:税率不为0商品的合计值
    	Decimal taxRate = 0;
    	Decimal amountTax = 0;
    	Tax = 0;
    	if (queryList.isEmpty()) return ;
    	// 2019/07/30 軽減税率機能対応 WGCH BEGIN
    	Decimal taxUnitPrice = 0;
    	// 2019/07/30 軽減税率機能対応 WGCH END
    	// 仕入明细处理
    	for(ApprovalItem__c pur : queryList){
    		// 2019/07/30 軽減税率機能対応 WGCH BEGIN
    		if(isReducedTaxFlg){
    			// 数量
	            Decimal qty = CommUtils.nullToZero(pur.Amount__c);
    			CommUtils.ProductInfo priceInfo = new CommUtils.ProductInfo(CommUtils.nullToIntZero(pur.UnitPriceDefKbCal__c));
	            CommLogicProcess.HotelTaxInfo hotelTaxItem = CommLogicProcess.getHotelTaxInfo(null, null, CommUtils.nullToZero(pur.UnitPrice__c), qty, pur.TaxRate__c, pur.ServiceRate__c, priceInfo, null);
	            // 重置最新的PriceInfo
	            priceInfo = hotelTaxItem.priceInfo;
	            // 最终单价重置
	            pur.UnitPriceTax__c = priceInfo.unitPriceTax;
	            // 最终消费税重置
	            taxUnitPrice += priceInfo.priceTax * qty;
	            // BRK行—合计值-赋值
	            pur.SpTotal__c = pur.UnitPriceTax__c * qty;
    		}
    		// 2019/07/30 軽減税率機能対応 WGCH END
    		amountExc += CommUtils.nullToIntZero(pur.SpTotal__c);
    		if(taxRate <= 0) taxRate = CommUtils.nullToIntZero(pur.TaxRate__c);
    		if(CommUtils.nullToIntZero(pur.TaxRate__c) > 0) amountTax += CommUtils.nullToIntZero(pur.SpTotal__c);
    		purLst.add(new purItem(pur,CommUtils.nullToIntZero(pur.RowNo__c)+1,pointlen));
    	}
    	// 计算内消费税
    	Tax = (amountTax > 0 ? CommUtils.RoundProcess(amountTax / (1 + taxRate / 100) * (taxRate / 100), pointLen) : 0);
    	// 2019/07/30 軽減税率機能対応 WGCH BEGIN
    	if(isReducedTaxFlg) Tax = taxUnitPrice;
    	// 2019/07/30 軽減税率機能対応 WGCH END
    }
    // 数值格式化
    public String numberFormat{get{return CommBaseCtrl.getNumberFormat();}}
    // 货币符号
    public String getCurrencySybmol(){ return CommBaseCtrl.getCurrencySybmol();}
    public Decimal amountExc{get;set;}			// 合計金額
    public Decimal Tax{get;set;}				// 内消費税
    public transient List<OneStamp> bulkPageList{get;private set;}
    public class OneStamp {
    	public OneStamp() {
    		allPageList = new list<PageItem>();	
    	}
    	public Boolean isFirstPage{get;set;}
    	public list<PageItem> allPageList{get;private set;}
    }
    // 数据
    public List<PageItem> allPageLst{get;set;}
    public class PageItem{
    	public Approvaldocuments__c sobj{get; private set;}
    	// 承认印章list
    	public list<StampItem> stampLst{get;set;}
    	// 仕入明细商品list
    	public list<purItem> onePageList{get; private set;}
    	public PageItem(Approvaldocuments__c app){
    		onePageList = new List<purItem>();
    		stampLst = new list<StampItem>();
    		sobj = app;
    		currPages = 1;
    	}
    	// 仕入明细数据
		public void addItem(purItem item) {
			onePageList.add(item);
		}
		//印章数据
		public void addStamp(StampItem item) {
			stampLst.add(item);
		}
		// 現在表示してページ数
		public Integer currPages{get;set;}
		public Boolean isFirstPage{get{
		  return currPages == 1;
		}}
    }
    // 承认申请印章显示的数据
    public class StampItem{
    	public String nameStr{get;set;} 	// 承认者
    	public String dateStr{get;set;} 	// 日期时间
    	public String departStr{get;set;} 	// 部门(暂时不使用，不确认是否需要调整)
    	public Integer indexNo{get;set;} 	// 印章序号(确认是否是最终承认)
    	public StampItem(String US,String DT,String UD,Integer indexRow){
    		indexNo = indexRow;
    		nameStr = US;
    		dateStr = DT;
    		departStr = UD;
    	}
    }
    // 仕入明细数据处理
    private List<purItem> purLst;
    public class purItem {
    	public Integer rowNo{get;set;}				// 序号
    	public String AccName{get;set;}				// 品名
    	public Decimal unitPrice{get;set;}			// 单价
    	public Decimal quantity{get;set;}			// 数量
    	public Decimal amout{get;set;}				// 小计
    	public Boolean isAccountMasterFlg{get;set;}	// 商品是否存在(不存在时显示为空，无商品数量)
    	public purItem(ApprovalItem__c pur, Integer index,Integer pPointLen) {
    		isAccountMasterFlg = true;
    		if (pur.id == null) isAccountMasterFlg = false;
    		rowNo = index;
    		AccName = CommRepUtils.getPdfMaxShowStringNew(CommUtils.isBlank(pur.ProductName__c) ? pur.refAccountMaster__r.Name : pur.ProductName__c,1,25);
    		unitPrice = CommUtils.nullToIntZero(pur.UnitPriceTax__c);
    		quantity = CommUtils.nullToIntZero(pur.Amount__c);
    		amout = CommUtils.nullToIntZero(pur.SpTotal__c);
    	}
    }
}