src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BankAccountNo__c</fullName>
        <label>口座番号</label>
        <length>7</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>BankBranchNameKana__c</fullName>
        <inlineHelpText>半角カタカナを入力してください</inlineHelpText>
        <label>支店名(カナ）</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankBranchName__c</fullName>
        <label>支店名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankBranchNumber__c</fullName>
        <label>支店番号</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankNameKana__c</fullName>
        <inlineHelpText>半角カタカナを入力してください</inlineHelpText>
        <label>金融機関名（カナ）</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankName__c</fullName>
        <label>金融機関名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankNumber__c</fullName>
        <label>金融機関番号</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DepositsType__c</fullName>
        <label>預金種目</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>普通</fullName>
                </value>
                <value>
                    <fullName>当座</fullName>
                </value>
                <value>
                    <fullName>貯蓄</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TransferChargeKbn__c</fullName>
        <inlineHelpText>振込には所定の手数料がかかります
ご依頼人さま：振込金額と手数料をご指定の出金口座から引き落とします。
お受取人さま：振込金額から手数料を除いた金額がお受取人さまに入金されます。</inlineHelpText>
        <label>振込手数料負担先</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>先方負担</fullName>
                </value>
                <value>
                    <fullName>自社負担</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ReportLogo__c.object
<CustomObject>
    <description>Logo image file for Statement sheet, Estimate sheet and Invoice sheet</description>
    <fields>
        <fullName>ShopInfoRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>店舗情報</label>
        <referenceTo>ShopInformation__c</referenceTo>
        <relationshipName>ShopInfoRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>レポートロゴ</label>
    <nameField>
        <label>請求書ロゴ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ShopAccountInfo__c.object
<CustomObject>
    <fields>
        <fullName>AccountRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>口座情報</relationshipLabel>
        <relationshipName>AccountRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AccountTypeLst__c</fullName>
        <label>口座種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>買掛支払</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BankAccountNo__c</fullName>
        <label>口座番号</label>
        <length>7</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>BankBranchNameKana__c</fullName>
        <inlineHelpText>半角カタカナを入力してください</inlineHelpText>
        <label>支店名(カナ）</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankBranchName__c</fullName>
        <label>支店名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankBranchNumber__c</fullName>
        <label>支店番号</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankNameKana__c</fullName>
        <inlineHelpText>半角カタカナを入力してください</inlineHelpText>
        <label>金融機関名（カナ）</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankName__c</fullName>
        <label>金融機関名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankNumber__c</fullName>
        <label>金融機関番号</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DepositsType__c</fullName>
        <label>預金種目</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>普通</fullName>
                </value>
                <value>
                    <fullName>当座</fullName>
                </value>
                <value>
                    <fullName>貯蓄</fullName>
                </value>
                <value>
                    <fullName>その他</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RequestUserCode__c</fullName>
        <label>委託者コード</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestUserName__c</fullName>
        <inlineHelpText>半角カタカナを入力してください</inlineHelpText>
        <label>委託者名(名義人)</label>
        <length>40</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ShopInfoRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>店舗情報</label>
        <referenceTo>ShopInformation__c</referenceTo>
        <relationshipLabel>店舗口座情報</relationshipLabel>
        <relationshipName>KozaShopInfoRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StatusLst__c</fullName>
        <label>ステータス</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>有効</fullName>
                    <default>true</default>
                    <label>有効</label>
                </value>
                <value>
                    <fullName>無効</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TransferChargeKbn__c</fullName>
        <label>振込手数料負担先</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>先方負担</fullName>
                </value>
                <value>
                    <fullName>自社負担</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>口座情報</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>番号</label>
        <type>AutoNumber</type>
    </nameField>
    <recordTypes>
        <fullName>CompanyRecordType</fullName>
        <active>true</active>
        <label>自社</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ShopInformation__c.object
<CustomObject>
    <description>Shoppers</description>
    <fields>
        <fullName>ShopCode__c</fullName>
        <externalId>true</externalId>
        <label>店舗コード</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>店舗情報</label>
    <nameField>
        <label>店舗名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InfoOutputProcessCtrl.cls
/*********************************************
* CSV情報を取得機能対応
* 2015/12/04 INIT
**/
public with sharing class InfoOutputProcessCtrl {

	public static final String PrefixKey = 'KOUZA_';
	private final String ProcessJobNo;
	private final String SalesLoginUrl = URL.getSalesforceBaseUrl().toExternalForm() + '/';
	
	private final String KouzaCsvTemplate = '$$_番号_$$,$$_金融機関番号_$$,$$_支店番号_$$,$$_預金種目_$$,$$_口座番号_$$,$$_取引先名_$$,$$_金融機関名_$$,$$_金融機関名カナ_$$,$$_支店名_$$,$$_支店名カナ_$$,$$_名義人_$$,$$_振込手数料負担先_$$,$$_委託者コード_$$,$$_口座種別_$$,$$_ステータス_$$,$$_URL_$$\n';
	private list<id> kouzaIdLst;
	public InfoOutputProcessCtrl() {
		ProcessJobNo = System.now().format('yyyyMMddHHmmss');
	}
	/**
	* 口座情報一覧を取得する
	**/
	public PageReference generalKouzaInfo() {
		// パラメータから引き渡す口座IDの場合、口座情報取得条件に該当限定条件を追加する
		kouzaIdLst = new List<String>();
		String conId = ApexPages.currentPage().getParameters().get('rIds'); 
		if (!Commutils.isBlank(conId)) {
			for(String str : conId.split(',')) {
	    		kouzaIdLst.add(str);
			}
		}
		RecordType rt = [SELECT Id,Name FROM RecordType WHERE DeveloperName='CompanyRecordType' LIMIT 1];
		
		String queryStr = 'Select Id,recordTypeId,name,BankNumber__c,BankBranchNumber__c,BankNameKana__c,BankBranchNameKana__c,AccountTypeLst__c,DepositsType__c,BankAccountNo__c,ShopInfoRef__c,ShopInfoRef__r.Name,AccountRef__c,AccountRef__r.Name,BankName__c,BankBranchName__c,RequestUserName__c,TransferChargeKbn__c,RequestUserCode__c,StatusLst__c from ShopAccountInfo__c';
		if (!kouzaIdLst.isEmpty()) {
			queryStr += ' Where id in :kouzaIdLst ';
		}
		queryStr += ' Order By RecordTypeId, ShopInfoRef__r.Name,AccountRef__r.Name Limit 10000 ';
		String csvBody = Label.MSG_051_0001+'\n';
		for (ShopAccountInfo__c kouza : DataBase.query(queryStr)) {
			String accountName = CommUtils.nullToBlank(kouza.AccountRef__r.Name);
			if (rt.Id == kouza.recordTypeId) {
				accountName = CommUtils.nullToBlank(kouza.ShopInfoRef__r.Name);
			}
			String oneLineCsv = KouzaCsvTemplate
								.Replace('$$_番号_$$'		, CommUtils.nullToBlank(kouza.Name))
								.Replace('$$_金融機関番号_$$'	, CommUtils.nullToBlank(kouza.BankNumber__c))
								.Replace('$$_支店番号_$$'		, CommUtils.nullToBlank(kouza.BankBranchNumber__c))
								.Replace('$$_預金種目_$$'		, CommUtils.nullToBlank(kouza.DepositsType__c))
								.Replace('$$_口座番号_$$'		, CommUtils.nullToBlank(kouza.BankAccountNo__c))
								.Replace('$$_取引先名_$$'		, accountName)
								.Replace('$$_金融機関名_$$'	, CommUtils.nullToBlank(kouza.BankName__c))
								.Replace('$$_金融機関名カナ_$$', CommUtils.nullToBlank(kouza.BankNameKana__c))
								.Replace('$$_支店名_$$'		, CommUtils.nullToBlank(kouza.BankBranchName__c))
								.Replace('$$_支店名カナ_$$'	, CommUtils.nullToBlank(kouza.BankBranchNameKana__c))
								.Replace('$$_名義人_$$'		, CommUtils.nullToBlank(kouza.RequestUserName__c))
								.Replace('$$_振込手数料負担先_$$'	, CommUtils.nullToBlank(kouza.TransferChargeKbn__c))
								.Replace('$$_委託者コード_$$'	, CommUtils.nullToBlank(kouza.RequestUserCode__c))
								.Replace('$$_口座種別_$$'		, CommUtils.nullToBlank(kouza.AccountTypeLst__c))
								.Replace('$$_ステータス_$$'	, CommUtils.nullToBlank(kouza.StatusLst__c))
								.Replace('$$_URL_$$'		, SalesLoginUrl + kouza.id);
			csvBody += oneLineCsv;
		}
		//  ユーザー所属店舗情報を取得する
		String shopCode = UserUtil.CurrentUserInfo.defaultShopCode;
		ShopInformation__c shop = new ShopInformation__c();
		if (!CommUtils.isBlank(shopCode)) {
			shop = ShopInfoUtil.getShop(shopCode);
		}
		Document newDoc = createFileToSyncFloder(csvBody, shop);
		Pagereference page = new Pagereference('/apex/PcaSyncCsvDownload?rid=' + newDoc.id);
		return page;
	}
	/**
	* フォルダに連携結果を保存する
	**/
	private Document createFileToSyncFloder(String csvBody, ShopInformation__c shop) {
		// 2017/02/23 Field Security Check BEGIN by wx
		List<String> insChkFields = new List<String>{'Description','FolderId','Name','ContentType','type','body','DeveloperName'};
		Map<String,Schema.SObjectField> insm = Schema.SObjectType.Document.fields.getMap();
		if (!CommSecurityUtils.isCanCreateable(insChkFields, insm)) {
			return null;
		}
		// 2017/02/23 Field Security Check End by wx
		// 添附ファイル名				
		String fileName = PrefixKey + ProcessJobNo
						+ ( CommUtils.isBlank(shop.ShopCode__c) ? '' : '_' + ( shop.ShopCode__c + '(' +shop.Name  + ')') ) 
						+ '.csv';	
		// ファイル格納のフォルダを取得する
		List<Folder> fs = [select id from Folder where DeveloperName = 'SyncFiles' limit 1];
        // CSVファイルをアップロードする
        Document newDoc = new Document(
        	DeveloperName = PrefixKey+ ProcessJobNo + (CommUtils.isBlank(shop.ShopCode__c) ? '' : '_' + shop.ShopCode__c),
        	//口座情報出力_
        	Description = Label.CONST_040_0103 +PrefixKey +System.now().format('yyyyMMddHHmmss'),
        	FolderId = fs[0].Id,
        	Name = fileName,
        	ContentType = 'text/csv',
        	type = 'csv',
        	body = Blob.valueOf(csvBody)
        );
        insert newDoc;
        return newDoc;
	}
}