src/objects/AccountAcount__c.object
<CustomObject>
    <description>*** Account Header</description>
    <fields>
        <fullName>BatchProcessStatusDiv__c</fullName>
        <label>バッチ処理区分</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SumTax__c</fullName>
        <description>消費税合計値
[合計金額（税込）/1.05]</description>
        <label>消費税</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>frs__c</fullName>
        <label>予約会計</label>
        <referenceTo>RsvAccount__c</referenceTo>
        <relationshipLabel>会計</relationshipLabel>
        <relationshipName>AccountYLM3</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>会計</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>Account#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RsvAccount__c.object
<CustomObject>
    <description>Revenue day by day</description>
    <label>売上</label>
    <nameField>
        <label>予約会計名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DataFixBatchForAccountTaxRate.cls
global with sharing class DataFixBatchForAccountTaxRate implements Database.Batchable<sObject>, Database.Stateful, Schedulable{
	private static final String CONST_BATCH_STATUS = '1';
	public String querySQL = ' Select Id, BatchProcessStatusDiv__c From AccountAcount__c ';
	public String whereSQL = ' Where (SumTax__c = null or SumTax__c = 0) ';
	public String orderBySQL = ' Order by LeadIndexRef__c, LeadIndexSubId__c, RoomGroupNo__c ';
	public String salesDtStr = CommUtils.dateToYYYYMMDD(Date.newInstance(2019,10,1));
	// スケジュールインスタンス関数
	global DataFixBatchForAccountTaxRate () {}
	global DataFixBatchForAccountTaxRate (Date pSalesdate) {
		if(pSalesdate != null) salesDtStr = CommUtils.dateToYYYYMMDD(pSalesdate);
	}
	
	// ***********************************
	// スケジュール処理開始
	// ***********************************
	public void execute(SchedulableContext SC) {
		DataFixBatchForAccountTaxRate batch = new DataFixBatchForAccountTaxRate();
		DataBase.executeBatch(batch, 1);
	}
	// ***********************************
	// バッチ処理開始
	// ***********************************
	public Database.QueryLocator start(Database.BatchableContext BC){
		String Query = querySQL + whereSQL + ' frs__r.Name >=: salesDtStr ' + orderBySQL;
		return Database.getQueryLocator(querySQL);
	}
	// ***********************************
	// バッチロジック処理開始
	// ***********************************
	public void execute(Database.BatchableContext BC, List<AccountAcount__c> accLst){
		if(accLst.isEmpty()) return;
		List<AccountAcount__c> upAccLst = new List<AccountAcount__c>();
		for(AccountAcount__c acc : accLst){
			ApexPages.StandardController contrl = new ApexPages.StandardController(acc);
			// 画面起動
			BillSimpleInputCtrl ctrl = new BillSimpleInputCtrl(contrl);
			ctrl.batchExcuteFlag = true;
			ctrl.initAction();
			// 更新数据
			if(ctrl.oPage.isIns) ctrl.insertData();
			else if(ctrl.oPage.isUpd) ctrl.upsertData();
			acc.BatchProcessStatusDiv__c = CONST_BATCH_STATUS;
			upAccLst.add(acc);
		}
		if(!upAccLst.isEmpty()) update upAccLst;
	}
	// ***********************************
	// バッチ終了処理開始
	// ***********************************
	public void finish(Database.BatchableContext BC){}
}