src/objects/AccountMaster__c.object
<CustomObject>
    <description>Master of account items</description>
    <fields>
        <fullName>ActionType__c</fullName>
        <description>普通の商品は　デフォルト値：通常で設定する、特別商品に対して、別々、商品種別に設定する
前受付金の場合、会計商品マスたに、価格はNull設定して、入力画面に自由入力する</description>
        <label>商品処理種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>通常</fullName>
                    <default>true</default>
                    <label>通常</label>
                </value>
                <value>
                    <fullName>前受付金</fullName>
                </value>
                <value>
                    <fullName>プラン</fullName>
                </value>
                <value>
                    <fullName>室料</fullName>
                </value>
                <value>
                    <fullName>朝食</fullName>
                </value>
                <value>
                    <fullName>夕食</fullName>
                </value>
                <value>
                    <fullName>非表示</fullName>
                </value>
                <value>
                    <fullName>支払</fullName>
                </value>
                <value>
                    <fullName>サービス料</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field3__c</fullName>
        <externalId>true</externalId>
        <label>商品コード</label>
        <length>13</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PaymentType__c</fullName>
        <label>支払種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>現金</fullName>
                </value>
                <value>
                    <fullName>カード</fullName>
                </value>
                <value>
                    <fullName>売掛金</fullName>
                </value>
                <value>
                    <fullName>クーポン</fullName>
                </value>
                <value>
                    <fullName>割引</fullName>
                </value>
                <value>
                    <fullName>値引</fullName>
                </value>
                <value>
                    <fullName>予約金</fullName>
                </value>
                <value>
                    <fullName>現金返金</fullName>
                </value>
                <value>
                    <fullName>カード返金</fullName>
                </value>
                <value>
                    <fullName>割増</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>会計商品</label>
    <nameField>
        <label>商品名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ReportLogo__c.object
<CustomObject>
    <description>Logo image file for Statement sheet, Estimate sheet and Invoice sheet</description>
    <fields>
        <fullName>ReportLogo__c</fullName>
        <label>レポートロゴ</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>レポートロゴ</label>
    <nameField>
        <label>請求書ロゴ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/JinyaInstallClassTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class JinyaInstallClassTest {

    @isTest(seeAllData=true)
	static void testInstallScript() {
		//delete [select id from pushTopic];
		String[] codes = new List<String>{'M99000','M99001','M99002','M99003','M99004','M99005'};
		//delete [select id from AccountMaster__c where Field3__c in :codes and ActionType__c = :CommConst.PROD_ACTION_TYPE_PY and PaymentType__c != null];
  		JinyaInstallClass postinstall = new JinyaInstallClass();
    	Test.testInstall(postinstall, null);
    	Test.testInstall(postinstall, new Version(1,5), true);
    	Version v = System.requestVersion();
  		System.debug(logginglevel.info,'v:::' + v);
    	//UserInfo.isCurrentUserLicensed('your_namespace');
    	System.debug(logginglevel.info,'System.requestVersion()' + System.requestVersion());
    	//System.debug(logginglevel.info,'Account Master' + [select id,Field3__c,Name,ActionType__c,PaymentType__c from AccountMaster__c where Field3__c in :codes ]);
		//System.debug(logginglevel.info,'System.requestVersion().major()' + System.requestVersion().major());
   		List<ReportLogo__c> a = [Select id from ReportLogo__c where name =: CommRepUtils.REP_TYPE.LOGO_00_SYSDEF.name()];
    	System.assertEquals(a.size(), 1, 'ReportLogo not found');
    	System.assertEquals([select id from pushTopic].size(),6);
    	System.assertEquals([select id from AccountMaster__c where Field3__c in :codes and ActionType__c = :CommConst.PROD_ACTION_TYPE_PY and PaymentType__c != null].size(),codes.size());
		Test.startTest();
			JinyaInstallClassHelpBatch batch = new JinyaInstallClassHelpBatch();
            DataBase.executeBatch(batch, 1);
		Test.stopTest();
	}
}