src/objects/AccountMaster__c.object
<CustomObject>
    <description>Master of account items</description>
    <fields>
        <fullName>ActionType__c</fullName>
        <description>普通の商品は　デフォルト値：通常で設定する、特別商品に対して、別々、商品種別に設定する
前受付金の場合、会計商品マスたに、価格はNull設定して、入力画面に自由入力する</description>
        <label>商品処理種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>通常</fullName>
                    <default>true</default>
                    <label>通常</label>
                </value>
                <value>
                    <fullName>前受付金</fullName>
                </value>
                <value>
                    <fullName>プラン</fullName>
                </value>
                <value>
                    <fullName>室料</fullName>
                </value>
                <value>
                    <fullName>朝食</fullName>
                </value>
                <value>
                    <fullName>夕食</fullName>
                </value>
                <value>
                    <fullName>非表示</fullName>
                </value>
                <value>
                    <fullName>支払</fullName>
                </value>
                <value>
                    <fullName>サービス料</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field3__c</fullName>
        <externalId>true</externalId>
        <label>商品コード</label>
        <length>13</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PaymentType__c</fullName>
        <label>支払種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>現金</fullName>
                </value>
                <value>
                    <fullName>カード</fullName>
                </value>
                <value>
                    <fullName>売掛金</fullName>
                </value>
                <value>
                    <fullName>クーポン</fullName>
                </value>
                <value>
                    <fullName>割引</fullName>
                </value>
                <value>
                    <fullName>値引</fullName>
                </value>
                <value>
                    <fullName>予約金</fullName>
                </value>
                <value>
                    <fullName>現金返金</fullName>
                </value>
                <value>
                    <fullName>カード返金</fullName>
                </value>
                <value>
                    <fullName>割増</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ServiceRate__c</fullName>
        <description>サービス料金（％）</description>
        <label>サービス料(%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ShopInfoRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>店舗情報</label>
        <referenceTo>ShopInformation__c</referenceTo>
        <relationshipLabel>会計商品</relationshipLabel>
        <relationshipName>AccountShopInfoRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会計商品</label>
    <nameField>
        <label>商品名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BookingEstimateItem__c.object
<CustomObject>
    <description>Details Estimate for Booking</description>
    <fields>
        <fullName>ActionType__c</fullName>
        <description>普通の商品は　デフォルト値：通常で設定する、特別商品に対して、別々、商品種別に設定する
前受付金の場合、会計商品マスたに、価格はNull設定して、入力画面に自由入力する</description>
        <label>商品処理種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>通常</fullName>
                    <default>true</default>
                    <label>通常</label>
                </value>
                <value>
                    <fullName>前受付金</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>商品の数量を入力してください</inlineHelpText>
        <label>数量</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Field3__c</fullName>
        <label>商品コード</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PaymentType__c</fullName>
        <label>支払種別</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceRate__c</fullName>
        <description>サービス料金（％）</description>
        <label>サービス料(%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <inlineHelpText>空欄のまま保存すると、会計商品で定義した単価が設定されます</inlineHelpText>
        <label>単価</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UseDate__c</fullName>
        <label>利用日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>refAccountMaster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>商品を選択して下さい</inlineHelpText>
        <label>商品名</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipLabel>予約見積明細</relationshipLabel>
        <relationshipName>BookingEstimateItemhSGP</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>予約見積明細</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>予約見積明細#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CommDefine__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>AccountServiceChargeIsShow__c</fullName>
        <inlineHelpText>会計書(施設コード33/34) 、請求書、見積書にサービス料合計金額は利用明細に表示する・しない制御 
0/空欄：サービス料合計金額は明細行に追加表示しない（デフォルト値） 
1：サービス料合計金額は明細行に追加表示
2：サービス料合計金額は内税消費税行の下に表示</inlineHelpText>
        <label>サービス料別表示制御</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PDFPlanBrkIsShowFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>該当パラメータON設定不可!!!
軽減税率機能有効前提
見積書、会計書、請求書の明細を表示する場合、プラン明細も出力する・しない切替フラグ
TRUE：プラン明細出力表示する
FALSE：プラン明細出力表示しない（デフォルト値）</inlineHelpText>
        <label>RFU</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReducedTaxRateFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>該当機能有効により、多税率混在定義可能になる
TRUE：軽減税率機能有効
FALSE：軽減税率機能無効（デフォルト値）</inlineHelpText>
        <label>軽減税率機能有効フラグ</label>
        <type>Checkbox</type>
    </fields>
    <label>共通定義</label>
</CustomObject>

src/objects/Lead__c.object
<CustomObject>
    <description>Booking sheet with record type</description>
    <fields>
        <fullName>ContractDate__c</fullName>
        <label>契約日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Field3__c</fullName>
        <inlineHelpText>出発の時間を選択してください。</inlineHelpText>
        <label>出発時刻</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>11:00</fullName>
                </value>
                <value>
                    <fullName>11:10</fullName>
                </value>
                <value>
                    <fullName>11:20</fullName>
                </value>
                <value>
                    <fullName>11:30</fullName>
                </value>
                <value>
                    <fullName>11:40</fullName>
                </value>
                <value>
                    <fullName>11:50</fullName>
                </value>
                <value>
                    <fullName>12:00</fullName>
                </value>
                <value>
                    <fullName>12:10</fullName>
                </value>
                <value>
                    <fullName>12:20</fullName>
                </value>
                <value>
                    <fullName>12:30</fullName>
                </value>
                <value>
                    <fullName>12:40</fullName>
                </value>
                <value>
                    <fullName>12:50</fullName>
                </value>
                <value>
                    <fullName>13:00</fullName>
                </value>
                <value>
                    <fullName>13:10</fullName>
                </value>
                <value>
                    <fullName>13:20</fullName>
                </value>
                <value>
                    <fullName>13:30</fullName>
                </value>
                <value>
                    <fullName>13:40</fullName>
                </value>
                <value>
                    <fullName>13:50</fullName>
                </value>
                <value>
                    <fullName>14:00</fullName>
                </value>
                <value>
                    <fullName>14:10</fullName>
                </value>
                <value>
                    <fullName>14:20</fullName>
                </value>
                <value>
                    <fullName>14:30</fullName>
                </value>
                <value>
                    <fullName>14:40</fullName>
                </value>
                <value>
                    <fullName>14:50</fullName>
                </value>
                <value>
                    <fullName>15:00</fullName>
                </value>
                <value>
                    <fullName>15:10</fullName>
                </value>
                <value>
                    <fullName>15:20</fullName>
                </value>
                <value>
                    <fullName>15:30</fullName>
                </value>
                <value>
                    <fullName>15:40</fullName>
                </value>
                <value>
                    <fullName>15:50</fullName>
                </value>
                <value>
                    <fullName>10:00</fullName>
                    <default>true</default>
                    <label>10:00</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LeadPdfShopCode__c</fullName>
        <label>見積書指定店舗</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PayDuration__c</fullName>
        <label>支払期限・方法</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PeriodInfo__c</fullName>
        <label>納期</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuotationComment__c</fullName>
        <label>見積書コメント</label>
        <type>TextArea</type>
    </fields>
    <label>ご予約</label>
    <nameField>
        <label>予約名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ReportLogo__c.object
<CustomObject>
    <description>Logo image file for Statement sheet, Estimate sheet and Invoice sheet</description>
    <fields>
        <fullName>ReportLogo__c</fullName>
        <label>レポートロゴ</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ShopInfoRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>店舗情報</label>
        <referenceTo>ShopInformation__c</referenceTo>
        <relationshipName>ShopInfoRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>レポートロゴ</label>
    <nameField>
        <label>請求書ロゴ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ShopInformation__c.object
<CustomObject>
    <description>Shoppers</description>
    <fields>
        <fullName>Payee1__c</fullName>
        <label>振込先１</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payee2__c</fullName>
        <label>振込先２</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payee3__c</fullName>
        <label>振込先３</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PayeeAcount__c</fullName>
        <label>振込先口座</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShopCode__c</fullName>
        <externalId>true</externalId>
        <label>店舗コード</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>店舗情報</label>
    <nameField>
        <label>店舗名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ShopCode__c</fullName>
        <description>従業員所属店舗の店舗コードを指定可能、複数店舗を兼務の場合、カンマで複数店舗コードを一括設定可能
例：複数店舗兼務：01,02,03　→店舗01,02,03兼務になる、デフォルト所属店舗：01
デフォルト所属店舗を指定したい場合、店舗コードの後ろに、「:1」を指定すると、デフォルト店舗を指定可能
例：複数店舗兼務、店舗02はデフォルト所属店舗の場合、下記様に定義可能
-&gt;01,02:1,03</description>
        <inlineHelpText>従業員所属店舗の店舗コードを指定可能、複数店舗を兼務の場合、カンマで複数店舗コードを一括設定可能
例：複数店舗兼務：01,02,03　→店舗01,02,03兼務になる、デフォルト所属店舗：01
デフォルト所属店舗を指定したい場合、店舗コードの後ろに、「:1」を指定すると、デフォルト店舗を指定可能
例：複数店舗兼務、店舗02はデフォルト所属店舗の場合、下記様に定義可能
-&gt;01,02:1,03</inlineHelpText>
        <label>店舗コード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BookingEstimateItemSetupTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class BookingEstimateItemSetupTest {

	// Leadと既存見積
	testMethod static void testCase1() {
        Test.startTest();
        // 2019/07/30 軽減税率機能対応 WGCH BEGIN
        CommDefine__c comDef = TestCommon.createCommDefine();
        comdef.ReducedTaxRateFlg__c = true;
        comdef.PDFPlanBrkIsShowFlg__c = true;
        update comdef;
        // 2019/07/30 軽減税率機能対応 WGCH END
        // 2018/10/24 見積明細自動計算機能対応 WGCH BEGIN
        Document doc = TestCommon.createBillSimpleHelpConfigDoc();
        commNoticeConfig();
        // 2018/10/24 見積明細自動計算機能対応 WGCH END
        // 予約情報を作成する
        Lead__c leadInfo = TestCommon.createLead();
        // 商品情報を作成する[5件商品を作成する]
        List<AccountMaster__c> productLst = TestCommon.createProductMst(5);
        // 見積明細を作成する[1件作成]
        //TestCommon.createBookEstItem(leadInfo, productLst[0]);
        Test.stopTest();
        // Lead設定する
        ApexPages.StandardController contrl = new ApexPages.StandardController(leadInfo);
        BookingEstimateItemSetup ctrl = new BookingEstimateItemSetup(contrl);
        List<BookingEstimateItemSetup.BookEstItem> queryLst = ctrl.oBookEstLst;
        Integer isValidataRecs = 0;
        for (BookingEstimateItemSetup.BookEstItem item : queryLst) {
        	if (item.isValidata) isValidataRecs++;
        }
        System.assertEquals(isValidataRecs, 1);

        BookingEstimateItemSetup.BookEstItem item2 = queryLst[1];
        item2.sobj.refAccountMaster__c = productLst[1].Id;
        item2.productNm = productLst[1].Name;
        item2.prodNums = '4';
        item2.sobj.UnitPrice__c = 5000;
        item2.sobj.UseDate__c = system.today();
        //item2.sobj.ActionType__c = '通常'
        ctrl.upsertData();
        queryLst = ctrl.oBookEstLst;
        isValidataRecs = 0;
        for (BookingEstimateItemSetup.BookEstItem item : queryLst) {
            if (item.isValidata) isValidataRecs++;
        }
        System.assertEquals(isValidataRecs, 2);
        
        // 商品自動取得機能
        ProductItemUtils.ProductItem item = BookingEstimateItemSetup.getProductItemInfo(productLst[0].Field3__c);
        System.assertEquals(item.prodcutName, productLst[0].Name);
        List<ProductItemUtils.ProductItem> items = BookingEstimateItemSetup.getArrayProductItemInfo(productLst[0].Field3__c);
		System.assert(items.size() > 0, items);
		
	}
	
	testMethod static void testCase2() {
        Test.startTest();
        // 2019/07/30 軽減税率機能対応 WGCH BEGIN
        CommDefine__c comDef = TestCommon.createCommDefine();
        comdef.ReducedTaxRateFlg__c = true;
        comdef.PDFPlanBrkIsShowFlg__c = true;
        update comdef;
        // 2019/07/30 軽減税率機能対応 WGCH END
        // 2018/10/24 見積明細自動計算機能対応 WGCH BEGIN
        Document doc = TestCommon.createBillSimpleHelpConfigDoc();
        commNoticeConfig();
        // 2018/10/24 見積明細自動計算機能対応 WGCH END
        Date startDt = Date.newInstance(2013,11,1);
        // 予約情報を作成する
        List<Lead__c> leadInfos = TestCommon.createLead(startDt, 1, 1);
        Lead__c leadInfo = leadInfos[0];
        // プラン情報を作成する
        AccountMaster__c planProd0 = TestCommon.createPlanProd();
        // 商品情報を作成する[5件商品を作成する]
        List<AccountMaster__c> productLst = TestCommon.createProductMst(5);
        // 見積明細を作成する[1件作成]
        //TestCommon.createBookEstItem(leadInfo, productLst[0]);
        Test.stopTest();
        // Lead設定する
        ApexPages.StandardController contrl = new ApexPages.StandardController(leadInfo);
        BookingEstimateItemSetup ctrl = new BookingEstimateItemSetup(contrl);
        List<BookingEstimateItemSetup.BookEstItem> queryLst = ctrl.oBookEstLst;
        Integer isValidataRecs = 0;
        for (BookingEstimateItemSetup.BookEstItem item : queryLst) {
        	if (item.isValidata) isValidataRecs++;
        }
        System.assertEquals(isValidataRecs, 1);
        // 明細情報を取得する
        BookingEstimateItemSetup.BookEstItem existItem = queryLst[0];
       	// 新規プラン商品を取得する
        List<BookingEstimateItemSetup.PlanDetail> planDetail1 = BookingEstimateItemSetup.getAccountMstLstByPlan('', '', planProd0.Id);
 		List<BookingEstimateItemSetup.PlanDetail> planDetail2 = BookingEstimateItemSetup.getAccountMstLstByPlan(existItem.itemId, existItem.leadId, '');
 		delete [select id from BookingEstimateItem__c where id = :existItem.itemId];
 		List<BookingEstimateItemSetup.PlanDetail> planDetail3 = BookingEstimateItemSetup.getAccountMstLstByPlan(existItem.itemId, existItem.leadId, planProd0.Id);
	   ctrl.getQuotationNameLst();
    }
	// 2017/07/14 発注書/注文請書 zyz BEGIN
	static testMethod void LeadToCase7_14_0() {
        Test.startTest();
        // 店舗情報を初期化する
        CommDefine__c comDef = TestCommon.createCommDefine();
        comDef.AccountServiceChargeIsShow__c = '1';
        // 2019/07/30 軽減税率機能対応 WGCH BEGIN
        comdef.ReducedTaxRateFlg__c = true;
        comdef.PDFPlanBrkIsShowFlg__c = true;
        // 2019/07/30 軽減税率機能対応 WGCH END
        update comDef;
        ShopInformation__c shopInfo = TestCommon.createShopInfo();
        shopInfo.payee1__c = '23';
        shopInfo.payee2__c = '23';
        shopInfo.payee3__c = '23';
        shopInfo.payeeAcount__c = '23';
        shopInfo.ShopCode__c = '02';
        update shopInfo;
        ReportLogo__c tempShopLogo = TestCommon.createRepLogo();
        tempShopLogo.ShopInfoRef__c = shopInfo.Id;
        update tempShopLogo;
        User currUser = [select id, ShopCode__c from user where id = :UserInfo.getUserId()];
        currUser.ShopCode__c = shopInfo.ShopCode__c;
        update currUser;
        // 予約情報を作成する
        Lead__c leadInfo = TestCommon.createLead();
        leadInfo.LeadPdfShopCode__c = '01';
        leadInfo.Payduration__c = 'zhifuqixian';
        leadInfo.QuotationComment__c = '発注';
        leadInfo.ContractDate__c = Date.today();
        leadInfo.PeriodInfo__c = '2017/07/01';
        // 商品情報を作成する
        List<AccountMaster__c> productLst = TestCommon.createProductMst(4);
        AccountMaster__c accMst = productLst[1];
        accMst.ActionType__c = '前受付金';
        accMst.PaymentType__c = 'カード';
        update accMst;
        // 見積明細を作成する
        BookingEstimateItem__c bookingItemA = TestCommon.createBookEstItem(leadInfo, productLst[0]);
        bookingItemA.UnitPrice__c = 30000;
        update bookingItemA;
        BookingEstimateItem__c bookingItem = TestCommon.createBookEstItem(leadInfo, productLst[0]);
        // 予約情報のステータス：チェックインに変更する
        bookingItem.UnitPrice__c = 20000;
        bookingItem.ActionType__c = '通常';
        bookingItem.PaymentType__c = null;
        bookingItem.refAccountMaster__c = accMst.Id;
        bookingItem.Amount__c = 4;
        bookingItem.ServiceRate__c = 10;
        bookingItem.ParentBookingItemRef__c = bookingItemA.id;
        update bookingItem;

        Test.stopTest();
        // Report Logo作成
        TestCommon.createRepLogo();

        // 発注書 /注文請書 
        getCsvSetupConfig();
        ApexPages.StandardController contr3 = new ApexPages.StandardController(leadInfo);
        Apexpages.currentPage().getParameters().put('Id',leadInfo.Id);
        Apexpages.currentPage().getParameters().put('ptype','1');
        Apexpages.currentPage().getParameters().put('Contract','2017/07/01');
        Apexpages.currentPage().getParameters().put('PayDuration','zhifuqixian');
        Apexpages.currentPage().getParameters().put('Charge','null');
        Apexpages.currentPage().getParameters().put('Comment','QuotationComment');
        RepGeneralExtendCtrl lPdf = new RepGeneralExtendCtrl(contr3);
        lPdf.initPdf();
        lPdf.initRepWindow();
        lPdf.getLead();
        lPdf.getServiceAmount();
        lPdf.getLeadNames();
        
        RepGeneralExtendCtrl.TotalInfo pdfSumInfo = lPdf.sumInfo;
        pdfSumInfo.payedDiscount = 500;
        System.assert(pdfSumInfo.amoutQuotePriceIncTax != null);
        System.assert(pdfSumInfo.amoutTax != null);
        System.assert(pdfSumInfo.amoutUsedPriceIncTax != null);
	}
	static testMethod void LeadToCase7_14_1() {
        Test.startTest();
        // 予約情報を作成する
        CommDefine__c comDef = TestCommon.createCommDefine();
        comDef.AccountServiceChargeIsShow__c = '1';
        // 2019/07/30 軽減税率機能対応 WGCH BEGIN
        comdef.ReducedTaxRateFlg__c = true;
        comdef.PDFPlanBrkIsShowFlg__c = true;
        // 2019/07/30 軽減税率機能対応 WGCH END
        update comDef;
        ReportLogo__c item1 = new ReportLogo__c();
        item1.Name = CommRepUtils.REP_TYPE.LOGO_00_SYSDEF.name();
        item1.ReportLogo__c = 'TEST CONTEXT BODY';
        insert item1;
        User currUser = [select id, ShopCode__c from user where id = :UserInfo.getUserId()];
        currUser.ShopCode__c = '';
        update currUser;
        list<Lead__c> leadInfolst = TestCommon.createLead(Date.today(),1,1);
        Lead__c leadInfo = leadInfolst[0];
        leadInfo.name = '予約単体テスト_UNIT_TEST_LEAD' + System.now(); // 予約名
        leadInfo.ReservedStatus__c = '確認中'; 
        leadInfo.ReservedDate__c = System.now(); 
        leadInfo.ReservedContact__c = 'Ono'; 
        leadInfo.EntryTime__c = Date.today(); 
        leadInfo.Field4__c = '15:30'; 
        leadInfo.Departure__c = Date.today() +1; 
        leadInfo.Field3__c = '10:00'; 
        leadInfo.StayPersons__c = 1; 
        leadInfo.Field2__c = 'FAX'; 
        leadInfo.Payduration__c = 'zhifuqixian'; 
        leadInfo.QuotationComment__c = '発注'; 
        leadInfo.ContractDate__c = Date.today();
        leadInfo.PeriodInfo__c = '2017/07/01';
        update leadInfo;
        // 商品情報を作成する
        List<AccountMaster__c> productLst = TestCommon.createProductMst(4);
        AccountMaster__c accMst = productLst[1];
        accMst.ActionType__c = '前受付金';
        accMst.PaymentType__c = 'カード';
        update accMst;
        // 見積明細を作成する
        BookingEstimateItem__c bookingItemA = TestCommon.createBookEstItem(leadInfo, productLst[0]);
        bookingItemA.UnitPrice__c = 30000;
        update bookingItemA;
        BookingEstimateItem__c bookingItem = TestCommon.createBookEstItem(leadInfo, productLst[0]);
        // 予約情報のステータス：チェックインに変更する
        bookingItem.UnitPrice__c = 20000;
        bookingItem.ActionType__c = '通常';
        bookingItem.PaymentType__c = null;
        bookingItem.refAccountMaster__c = accMst.Id;
        bookingItem.Amount__c = 4;
        bookingItem.ServiceRate__c = 10;
        bookingItem.ParentBookingItemRef__c = bookingItemA.id;
        update bookingItem;

        Test.stopTest();
        // 発注書 /注文請書 
        getCsvSetupConfig();
        ApexPages.StandardController contr3 = new ApexPages.StandardController(leadInfo);
        Apexpages.currentPage().getParameters().put('Id',leadInfo.Id);
        Apexpages.currentPage().getParameters().put('ptype','1');
        Apexpages.currentPage().getParameters().put('spcd','');
        Apexpages.currentPage().getParameters().put('Contract','2017/07/01');
        Apexpages.currentPage().getParameters().put('PayDuration','zhifuqixian');
        Apexpages.currentPage().getParameters().put('Charge','null');
        Apexpages.currentPage().getParameters().put('Comment','QuotationComment');
        RepGeneralExtendCtrl lPdf = new RepGeneralExtendCtrl(contr3);
        lPdf.initPdf();
        lPdf.initRepWindow();
        lPdf.getLead();
        lPdf.getServiceAmount();
        lPdf.getLeadNames();

        RepGeneralExtendCtrl.TotalInfo pdfSumInfo = lPdf.sumInfo;
        pdfSumInfo.payedDiscount = 500;
        System.assert(pdfSumInfo.amoutQuotePriceIncTax != null);
        System.assert(pdfSumInfo.amoutTax != null);
        System.assert(pdfSumInfo.amoutUsedPriceIncTax != null);
	}
    static testMethod void LeadToCase7_14_2() {
        commNoticeConfig();
        TestCommon.createGroups(1);
        CommDefine__c comm = TestCommon.createCommDefine();
        comm.AutoAlarmFlg__c = true;
        // 2019/07/30 軽減税率機能対応 WGCH BEGIN
        comm.ReducedTaxRateFlg__c = true;
        comm.PDFPlanBrkIsShowFlg__c = true;
        update comm;
        Test.startTest();
        // 2019/07/30 軽減税率機能対応 WGCH END
        List<CollaborationGroup> groupList = [select name from CollaborationGroup];
        comm.ChatterGroupName__c = '11:' + groupList[0].name;
        update comm;
        // 予約情報を作成する
        Lead__c leadInfo = TestCommon.createLead(system.today());
        List<BookingEstimateItem__c> books = [select id,Amount__c from BookingEstimateItem__c];
        books[0].Amount__c = 9;
        update books[0];
        Test.stopTest();
    }

	static testMethod void Commnotice_1_1(){
        commNoticeConfig();
        TestCommon.createGroups(1);
        List<CollaborationGroup> groupList = [select name from CollaborationGroup];
        CommDefine__c comm = TestCommon.createCommDefine();
        comm.AutoAlarmFlg__c = true;
        comm.ChatterGroupName__c = '11:' + groupList[0].name;
        update comm;
        // 予約情報を作成する
        Lead__c leadInfo = TestCommon.createLead(system.today());
        List<BookingEstimateItem__c> books = [select id,Amount__c from BookingEstimateItem__c];
        books[0].Amount__c = 9;
        update books[0];
        // CommonNotifacationCtrl.NoticeDatas datas = new CommonNotifacationCtrl.NoticeDatas(new List<Sobject>(),new List<Sobject>(),'lead__c',CommConst.TriggerMethod.IsUpdate,'11');
    }
	private static void getCsvSetupConfig() {
        String csv = '<?xml version="1.0" encoding="UTF-8"?><root><SHOP><SHOPCODE></SHOPCODE><PAYMENT><CONVERT><PAYTYPE>現金</PAYTYPE><MEIDALAB>預り／現計</MEIDALAB></CONVERT><CONVERT><PAYTYPE>カード</PAYTYPE><MEIDALAB>ｸﾚ計・掛計等</MEIDALAB></CONVERT><CONVERT><PAYTYPE>売掛金</PAYTYPE><MEIDALAB>掛計</MEIDALAB></CONVERT><CONVERT><PAYTYPE>クーポン</PAYTYPE><MEIDALAB>クーポン</MEIDALAB></CONVERT><CONVERT><PAYTYPE>値引</PAYTYPE><MEIDALAB>値引・割引券</MEIDALAB></CONVERT><CONVERT><PAYTYPE>予約金</PAYTYPE><MEIDALAB>予約金</MEIDALAB></CONVERT></PAYMENT><PAYMEIDA><CONVERT><MEIDALAB>預り／現計</MEIDALAB><PRODCODE>87001</PRODCODE></CONVERT><CONVERT><MEIDALAB>ｸﾚ計・掛計等</MEIDALAB><PRODCODE>85201</PRODCODE></CONVERT><CONVERT><MEIDALAB>掛計</MEIDALAB><PRODCODE>85101</PRODCODE></CONVERT><CONVERT><MEIDALAB>クーポン</MEIDALAB><PRODCODE>85610</PRODCODE></CONVERT><CONVERT><MEIDALAB>値引・割引券</MEIDALAB><PRODCODE>87005</PRODCODE></CONVERT><CONVERT><MEIDALAB>予約金</MEIDALAB><PRODCODE>87001</PRODCODE></CONVERT></PAYMEIDA></SHOP></root>';
        Document doc = new Document();
        doc.Name = 'BillSimpleHelpConfig';
        doc.DeveloperName = doc.Name;
        doc.FolderId = UserInfo.getUserId();
        doc.Body = Blob.valueOf(csv);
        insert doc;
	}
	// 2017/07/14 発注書/注文請書 zyz END
    private static void commNoticeConfig(){
        String csv = '<?xml version="1.0" encoding="UTF-8"?><root><Lead__c> <!-- 监听变更字段设定 -->   <LISTENFIELD>name,Comment3__c</LISTENFIELD> <!-- 监听数据条件控制 当ご予約のfield01__cチェック -->   <LISTENFILTER>Field310__c != null</LISTENFILTER> <!--通知グループ指定--> <CHATTERGROUP>11</CHATTERGROUP> </Lead__c><BookingEstimateItem__c>  <!-- 监听变更字段设定 -->   <LISTENFIELD>Amount__c,UnitPrice__c,X2_1__c,UseDate__c</LISTENFIELD>    <!-- 监听数据条件控制 当ご予約のfield01__cチェック -->   <LISTENFILTER>refBooking__r.Relcontact__c != null</LISTENFILTER>    <!--    <WHERE>refBooking__r.Relcontact__c != null and Field4__r.Field1__c = \'0140\'</WHERE> --> <!--通知グループ指定--> <CHATTERGROUP>11</CHATTERGROUP><UPDFIELD value="2019/10/30 10:20">refBooking__r.VBCheckTime__c</UPDFIELD></BookingEstimateItem__c></root>';
        Document doc = new Document();
        doc.Name = 'CommObjectListenConfig';
        doc.DeveloperName = doc.Name;
        doc.FolderId = UserInfo.getUserId();
        doc.Body = Blob.valueOf(csv);
        insert doc;
    }
}