src/objects/AccountAcount__c.object
<CustomObject>
    <description>*** Account Header</description>
    <fields>
        <fullName>Relreserve__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ご予約</label>
        <referenceTo>Lead__c</referenceTo>
        <relationshipLabel>会計</relationshipLabel>
        <relationshipName>Account8Wls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShopCode__c</fullName>
        <label>店舗コード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>frs__c</fullName>
        <label>予約会計</label>
        <referenceTo>RsvAccount__c</referenceTo>
        <relationshipLabel>会計</relationshipLabel>
        <relationshipName>AccountYLM3</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>会計</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>Account#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AccountMaster__c.object
<CustomObject>
    <description>Master of account items</description>
    <fields>
        <fullName>ActionType__c</fullName>
        <description>普通の商品は　デフォルト値：通常で設定する、特別商品に対して、別々、商品種別に設定する
前受付金の場合、会計商品マスたに、価格はNull設定して、入力画面に自由入力する</description>
        <label>商品処理種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>通常</fullName>
                    <default>true</default>
                    <label>通常</label>
                </value>
                <value>
                    <fullName>前受付金</fullName>
                </value>
                <value>
                    <fullName>プラン</fullName>
                </value>
                <value>
                    <fullName>室料</fullName>
                </value>
                <value>
                    <fullName>朝食</fullName>
                </value>
                <value>
                    <fullName>夕食</fullName>
                </value>
                <value>
                    <fullName>非表示</fullName>
                </value>
                <value>
                    <fullName>支払</fullName>
                </value>
                <value>
                    <fullName>サービス料</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>お料理</label>
        <referenceTo>FoodMenu__c</referenceTo>
        <relationshipName>AccountMaster8nAn</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentType__c</fullName>
        <label>支払種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>現金</fullName>
                </value>
                <value>
                    <fullName>カード</fullName>
                </value>
                <value>
                    <fullName>売掛金</fullName>
                </value>
                <value>
                    <fullName>クーポン</fullName>
                </value>
                <value>
                    <fullName>割引</fullName>
                </value>
                <value>
                    <fullName>値引</fullName>
                </value>
                <value>
                    <fullName>予約金</fullName>
                </value>
                <value>
                    <fullName>現金返金</fullName>
                </value>
                <value>
                    <fullName>カード返金</fullName>
                </value>
                <value>
                    <fullName>割増</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ShopInfoRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>店舗情報</label>
        <referenceTo>ShopInformation__c</referenceTo>
        <relationshipLabel>会計商品</relationshipLabel>
        <relationshipName>AccountShopInfoRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会計商品</label>
    <nameField>
        <label>商品名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BookingEstimateItem__c.object
<CustomObject>
    <description>Details Estimate for Booking</description>
    <fields>
        <fullName>ActionType__c</fullName>
        <description>普通の商品は　デフォルト値：通常で設定する、特別商品に対して、別々、商品種別に設定する
前受付金の場合、会計商品マスたに、価格はNull設定して、入力画面に自由入力する</description>
        <label>商品処理種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>通常</fullName>
                    <default>true</default>
                    <label>通常</label>
                </value>
                <value>
                    <fullName>前受付金</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PaymentType__c</fullName>
        <label>支払種別</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>予約見積明細</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>予約見積明細#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CommDefine__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BillReportCommentAutoBreakFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>請求書、見積書、予約確認書コメント文字列の自動改行制御フラグ
TRUE:画面入力の改行を無視して、入力行の文字数により、自動改行を行う
FALSE:画面入力の改行により、その文字はそのまま請求書、見積書、予約確認書に表示する（デフォルト値）</inlineHelpText>
        <label>請求書、見積書、予約確認書コメント自動改行制御</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BillReportStampIsShowFlg__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>請求書にハンコ表示・非表示
TRUE：ハンコ表示(Default値）
FALSE:ハンコ非表示</inlineHelpText>
        <label>請求書ハンコ表示・非表示</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PDFPlanBrkIsShowFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>該当パラメータON設定不可!!!
軽減税率機能有効前提
見積書、会計書、請求書の明細を表示する場合、プラン明細も出力する・しない切替フラグ
TRUE：プラン明細出力表示する
FALSE：プラン明細出力表示しない（デフォルト値）</inlineHelpText>
        <label>RFU</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReducedTaxRateFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>該当機能有効により、多税率混在定義可能になる
TRUE：軽減税率機能有効
FALSE：軽減税率機能無効（デフォルト値）</inlineHelpText>
        <label>軽減税率機能有効フラグ</label>
        <type>Checkbox</type>
    </fields>
    <label>共通定義</label>
</CustomObject>

src/objects/Lead__c.object
<CustomObject>
    <description>Booking sheet with record type</description>
    <fields>
        <fullName>Field298__c</fullName>
        <inlineHelpText>チェックインへ変更することで、予約見積明細の内容が会計計上されます、連泊のお客様のときも日ごとにチェックインステータスへ変更する必要がありますのでご注意が必要です。</inlineHelpText>
        <label>お客様ステータス</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>チェックイン完</fullName>
                </value>
                <value>
                    <fullName>チェックアウト完</fullName>
                </value>
                <value>
                    <fullName>外出中</fullName>
                </value>
                <value>
                    <fullName>入浴中</fullName>
                </value>
                <value>
                    <fullName>滞在中</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ご予約</label>
    <nameField>
        <label>予約名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ReportLogo__c.object
<CustomObject>
    <description>Logo image file for Statement sheet, Estimate sheet and Invoice sheet</description>
    <fields>
        <fullName>ReportLogo__c</fullName>
        <label>レポートロゴ</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ShopInfoRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>店舗情報</label>
        <referenceTo>ShopInformation__c</referenceTo>
        <relationshipName>ShopInfoRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>レポートロゴ</label>
    <nameField>
        <label>請求書ロゴ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ShopInformation__c.object
<CustomObject>
    <description>Shoppers</description>
    <fields>
        <fullName>Payee1__c</fullName>
        <label>振込先１</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payee2__c</fullName>
        <label>振込先２</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payee3__c</fullName>
        <label>振込先３</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PayeeAcount__c</fullName>
        <label>振込先口座</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShopCode__c</fullName>
        <externalId>true</externalId>
        <label>店舗コード</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>店舗情報</label>
    <nameField>
        <label>店舗名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TTend__c.object
<CustomObject>
    <description>*** Account Payment type</description>
    <fields>
        <fullName>PaymentType__c</fullName>
        <label>支払種別</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>会計支払</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>会計支払TranR#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ShopCode__c</fullName>
        <description>従業員所属店舗の店舗コードを指定可能、複数店舗を兼務の場合、カンマで複数店舗コードを一括設定可能
例：複数店舗兼務：01,02,03　→店舗01,02,03兼務になる、デフォルト所属店舗：01
デフォルト所属店舗を指定したい場合、店舗コードの後ろに、「:1」を指定すると、デフォルト店舗を指定可能
例：複数店舗兼務、店舗02はデフォルト所属店舗の場合、下記様に定義可能
-&gt;01,02:1,03</description>
        <inlineHelpText>従業員所属店舗の店舗コードを指定可能、複数店舗を兼務の場合、カンマで複数店舗コードを一括設定可能
例：複数店舗兼務：01,02,03　→店舗01,02,03兼務になる、デフォルト所属店舗：01
デフォルト所属店舗を指定したい場合、店舗コードの後ろに、「:1」を指定すると、デフォルト店舗を指定可能
例：複数店舗兼務、店舗02はデフォルト所属店舗の場合、下記様に定義可能
-&gt;01,02:1,03</inlineHelpText>
        <label>店舗コード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BillPDFTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class BillPDFTest {
	static testMethod void firstTest()
	{
		// TO DO: implement unit test
        Test.startTest();
        // 2018/12/15 請求書-領収書新規レイアウトを追加 WGCH BEGIN
        ReportLogo__c rep = TestCommon.createRepLogo();
        ShopInformation__c shop = TestCommon.createShopInfo();
        rep.ShopInfoRef__c = shop.Id;
        update rep;
        User currUser = [select id, ShopCode__c from user where id = :UserInfo.getUserId()];
        currUser.ShopCode__c = shop.ShopCode__c;
        update currUser;
        // 2018/12/15 請求書-領収書新規レイアウトを追加 WGCH END
        // 予約情報を作成する
    	Lead__c leadInfo = TestCommon.createLead();
    	ExchangeRate__c rate = TestCommon.createExchangeRate(CommBaseCtrl.getCurrency(),'JPY');
    	// 商品情報を作成する
    	List<AccountMaster__c> productLst = TestCommon.createProductMst(1);
    	// 見積明細を作成する
    	TestCommon.createBookEstItem(leadInfo, productLst[0]);
    	// 予約情報のステータス：チェックインに変更する
    	leadInfo.Field298__c = 'チェックイン完';
    	update leadInfo;

    	Test.stopTest();
    	
    	// 会計画面に動作確認を行う
    	List<AccountAcount__c> accObjLst = [select id,frs__c,Relreserve__c from AccountAcount__c where Relreserve__c = :leadInfo.Id];
    	AccountAcount__c accObj = accObjLst[0];

    	ApexPages.StandardController contrl = new ApexPages.StandardController(accObj);
    	
    	Apexpages.currentPage().getParameters().put('bulkId',accObj.Id);
    	BillPDF pdf1 = new BillPDF(contrl);
    	System.assert(pdf1.getTran() != null);
    	System.debug('20161111111111::::::::::::');
	}
    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        Test.startTest();
        // 2018/12/15 請求書-領収書新規レイアウトを追加 WGCH BEGIN
        ReportLogo__c rep = TestCommon.createRepLogo();
        ShopInformation__c shop = TestCommon.createShopInfo();
        rep.ShopInfoRef__c = shop.Id;
        update rep;
        User currUser = [select id, ShopCode__c from user where id = :UserInfo.getUserId()];
        currUser.ShopCode__c = shop.ShopCode__c;
        update currUser;
        // 2018/12/15 請求書-領収書新規レイアウトを追加 WGCH END
        // 予約情報を作成する
    	Lead__c leadInfo = TestCommon.createLead();
    	ExchangeRate__c rate = TestCommon.createExchangeRate(CommBaseCtrl.getCurrency(),'JPY');
    	// 商品情報を作成する
    	List<AccountMaster__c> productLst = TestCommon.createProductMst(1);
    	// 見積明細を作成する
    	TestCommon.createBookEstItem(leadInfo, productLst[0]);
    	// 予約情報のステータス：チェックインに変更する
    	leadInfo.Field298__c = 'チェックイン完';
    	update leadInfo;

    	Test.stopTest();
    	
    	// 会計画面に動作確認を行う
    	List<AccountAcount__c> accObjLst = [select id,frs__c,Relreserve__c from AccountAcount__c where Relreserve__c = :leadInfo.Id];
    	AccountAcount__c accObj = accObjLst[0];

    	ApexPages.StandardController contrl = new ApexPages.StandardController(accObj);
    	
    	//Apexpages.currentPage().getParameters().put('id',accObj.Id);
    	Apexpages.currentPage().getParameters().put('bulkId',accObj.Id);
    	Apexpages.currentPage().getParameters().put('cy','JPY');
    	BillPDF pdf = new BillPDF(contrl);
    	pdf.extInitAction();
    	pdf.getNumberFormat();
    	
    	
    	pdf.getAccoutInfo();
    	pdf.getAccountNo();
    	pdf.getCustomer();
    	pdf.getCharge();
    	pdf.getRequestAmount();
    	pdf.getTax();
    	pdf.getIssueDate();
    	pdf.getAdvancesReceived();
    	pdf.getTran();
    	pdf.getAmoutIncDiscont();
    	pdf.getServiceDate();
    	
    	// TO DO: implement unit test
    		TestCommon.createShopInfo();
    	
    	Apexpages.currentPage().getParameters().put('bulkId',accObj.Id);
    	BillPDF pdf1 = new BillPDF(contrl);
    	//pdf.getReportLogo();
    	//pdf.isFirstPage();
    	System.assert(pdf1.getTran() != null);
    }
    static testMethod void myUnitTest1() {   
        // TO DO: implement unit test
        Test.startTest();
        // 2018/12/15 請求書-領収書新規レイアウトを追加 WGCH BEGIN
        ReportLogo__c rep = TestCommon.createRepLogo();
        ShopInformation__c shop = TestCommon.createShopInfo();
        rep.ShopInfoRef__c = shop.Id;
        update rep;
        // 2018/12/15 請求書-領収書新規レイアウトを追加 WGCH END
        JMST__c taxMst = TestCommon.createTaxMst();
        CommDefine__c def = TestCommon.createCommDefine();
   		def.BillReportCommentAutoBreakFlg__c = false;
   		def.BillReportStampIsShowFlg__c = true;
   		// 2019/07/30 軽減税率機能対応 WGCH BEGIN
   		def.ReducedTaxRateFlg__c = true;
   		def.PDFPlanBrkIsShowFlg__c = true;
   		// 2019/07/30 軽減税率機能対応 WGCH END
    	update def;
        ShopInformation__c shopInfo = TestCommon.createShopInfo();
    	shopInfo.payee1__c = '23';
    	shopInfo.payee2__c = '23';
    	shopInfo.payee3__c = '23';
    	shopInfo.payeeAcount__c = '23';
    	update shopInfo;
    	ReportLogo__c tempShopLogo = TestCommon.createRepLogo();
        tempShopLogo.ShopInfoRef__c = shopInfo.Id;
        update tempShopLogo;
    	User currUser = [select id, ShopCode__c from user where id = :UserInfo.getUserId()];
    	currUser.ShopCode__c = shopInfo.ShopCode__c;
    	update currUser;
        // 予約情報を作成する
    	Lead__c leadInfo = TestCommon.createLead();
    	ExchangeRate__c rate = TestCommon.createExchangeRate(CommBaseCtrl.getCurrency(),'JPY');
    	// 商品情報を作成する
    	List<AccountMaster__c> productLst = TestCommon.createProductMst(4);
    	// 見積明細を作成する
    	BookingEstimateItem__c bookingItem = TestCommon.createBookEstItem(leadInfo, productLst[0]);
        // 商品２は前受付金に変更を行う
        AccountMaster__c accMst = productLst[1];
        accMst.ActionType__c = CommConst.PROD_ACTION_TYPE_AR;
        accMst.PaymentType__c = 'カード';  // XMLの定義と合わせるが必要です
        update accMst;
        AccountMaster__c accMstPay = productLst[2];
        accMstPay.ActionType__c = CommConst.PROD_ACTION_TYPE_PY;
        accMstPay.PaymentType__c = '現金';    // XMLの定義と合わせるが必要です
        update accMstPay;
    	// 予約情報のステータス：チェックインに変更する
    	leadInfo.Field298__c = 'チェックイン完';
    	update leadInfo;
    	RsvAccount__c rsv = TestCommon.createRsvAccount();
    	AccountAcount__c aa = TestCommon.createAccountAcount(rsv.Id, leadInfo.Id);
    	// 会計画面に動作確認を行う
    	List<AccountAcount__c> accObjLst = [select id,frs__c,Relreserve__c from AccountAcount__c where Relreserve__c = :leadInfo.Id];
    	AccountAcount__c accObj = accObjLst[0];
    	TTend__c ttitem = TestCommon.createTTend(rsv.Id, accObj.Id); 
    	ttitem.field2__c = '22'; 
    	ttitem.field3__c = '予約金';
    	//ttitem.Field28__c = 5000;  
    	//ttitem.Field29__c = 5000;    	
    	ttitem.RowNo__c  = 44;	// メディア種別,メディア名称
		ttitem.Field16__c = '55';
		ttitem.Field17__c = '66';
		ttitem.Field20__c = '77';// 単価,枚数,支払金額 
		//ttitem.SplitGroupNo__c = '88';
		//ttitem.PaymentType__c = '99';
		//ttitem.PayProductName__c = '111';
		//ttitem.UseDate__c = Date.today();
		update ttitem;
		Apexpages.currentPage().getParameters().put('id',leadInfo.Id);
		//System.debug(LoggingLevel.INFO, 'TTend__c::::::::::::' + [select field3__c, Field1__c from TTend__c
		//	where  ( Field3__c = :CommConst.MEDIA_TYPE_11 OR Field3__c = :CommConst.MEDIA_TYPE_21) 
		//	Group by Field3__c, Field1__c]);
    	Test.stopTest();   	
    	ApexPages.StandardController contrl = new ApexPages.StandardController(accObj);
    	BillInput_Ctrl ctrl = new BillInput_Ctrl(contrl);
    	ctrl.initAction();
    	ctrl.calPaymentInfo();
    	ctrl.upsertData();
    	//Apexpages.currentPage().getParameters().put('id',accObj.Id);
    	Apexpages.currentPage().getParameters().put('bulkId',accObj.Id);
    	Apexpages.currentPage().getParameters().put('cy','JPY');
    	BillPDF pdf = new BillPDF(contrl);
    	pdf.extInitAction();
    	pdf.getNumberFormat(); 
    	pdf.getReportLogo();	
    	pdf.getAccoutInfo();
    	pdf.getAccountNo();
    	pdf.getCustomer();
    	pdf.getCharge();
    	pdf.getRequestAmount();
    	pdf.getTax();
    	pdf.getIssueDate();
    	pdf.getAdvancesReceived();
    	pdf.getTran();
    	pdf.getAmoutIncDiscont();
    	pdf.getServiceDate();
    	pdf.getServiceAmount ();   	
    	// TO DO: implement unit test
    		TestCommon.createShopInfo();    	
    	Apexpages.currentPage().getParameters().put('bulkId',accObj.Id);
    	BillPDF pdf1 = new BillPDF(contrl);
    	//pdf.getReportLogo();
    	//pdf.isFirstPage();
    	System.assert(pdf1.getTran() != null);
    	CommUtils.ProductInfo priceInfo = new CommUtils.ProductInfo();
    	// 特別税
    	Decimal SpecialTax = productLst[0].SpecialTax__c;
		Decimal unitPrice = CommUtils.nullToZero(productLst[0].Field5__c);  // <-税金含め単価です
		Decimal qty = CommUtils.nullToZero(bookingItem.Amount__c);
        priceInfo.process(unitPrice , qty , taxMst.TaxRate__c, productLst[0].ServiceRate__c);    	
    	// 金額設定判定		
    }
    static testMethod void myUnitTest2() {
        // TO DO: implement unit test
        Test.startTest();
        // 2018/12/15 請求書-領収書新規レイアウトを追加 WGCH BEGIN
        ReportLogo__c rep = TestCommon.createRepLogo();
        ShopInformation__c shop = TestCommon.createShopInfo();
        rep.ShopInfoRef__c = shop.Id;
        update rep;
        User currUser = [select id, ShopCode__c from user where id = :UserInfo.getUserId()];
        currUser.ShopCode__c = shop.ShopCode__c;
        update currUser;
        // 2018/12/15 請求書-領収書新規レイアウトを追加 WGCH END
        JMST__c taxMst = TestCommon.createTaxMst();
        CommDefine__c def = TestCommon.createCommDefine();
   		def.BillReportCommentAutoBreakFlg__c = false;
   		def.BillReportStampIsShowFlg__c = true;
   		def.BillInputSwitchCode__c='2';
   		// 2019/07/30 軽減税率機能対応 WGCH BEGIN
   		def.ReducedTaxRateFlg__c = true;
   		def.PDFPlanBrkIsShowFlg__c = true;
		def.BillReportReceiptIsShowFlg__c = true;
   		// 2019/07/30 軽減税率機能対応 WGCH END
    	update def;
        // 予約情報を作成する
    	Lead__c leadInfo = TestCommon.createLead();
    	ExchangeRate__c rate = TestCommon.createExchangeRate(CommBaseCtrl.getCurrency(),'JPY');
    	// 商品情報を作成する
    	List<AccountMaster__c> productLst = TestCommon.createProductMst(1);
    	// 見積明細を作成する
    	BookingEstimateItem__c bookingItem = TestCommon.createBookEstItem(leadInfo, productLst[0]);
    	// 予約情報のステータス：チェックインに変更する
    	leadInfo.Field298__c = 'チェックイン完';
    	update leadInfo;
        RsvAccount__c rsv = TestCommon.createRsvAccount();
    	AccountAcount__c aa = TestCommon.createAccountAcount(rsv.Id, leadInfo.Id);
    	// 会計画面に動作確認を行う
    	List<AccountAcount__c> accObjLst = [select id,frs__c,IsNewLayout__c,Relreserve__c from AccountAcount__c where Relreserve__c = :leadInfo.Id];
    	AccountAcount__c accObj = accObjLst[0];
    	TTend__c ttitem = TestCommon.createTTend(rsv.Id, accObj.Id); 
    	ttitem.field2__c = '22'; 
    	ttitem.field3__c = '予約金';
    	//ttitem.Field28__c = 5000;  
    	//ttitem.Field29__c = 5000;    	
    	ttitem.RowNo__c  = 44;	// メディア種別,メディア名称
		ttitem.Field16__c = '55';
		ttitem.Field17__c = '66';
		ttitem.Field20__c = '77';// 単価,枚数,支払金額 
		//ttitem.SplitGroupNo__c = '88';
		//ttitem.PaymentType__c = '99';
		//ttitem.PayProductName__c = '111';
		//ttitem.UseDate__c = Date.today();
		update ttitem;
    	Test.stopTest();
    	ApexPages.StandardController contrl = new ApexPages.StandardController(accObj);
    	
    	//Apexpages.currentPage().getParameters().put('id',accObj.Id);
    	Apexpages.currentPage().getParameters().put('bulkId',accObj.Id);
    	Apexpages.currentPage().getParameters().put('cy','JPY');
    	BillPDF pdf = new BillPDF(contrl);
    	pdf.extInitAction();
    	pdf.getNumberFormat();	
    	pdf.getAccoutInfo();
    	pdf.getAccountNo();
    	pdf.getCustomer();
    	pdf.getCharge();
    	pdf.getRequestAmount();
    	pdf.getTax();
    	pdf.getIssueDate();
    	pdf.getAdvancesReceived();
    	pdf.getTran();
    	pdf.getAmoutIncDiscont();
    	pdf.getServiceDate();   	
    	// TO DO: implement unit test
    		TestCommon.createShopInfo();
    	
    	Apexpages.currentPage().getParameters().put('bulkId',accObj.Id);
    	BillPDF pdf1 = new BillPDF(contrl);
    	//pdf.getReportLogo();
    	//pdf.isFirstPage();
    	System.assert(pdf1.getTran() != null);
    	CommUtils.ProductInfo priceInfo = new CommUtils.ProductInfo();
    	// 特別税
    	Decimal SpecialTax = productLst[0].SpecialTax__c;
		Decimal unitPrice = CommUtils.nullToZero(productLst[0].Field5__c);  // <-税金含め単価です
		Decimal qty = CommUtils.nullToZero(bookingItem.Amount__c);
        priceInfo.process(unitPrice , qty , taxMst.TaxRate__c, productLst[0].ServiceRate__c);    	
    	// 金額設定判定		
    } 
    
}