src/objects/AccountMaster__c.object
<CustomObject>
    <description>Master of account items</description>
    <fields>
        <fullName>BestDateInfo__c</fullName>
        <label>賞味期限</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategorySub__c</fullName>
        <label>カテゴリサブ</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>素材</fullName>
                </value>
                <value>
                    <fullName>野菜類</fullName>
                </value>
                <value>
                    <fullName>肉類</fullName>
                </value>
                <value>
                    <fullName>魚介類</fullName>
                </value>
                <value>
                    <fullName>半加工品</fullName>
                </value>
                <value>
                    <fullName>加工・出汁系</fullName>
                </value>
                <value>
                    <fullName>完成品</fullName>
                </value>
                <value>
                    <fullName>おみやげ品</fullName>
                </value>
                <value>
                    <fullName>珍味</fullName>
                </value>
                <value>
                    <fullName>ハラール</fullName>
                </value>
                <value>
                    <fullName>食材その他</fullName>
                </value>
                <value>
                    <fullName>ビール</fullName>
                </value>
                <value>
                    <fullName>日本酒</fullName>
                </value>
                <value>
                    <fullName>ワイン</fullName>
                </value>
                <value>
                    <fullName>焼酎</fullName>
                </value>
                <value>
                    <fullName>飲料おみやげ品</fullName>
                </value>
                <value>
                    <fullName>飲料その他</fullName>
                </value>
                <value>
                    <fullName>食器</fullName>
                </value>
                <value>
                    <fullName>電気製品</fullName>
                </value>
                <value>
                    <fullName>家具・調度</fullName>
                </value>
                <value>
                    <fullName>アメニティ類</fullName>
                </value>
                <value>
                    <fullName>備品おみやげ品</fullName>
                </value>
                <value>
                    <fullName>備品その他</fullName>
                </value>
                <value>
                    <fullName>マネージャー</fullName>
                </value>
                <value>
                    <fullName>調理人</fullName>
                </value>
                <value>
                    <fullName>接客担当</fullName>
                </value>
                <value>
                    <fullName>清掃担当</fullName>
                </value>
                <value>
                    <fullName>予約担当</fullName>
                </value>
                <value>
                    <fullName>人材その他</fullName>
                </value>
                <value>
                    <fullName>建築・リフォーム</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>カテゴリ</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>食材</fullName>
                </value>
                <value>
                    <fullName>飲料</fullName>
                </value>
                <value>
                    <fullName>備品</fullName>
                </value>
                <value>
                    <fullName>人材</fullName>
                </value>
                <value>
                    <fullName>サービス</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charge__c</fullName>
        <label>手数料(%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <label>内容量</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CookCount__c</fullName>
        <label>$料理数量</label>
        <summaryForeignKey>FoodDetail__c.AccountMasterRef__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>DeliveryType__c</fullName>
        <label>配達及びコンタクト</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>取りに行く</fullName>
                </value>
                <value>
                    <fullName>宅配便</fullName>
                </value>
                <value>
                    <fullName>ルート配送</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>商品説明</label>
        <length>10240</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DiscountType__c</fullName>
        <label>キャンペーン方式</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>値引</fullName>
                </value>
                <value>
                    <fullName>割引</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DisplayDate__c</fullName>
        <inlineHelpText>EXPOに公開したい場合、該当公開開始予定日を設定してください</inlineHelpText>
        <label>EXPO開示開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExpoAreaMstCode__c</fullName>
        <label>地域情報コード</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>その他</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExpoAreaMstLab__c</fullName>
        <inlineHelpText>詳細画面の「地域情報」ボタンで設定してください</inlineHelpText>
        <label>地域情報</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>未設定</fullName>
                    <default>true</default>
                    <label>未設定</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExpoHrInfoRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>カテゴリが人材の場合、人材属性情報を入力してください</inlineHelpText>
        <label>人材属性情報</label>
        <referenceTo>ExpoHrInfo__c</referenceTo>
        <relationshipLabel>会計商品</relationshipLabel>
        <relationshipName>ExpoHrInfoRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExpoOrgInfoRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expo組織情報</label>
        <referenceTo>ExpoOrgInfo__c</referenceTo>
        <relationshipLabel>会計商品</relationshipLabel>
        <relationshipName>ExpoOrgInfoRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExpoStockCount__c</fullName>
        <description>Expoサイト専用</description>
        <inlineHelpText>在庫数情報管理</inlineHelpText>
        <label>Expo在庫数</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Field5__c</fullName>
        <label>単価</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Field7__c</fullName>
        <label>原価</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GoodFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <label>おすすめ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LimitedFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <label>期間限定</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <label>原材料</label>
        <length>2048</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>原産国名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OutsourceFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <label>業務委託</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PayType__c</fullName>
        <label>利用できる決済方法</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>売掛</fullName>
                </value>
                <value>
                    <fullName>カード</fullName>
                </value>
                <value>
                    <fullName>振込（事前入金）</fullName>
                </value>
                <value>
                    <fullName>代引</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductStatus__c</fullName>
        <inlineHelpText>新品/中古</inlineHelpText>
        <label>商品状態</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>新品</fullName>
                </value>
                <value>
                    <fullName>中古</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PurchaseMaxNum__c</fullName>
        <label>個人最大購買数</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RepeatDiscountPrice__c</fullName>
        <label>定期購入価格値引</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RepeatDiscountRate__c</fullName>
        <label>定期購入価額割引</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>RepeaterFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <label>定期購入</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SalesStatus__c</fullName>
        <label>販売状態</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>販売中</fullName>
                    <default>true</default>
                    <label>販売中</label>
                </value>
                <value>
                    <fullName>停止中</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ServiceRate__c</fullName>
        <description>サービス料金（％）</description>
        <label>サービス料(%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ShippingDays__c</fullName>
        <inlineHelpText>ご注文から出荷までの所要時間の目安です</inlineHelpText>
        <label>発送可能日</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShopInfoRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>店舗情報</label>
        <referenceTo>ShopInformation__c</referenceTo>
        <relationshipLabel>会計商品</relationshipLabel>
        <relationshipName>AccountShopInfoRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SpDescription__c</fullName>
        <label>商品簡易説明</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SpecialMemo__c</fullName>
        <label>注意事項</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>StaffName__c</fullName>
        <label>人材名前</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorkContent__c</fullName>
        <label>人材仕事内容</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>WorkRole__c</fullName>
        <label>人材役割</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>jmstRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>消費税マスタ</label>
        <referenceTo>JMST__c</referenceTo>
        <relationshipName>jmst</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会計商品</label>
    <nameField>
        <label>商品名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ExpoUser__c.object
<CustomObject>
    <fields>
        <fullName>ExpoOrgInfoRef__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>組織情報参照</description>
        <label>Expo組織情報</label>
        <referenceTo>ExpoOrgInfo__c</referenceTo>
        <relationshipLabel>Expoユーザ</relationshipLabel>
        <relationshipName>ExpoOrgInfoRefe</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Expoユーザ</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ShopInformation__c.object
<CustomObject>
    <description>Shoppers</description>
    <fields>
        <fullName>ExpoOrgInfoRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expo組織情報</label>
        <referenceTo>ExpoOrgInfo__c</referenceTo>
        <relationshipLabel>店舗情報</relationshipLabel>
        <relationshipName>ExpoOrgInfoRefs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>店舗情報</label>
    <nameField>
        <label>店舗名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ExpoAccountMasterEditCtrl.cls
public with sharing class ExpoAccountMasterEditCtrl extends ExpoCommBaseCtrl{
	private static final String APPOTION_NAMESPACE = CommConst.APPOTION_NAMESPACE;
	public String parentDsJson{get;set;} // 级联主DATA
	public String childDsJson{get;set;} // 级联子DATA
	public AccountMaster__c accMaster{get;set;} //会计商品
	public ExpoHelperUtil.ExpoFieldInfo expo{get;set;}	// 返回数据
	public String dataId{get;set;}
	// *配置API必须小写* 固定标准必填字段
	private static final set<String> fieldReqSet = new set<String>{'name','displaydate__c','category__c','categorysub__c','shopinforef__c','field5__c','expostockcount__c','shippingdays__c','paytype__c','deliverytype__c'};
	// *配置API必须小写* 固定只读字段
	private static final set<String> fieldRomSet = new set<String>{};
	// *配置API必须小写* 固定不显示字段
	// 2019/04/03 TEST[LOOKUP] WGCH BEGIN
	private static final set<String> fieldNotSet = new set<String>{'id','cookcount__c','expoorginforef__c', 'expoareamstcode__c'};
	// 2019/04/03 TEST[LOOKUP] WGCH END
	// XML为空时,默认显示 版块Key
	private static List<String> defOrderLst = new List<String>{'0','1','2','3','4','5'}; // 版块顺序
	private static map<String,String> defMap = new map<String,String>{'0' => '商品基本;2;Name,Field7__c,DisplayDate__c,jmstRef__c:消費税,Category__c,ServiceRate__c:サービス料,CategorySub__c,ShopInfoRef__c,Field5__c,ExpoStockCount__c:在庫,Charge__c,SalesStatus__c,ShippingDays__c,$_blank_$,PayType__c:決済方法,$_blank_$,DeliveryType__c;','1' => 'EXPO基本情報;1;SpDescription__c,Description__c,Content__c,Material__c,Origin__c,BestDateInfo__c,SpecialMemo__c, PurchaseMaxNum__c;','2' => '定期購入;2;RepeaterFlg__c,RepeatDiscountPrice__c,DiscountType__c,RepeatDiscountRate__c;','3' => '商品フラグ;1;LimitedFlg__c,ProductStatus__c:商品状態,OutsourceFlg__c,GoodFlg__c;','4' => '人材;1;StaffName__c,WorkRole__c,ExpoHrInfoRef__c,WorkContent__c;','5' => '地域;1;ExpoAreaMstLab__c;'};
	// DOUBLE类型的数据的格式
	public String getNumberFormat() {
		return CommUtils.getNumberFormat();
	}
	public ExpoAccountMasterEditCtrl(){
		accMaster = new AccountMaster__c();
	}
	public PageReference initAct() {
		// *****************************
		// 共通処理呼び出す
		// *****************************
		PageReference pg = checkLogin();
		if (pg != null) return pg;
		// *****************************
		// 実際の業務ロジック処理展開
		// *****************************
		
		// 获取会计商品ID
		dataId = Apexpages.currentpage().getparameters().get('Id');
		// 页面显示的数据处理
		getExpoShopInfoXML();
		return null;
	}
	// 获取数据集
	public void getExpoShopInfoXML(){
		expo = ExpoHelperUtil.getExpoXML('ACCMASTERFIELDS', AccountMaster__c.sObjectType, fieldReqSet, fieldRomSet, fieldNotSet);
		if(expo.custApiSet.isEmpty()){
			expo = ExpoHelperUtil.getExpoDef(defOrderLst, defMap, AccountMaster__c.sObjectType, fieldReqSet, fieldRomSet, fieldNotSet);
		}
		// 级联字段特殊处理
		parentDsJson = childDsJson = '[]';
		if(expo.custApiSet.contains('category__c') && expo.custApiSet.contains('categorysub__c') ){
			ExpoHelperUtil.KendoDataSourceAll kendo = ExpoHelperUtil.getDependentOptions(APPOTION_NAMESPACE + 'AccountMaster__c', APPOTION_NAMESPACE + 'Category__c', APPOTION_NAMESPACE + 'CategorySub__c');
			parentDsJson = JSON.serialize(kendo.parentKendoDs);
			childDsJson = JSON.serialize(kendo.childKendoDs);
			expo.custFieldInfoMap.get('category__c').fieldTyp = ExpoHelperUtil.API_TYPE.CPLST.name();
			expo.custFieldInfoMap.get('categorysub__c').fieldTyp = ExpoHelperUtil.API_TYPE.CPLST.name();
		}
		if (!CommUtils.isBlank(dataId)){
			// 2019/04/03 TEST[LOOKUP] WGCH BEGIN
			String queryStr = ' Select ExpoAreaMstCode__c, ';
			// 2019/04/03 TEST[LOOKUP] WGCH END
			for(String api : expo.custApiSet) queryStr += api + ',' ;
			queryStr = queryStr.removeEnd(',');
			queryStr += ' From AccountMaster__c Where Id =: dataId ';
			accMaster = DataBase.query(queryStr);
			ExpoHelperUtil.setApiVal(accMaster, expo);
		}
	}
	// 参照字段のデータ取得する
	@remoteaction 
	public static List<ExpoHelperUtil.KendoDataSource> getRefDs(String ref,String ExpoInfoRef){
		String querySQL = 'select id,name ';
		if(ref == (APPOTION_NAMESPACE + 'jmst__c')) querySQL += ' ,TaxRate__c ';
		querySQL += ' from ' + ref;
		if((ref == (APPOTION_NAMESPACE +'shopinformation__c') || ref == (APPOTION_NAMESPACE + 'expouser__c')) && !CommUtils.isBlank(ExpoInfoRef)) querySQL += ' where ExpoOrgInfoRef__c =: ExpoInfoRef order by name';
		List<ExpoHelperUtil.KendoDataSource> selectOptionDsLst = new List<ExpoHelperUtil.KendoDataSource>{new ExpoHelperUtil.KendoDataSource('', '')};
		for (Sobject s : Database.query(querySQL)) {
			String textStr = CommUtils.nullToBlank(s.get('id'));
			String valueStr = CommUtils.nullToBlank(s.get('name'));
			if(ref == (APPOTION_NAMESPACE + 'jmst__c')) valueStr = Integer.valueOf(CommUtils.nullToZero(s.get('TaxRate__c')))+'%';
			selectOptionDsLst.add(new ExpoHelperUtil.KendoDataSource(valueStr, textStr));
		}
		return selectOptionDsLst;
	}
	// 保存
	@remoteaction 
	public static String saveInfo(String dataId, String fieldJson, String expoOrgInfoRef){
		AccountMaster__c accMasterItem = new AccountMaster__c();
		if(!CommUtils.isBlank(expoOrgInfoRef)) accMasterItem.ExpoOrgInfoRef__c = expoOrgInfoRef;
		return ExpoHelperUtil.saveInfo(dataId, fieldJson, accMasterItem);
	}
	
}