src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountType__c</fullName>
        <label>取引先種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>通常</fullName>
                    <default>true</default>
                    <label>通常</label>
                </value>
                <value>
                    <fullName>旅行会社</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContractStatus__c</fullName>
        <label>契約状態</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>有効</fullName>
                </value>
                <value>
                    <fullName>無効</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesOfficeCompanyCodeTLAPI__c</fullName>
        <label>旅行会社コードAPI_TL</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesOfficeCompanyType__c</fullName>
        <label>旅行会社分類</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>リアル</fullName>
                </value>
                <value>
                    <fullName>ネット</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/JMST__c.object
<CustomObject>
    <description>Tax of sales</description>
    <label>消費税</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>消費税マスタ名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>Master Package code Plan</description>
    <fields>
        <fullName>AccountA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountA</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipLabel>プラン</relationshipLabel>
        <relationshipName>Planm8c9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AccountB__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountB</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipLabel>プラン (AccountB)</relationshipLabel>
        <relationshipName>Planm8cT</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AccountC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountC</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipLabel>プラン (AccountC)</relationshipLabel>
        <relationshipName>Planm8cd</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AccountTotal__c</fullName>
        <formula>Charge1__c  +  Charge2__c  +  Charge3__c  +  ChargeRC__c   +  mealcost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AccountTotal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BasePlanFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <description>プラングループ設定機能利用する場合、基本プラン標識する</description>
        <label>ベースプラン</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charge1__c</fullName>
        <formula>AccountA__r.Field5__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Charge1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge2__c</fullName>
        <formula>AccountB__r.Field5__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Charge2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge3__c</fullName>
        <formula>AccountC__r.Field5__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Charge3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ChargeRC__c</fullName>
        <label>ChargeRC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>コメント</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DpRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>カテゴリ</label>
        <referenceTo>DP__c</referenceTo>
        <relationshipLabel>プラン</relationshipLabel>
        <relationshipName>PlanDpRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GpRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>部門</label>
        <referenceTo>GP__c</referenceTo>
        <relationshipLabel>プラン</relationshipLabel>
        <relationshipName>PlanGpRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Image1__c</fullName>
        <label>イメージ1</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Image2__c</fullName>
        <label>イメージ2</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Image3__c</fullName>
        <label>イメージ3</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Image4__c</fullName>
        <label>イメージ4</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsClosed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>非公開</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JmstRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>消費税</label>
        <referenceTo>JMST__c</referenceTo>
        <relationshipLabel>プラン</relationshipLabel>
        <relationshipName>PlanJmsRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lunch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lunch</label>
        <referenceTo>FoodMenu__c</referenceTo>
        <relationshipLabel>プラン (Lunch)</relationshipLabel>
        <relationshipName>PlanApAl</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PackageCode__c</fullName>
        <label>パッケージコード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PlanNo__c</fullName>
        <label>PlanNo</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PlanStartDateandtime__c</fullName>
        <label>プランオープン日時</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Plan_URL__c</fullName>
        <label>Plan URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Planclosedateandtime__c</fullName>
        <label>プランクローズ日時</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>プラン金額</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PublicPlan__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>サイトへ公開するプランにはチェックを入れる</inlineHelpText>
        <label>PublicPlan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Roomname__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guest room name</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>プラン</relationshipLabel>
        <relationshipName>planTvYQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Roomtype__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guest room type</label>
        <referenceTo>Type__c</referenceTo>
        <relationshipLabel>プラン</relationshipLabel>
        <relationshipName>planxx0r</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seq__c</fullName>
        <label>Seq#</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ServiceN__c</fullName>
        <formula>Roomname__r.heyadashiryouryou__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ServiceNY$</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ServiceRate__c</fullName>
        <label>サービス料(%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <formula>Roomname__r.heyadashiryou__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service$</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ShopInfoRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>店舗情報</label>
        <referenceTo>ShopInformation__c</referenceTo>
        <relationshipLabel>プラン</relationshipLabel>
        <relationshipName>PlanShopInfoRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AGT</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>プラン</relationshipLabel>
        <relationshipName>planXE9c</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dinner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dinner</label>
        <referenceTo>FoodMenu__c</referenceTo>
        <relationshipLabel>プラン</relationshipLabel>
        <relationshipName>planA8mD</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>mealcost__c</fullName>
        <formula>IF ( dinner__r.Currency__c  &gt; 0 &amp;&amp;  Lunch__r.Currency__c &gt; 0, morning__r.Currency__c  +  dinner__r.Currency__c, morning__r.Currency__c  +  dinner__r.Currency__c +  Lunch__r.Currency__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cost of meal/person</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>morning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Morning</label>
        <referenceTo>FoodMenu__c</referenceTo>
        <relationshipLabel>プラン (朝食)</relationshipLabel>
        <relationshipName>planA8mN</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>プラン</label>
    <nameField>
        <label>Plan</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ReportLogo__c.object
<CustomObject>
    <description>Logo image file for Statement sheet, Estimate sheet and Invoice sheet</description>
    <fields>
        <fullName>ShopInfoRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>店舗情報</label>
        <referenceTo>ShopInformation__c</referenceTo>
        <relationshipName>ShopInfoRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>レポートロゴ</label>
    <nameField>
        <label>請求書ロゴ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ShopInformation__c.object
<CustomObject>
    <description>Shoppers</description>
    <fields>
        <fullName>Seq__c</fullName>
        <label>Seq#</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ShopCode__c</fullName>
        <externalId>true</externalId>
        <label>店舗コード</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>店舗情報</label>
    <nameField>
        <label>店舗名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TA_MasterSyncService.cls
global with sharing class TA_MasterSyncService {
	/**
	* TL側のプランマスタ定義情報の取込み
	* 取り込み後、自動的に、関連のプラン会計商品も自動作成
	**/
	webservice static String importPlanMaster(String branchShopCd, Boolean isSync) {
		// 指定の店舗コードはNULLの場合、店舗情報マスタから店舗コードを取得する、多店舗じゃない場合、単店舗情報を取得する
		List<String> shopCdsLst = getImportShopCodes(branchShopCd);
		Map<String, ShopInformation__c> shopInfoMap = ShopInfoUtil.getShopInfoMap();
		// 消費税マスタ
		JMST__c taxRateInf = CommLogicProcess.getTaxRateInfo();
		// 初期化
		map<String, Plan__c> tlMsgTypeRooms = new map<String, Plan__c>();
		set<String> planShopSet = new set<String>();
		set<String> pkgCdSet = new set<String>();
		TA_ServiceCtrl taService = new TA_ServiceCtrl();
		/*
		Map<String, Account> accMap = new Map<String, Account>();
		
		// 既存のAGT情報を取得する
		String salesOfficeCompanyType =  'ネット';
		String contractStatus =  '有効';
		String accountType =  CommConst.ACCOUNT_TYPE_TRAVEL;
		List<Account> accList = [select Id, Name, SalesOfficeCompanyCodeTLAPI__c from Account where SalesOfficeCompanyType__c = :salesOfficeCompanyType and ContractStatus__c = :contractStatus and AccountType__c = :accountType];
		Map<String, String> agtCodeMap = new Map<String, String>();
		for (Account s:accList ) {
			agtCodeMap.put(s.SalesOfficeCompanyCodeTLAPI__c, s.Id);
		}*/
		// 各店舗のプラン定義情報を取得する
		for (String shopCd : shopCdsLst) {
			// 契約していない店舗情報は取込対象外になる
			if (!TA_ServiceConfigHelp.isContractShop(shopCd)) continue;
			// APIを呼出
			TA_PlanInfoItem netRep = taService.callNetPlanMasterSearchService(shopCd);
			if (!netRep.commonResponse.isSuccess) {
				return netRep.commonResponse.failureReason + ':' + netRep.commonResponse.errorDescription;
			}
			for (TA_PlanInfoItem.PlanInfo rm: netRep.planList) {
				Plan__c nPlan = new Plan__c(
					PackageCode__c = rm.planCode,
					Name = rm.planName,
					//client__c = agtCodeMap.get(rm.agtCode),
					ShopInfoRef__c = shopInfoMap.containsKey(shopCd) ? shopInfoMap.get(shopCd).Id : null,
					Price__c = 0,
					JmstRef__c = taxRateInf.Id
				);
				String nkey = getPlanKey(nPlan);
				tlMsgTypeRooms.put(nkey, nPlan);
				planShopSet.add(shopCd);
				pkgCdSet.add(rm.planCode);
			}
			/*
			netRep.planGroupList = (netRep.planGroupList == null) ? new TL_NetPlanMasterSearchService.planGroup[0] : netRep.planGroupList;
			for (TL_NetPlanMasterSearchService.planGroup rm: netRep.planGroupList) {
				Plan__c nPlan = new Plan__c(
					PackageCode__c = rm.planGroupCode,
					Name = rm.planGroupName,
					ShopInfoRef__c = shopInfoMap.containsKey(shopCd) ? shopInfoMap.get(shopCd).Id : null,
					Price__c = 0,
					JmstRef__c = taxRateInf.Id
				);
				String nkey = getPlanKey(nPlan);
				tlMsgTypeRooms.put(nkey, nPlan);
				planShopSet.add(shopCd);
				pkgCdSet.add(rm.planGroupCode);
			}*/
		}
System.debug(loggingLevel.INFO, 'tlMsgTypeRooms:=' + tlMsgTypeRooms);
		if (!tlMsgTypeRooms.isEmpty()) {
			List<Plan__c> nwlst = new List<Plan__c>();
			List<Plan__c> existRoomTypes = [select Id, Name, AccountA__c, AccountB__c, AccountC__c, AccountTotal__c, Charge1__c, Charge2__c, Charge3__c, ChargeRC__c, Comment__c, DpRef__c, GpRef__c, Image1__c, Image2__c, Image3__c, Image4__c, IsClosed__c, JmstRef__c, Lunch__c, PackageCode__c, PlanNo__c, PlanStartDateandtime__c, Plan_URL__c, Planclosedateandtime__c, Price__c, PublicPlan__c, Roomname__c, Roomtype__c, Seq__c, ServiceN__c, ServiceRate__c, Service__c, client__c, dinner__c, mealcost__c, morning__c, BasePlanFlg__c, ShopInfoRef__c from Plan__c 
											where ShopInfoRef__r.ShopCode__c in :planShopSet and PackageCode__c in :pkgCdSet ];
			map<String, Plan__c> existRoomTypeMap = new map<String, Plan__c>();
			for (Plan__c oPlan : existRoomTypes) {
				String okey = getPlanKey(oPlan);
				existRoomTypeMap.put(okey, oPlan);
			}
			for (String skey : tlMsgTypeRooms.keySet()){
				// システムに該当プランが非存在の場合、新規登録を行う
				if (!existRoomTypeMap.containsKey(skey)) {
					nwlst.add(tlMsgTypeRooms.get(skey));
				}
			}
			if (!nwlst.isEmpty()) insert nwLst;
		}
		
		return '取込正常に完了しました。';
	}  
	private static String getPlanKey(Plan__c plan) {
		return plan.PackageCode__c + '_' + CommUtils.nullToBlank(plan.ShopInfoRef__c);
	}
	// 取込の店舗コードリストを設定する
	private static List<String> getImportShopCodes(String branchShopCd) {
		// 指定の店舗コードはNULLの場合、店舗情報マスタから店舗コードを取得する、多店舗じゃない場合、単店舗情報を取得する
		List<String> shopCdsLst = new List<String>();
		if (CommUtils.isBLank(branchShopCd)) {
			map<String, ShopInformation__c> shopInfoMap = ShopInfoUtil.getShopInfoMap();
			for (ShopInformation__c shop : shopInfoMap.values()) {
				shopCdsLst.add(shop.ShopCode__c);
			}
		} else {
			shopCdsLst.add(branchShopCd);
		}
		// 単店舗の場合
		if (shopCdsLst.isEmpty()) shopCdsLst.add('');
		// 50以内の店舗情報制御が必要
		if (shopCdsLst.size() > 50) {
			throw new CommException('一括取込できる店舗数を超えました。');
		}
		return shopCdsLst;
	}
}