src/objects/AccountMaster__c.object
<CustomObject>
    <description>Master of account items</description>
    <fields>
        <fullName>ActionType__c</fullName>
        <description>普通の商品は　デフォルト値：通常で設定する、特別商品に対して、別々、商品種別に設定する
前受付金の場合、会計商品マスたに、価格はNull設定して、入力画面に自由入力する</description>
        <label>商品処理種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>通常</fullName>
                    <default>true</default>
                    <label>通常</label>
                </value>
                <value>
                    <fullName>前受付金</fullName>
                </value>
                <value>
                    <fullName>プラン</fullName>
                </value>
                <value>
                    <fullName>室料</fullName>
                </value>
                <value>
                    <fullName>朝食</fullName>
                </value>
                <value>
                    <fullName>夕食</fullName>
                </value>
                <value>
                    <fullName>非表示</fullName>
                </value>
                <value>
                    <fullName>支払</fullName>
                </value>
                <value>
                    <fullName>サービス料</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BasePlanFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <description>プラングループ設定機能利用する場合、基本プラン標識する【プラン設定】画面から連動設定する</description>
        <label>ベースプラン</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field3__c</fullName>
        <externalId>true</externalId>
        <label>商品コード</label>
        <length>13</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Field5__c</fullName>
        <label>単価</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ServiceRate__c</fullName>
        <description>サービス料金（％）</description>
        <label>サービス料(%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SpecialTax__c</fullName>
        <defaultValue>0</defaultValue>
        <label>特別税</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StsTaxfee__c</fullName>
        <inlineHelpText>0: 課税 99:非課税</inlineHelpText>
        <label>税ｽﾃｰﾀｽ</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>jmstRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>消費税マスタ</label>
        <referenceTo>JMST__c</referenceTo>
        <relationshipName>jmst</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会計商品</label>
    <nameField>
        <label>商品名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/JMST__c.object
<CustomObject>
    <description>Tax of sales</description>
    <fields>
        <fullName>TaxRate__c</fullName>
        <label>税率</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <label>消費税</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>消費税マスタ名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>Master Package code Plan</description>
    <fields>
        <fullName>AccountA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountA</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipLabel>プラン</relationshipLabel>
        <relationshipName>Planm8c9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AccountB__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountB</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipLabel>プラン (AccountB)</relationshipLabel>
        <relationshipName>Planm8cT</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BasePlanFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <description>プラングループ設定機能利用する場合、基本プラン標識する</description>
        <label>ベースプラン</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JmstRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>消費税</label>
        <referenceTo>JMST__c</referenceTo>
        <relationshipLabel>プラン</relationshipLabel>
        <relationshipName>PlanJmsRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PackageCode__c</fullName>
        <label>パッケージコード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PlanNo__c</fullName>
        <label>PlanNo</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceRate__c</fullName>
        <label>サービス料(%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>プラン</label>
    <nameField>
        <label>Plan</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PlanDetail__c.object
<CustomObject>
    <description>Package Plan detaied</description>
    <fields>
        <fullName>AccountMasterRef__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>商品</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipLabel>プラン明細</relationshipLabel>
        <relationshipName>AccountMasterRef</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JmstRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>消費税(参照)</label>
        <referenceTo>JMST__c</referenceTo>
        <relationshipLabel>プラン明細</relationshipLabel>
        <relationshipName>PlanDlJmsRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PlanRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>プラン</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>プラン明細</relationshipLabel>
        <relationshipName>PlanRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceRate__c</fullName>
        <label>サービス料(%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TaxRate__c</fullName>
        <label>消費税</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <label>プラン明細</label>
    <nameField>
        <label>プラン明細名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ShopInformation__c.object
<CustomObject>
    <description>Shoppers</description>
    <fields>
        <fullName>ShopCode__c</fullName>
        <externalId>true</externalId>
        <label>店舗コード</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>店舗情報</label>
    <nameField>
        <label>店舗名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TypeOfRooms__c.object
<CustomObject>
    <description>Master Guest Room Type</description>
    <fields>
        <fullName>ActionType__c</fullName>
        <label>部屋タイプ種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>通常</fullName>
                    <default>true</default>
                    <label>通常</label>
                </value>
                <value>
                    <fullName>E/B</fullName>
                </value>
                <value>
                    <fullName>架空</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>部屋タイプ</label>
    <nameField>
        <label>名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ShopCode__c</fullName>
        <description>従業員所属店舗の店舗コードを指定可能、複数店舗を兼務の場合、カンマで複数店舗コードを一括設定可能
例：複数店舗兼務：01,02,03　→店舗01,02,03兼務になる、デフォルト所属店舗：01
デフォルト所属店舗を指定したい場合、店舗コードの後ろに、「:1」を指定すると、デフォルト店舗を指定可能
例：複数店舗兼務、店舗02はデフォルト所属店舗の場合、下記様に定義可能
-&gt;01,02:1,03</description>
        <inlineHelpText>従業員所属店舗の店舗コードを指定可能、複数店舗を兼務の場合、カンマで複数店舗コードを一括設定可能
例：複数店舗兼務：01,02,03　→店舗01,02,03兼務になる、デフォルト所属店舗：01
デフォルト所属店舗を指定したい場合、店舗コードの後ろに、「:1」を指定すると、デフォルト店舗を指定可能
例：複数店舗兼務、店舗02はデフォルト所属店舗の場合、下記様に定義可能
-&gt;01,02:1,03</inlineHelpText>
        <label>店舗コード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PlanSearchCtrlTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class PlanSearchCtrlTest {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        ShopInformation__c shopInfo = TestCommon.createShopInfo();
        Plan__c item = TestCommon.createPlan();
    	PlanSearchCtrl ctrl = new PlanSearchCtrl();
    	ctrl.init();
    	ctrl.ShopCode = shopInfo.Id;
    	ctrl.c_planNm = item.Name;
    	ctrl.c_dpId = '1111';
    	ctrl.c_gpId = '2222';
    	ctrl.nextPage();
        ctrl.lastPage();
        ctrl.previousPage();
        ctrl.firstPage();
    	ctrl.queryInfo();
        
    }
    // 室料情報を取得する
    static testMethod void myUnitTest1() {
        // TO DO: implement unit test
        ShopInformation__c shop = TestCommon.createShopInfo();
		shop.ShopCode__c = '02';
		upsert shop;
        User cUser = [select shopCode__c from User Where id = :UserInfo.getUserId()];
		cUser.shopCode__c = '01,02:1,03';
		update cUser;
        
        JMST__c taxMst =  TestCommon.createTaxMst();
    	taxMst.TaxRate__c = 0;
    	update taxMst;
        AccountMaster__c shitulyoItem1 = new AccountMaster__c(
           Name = '食事1',
           ActionType__c = CommConst.PROD_ACTION_TYPE_RP,
           jmstRef__c = taxMst.Id,
           StsTaxfee__c = '0',
           Field3__c = '100999',
           Field5__c = 1050,
           ServiceRate__c = 10,
           SpecialTax__c = 100
        );
        AccountMaster__c shitItem2 = new AccountMaster__c(
           Name = '室料',
           ActionType__c = CommConst.PROD_ACTION_TYPE_RP,
           jmstRef__c = taxMst.Id,
           StsTaxfee__c = '0',
           Field3__c = '10099434',
           Field5__c = 0,
           ServiceRate__c = 10
        );
        List<AccountMaster__c> itemLst = new List<AccountMaster__c>();
        itemLst.add(shitulyoItem1);
        itemLst.add(shitItem2);
        insert itemLst;
        Plan__c planItem = TestCommon.createPlan();
    	planItem.packageCode__c = 'U0001';
    	planItem.PlanNo__c = '00000001';
    	planItem.AccountA__c = shitulyoItem1.Id;
    	planItem.AccountB__c = shitItem2.Id;
    	planItem.Name = 'テストプラン情報の設定をを行う111';
    	update planItem;
    	PlanDetail__c detail = new PlanDetail__c(
			TaxRate__c = 0,
        	PlanRef__c = planItem.Id,
        	AccountMasterRef__c = shitItem2.Id
        );
        insert detail;
    	Apexpages.currentPage().getParameters().put('par','1');
    	PlanSearchCtrl ctrl = new PlanSearchCtrl();    	
    	ctrl.init();
    	ctrl.ShopCode = shop.Id;
    	ctrl.c_planNm = 'テストプラン情報の設定をを行う111';
    	ctrl.c_dpId = '1111';
    	ctrl.c_gpId = '2222';
    	ctrl.queryInfo();
    	
        
    }
    // 2020/05/30 BY zyz BEGIN
    static testMethod void myUnitPlanTest() {
        // TO DO: implement unit test
        ShopInformation__c shopInfo = TestCommon.createShopInfo();
		List<TypeOfRooms__c> TypeOfRooms1 = TestCommon.createTypeOfRoomByShop(shopInfo.Id, 3);
        Plan__c plan = TestCommon.createPlan();
		plan.BasePlanFlg__c = true;
		update plan;
		TestCommon.createRaceRateDetail('A','B',5);
    	BasePlanSetupViewCtrl ctrl = new BasePlanSetupViewCtrl();
    	ctrl.c_planNm = 'テストプラン情報の設定をを行う111';
    	ctrl.c_dpId = '1111';
    	ctrl.c_gpId = '2222';
    	ctrl.queryInfo();
        
    }
    // 2020/05/30 BY zyz END
}