src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountType__c</fullName>
        <label>取引先種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>通常</fullName>
                    <default>true</default>
                    <label>通常</label>
                </value>
                <value>
                    <fullName>旅行会社</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Call_information__c.object
<CustomObject>
    <description>CTI incoming call history</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Information</relationshipLabel>
        <relationshipName>Call_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Call_Time__c</fullName>
        <label>Call Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Call Information</relationshipLabel>
        <relationshipName>Call_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LNO__c</fullName>
        <label>LNO</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SNO__c</fullName>
        <label>SNO</label>
        <type>Phone</type>
    </fields>
    <label>Call information</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Call information名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CommDefine__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CTI_Call_Columns_xml_Name__c</fullName>
        <label>CTI Call Columns xml Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>maxrecords_DB__c</fullName>
        <defaultValue>10</defaultValue>
        <label>maxrecords_DB</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>maxrecords_DSP__c</fullName>
        <defaultValue>5</defaultValue>
        <label>maxrecords_DSP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>共通定義</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Usage_Count__c</fullName>
        <label>Usage Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead__c.object
<CustomObject>
    <description>Booking sheet with record type</description>
    <fields>
        <fullName>EntryTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <inlineHelpText>お客様が来られる予定の日付を選択してください。</inlineHelpText>
        <label>到着日</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Field4__c</fullName>
        <inlineHelpText>お着きの時間を選択してください。</inlineHelpText>
        <label>到着時刻</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>11:00</fullName>
                </value>
                <value>
                    <fullName>11:10</fullName>
                </value>
                <value>
                    <fullName>11:20</fullName>
                </value>
                <value>
                    <fullName>11:30</fullName>
                </value>
                <value>
                    <fullName>11:40</fullName>
                </value>
                <value>
                    <fullName>11:50</fullName>
                </value>
                <value>
                    <fullName>12:00</fullName>
                </value>
                <value>
                    <fullName>12:10</fullName>
                </value>
                <value>
                    <fullName>12:20</fullName>
                </value>
                <value>
                    <fullName>12:30</fullName>
                </value>
                <value>
                    <fullName>12:40</fullName>
                </value>
                <value>
                    <fullName>12:50</fullName>
                </value>
                <value>
                    <fullName>13:00</fullName>
                </value>
                <value>
                    <fullName>13:10</fullName>
                </value>
                <value>
                    <fullName>13:20</fullName>
                </value>
                <value>
                    <fullName>13:30</fullName>
                </value>
                <value>
                    <fullName>13:40</fullName>
                </value>
                <value>
                    <fullName>13:50</fullName>
                </value>
                <value>
                    <fullName>14:00</fullName>
                </value>
                <value>
                    <fullName>14:10</fullName>
                </value>
                <value>
                    <fullName>14:20</fullName>
                </value>
                <value>
                    <fullName>14:30</fullName>
                </value>
                <value>
                    <fullName>14:40</fullName>
                </value>
                <value>
                    <fullName>14:50</fullName>
                </value>
                <value>
                    <fullName>15:00</fullName>
                    <default>true</default>
                    <label>15:00</label>
                </value>
                <value>
                    <fullName>15:10</fullName>
                </value>
                <value>
                    <fullName>15:20</fullName>
                </value>
                <value>
                    <fullName>15:30</fullName>
                </value>
                <value>
                    <fullName>15:40</fullName>
                </value>
                <value>
                    <fullName>15:50</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relcontact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>お客様</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ご予約</relationshipLabel>
        <relationshipName>reservetg85</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReservedStatus__c</fullName>
        <inlineHelpText>NO SHOW、キャンセルまたは、削除への変更について、パラメータにより一括キャンセルする／しないを選択可能(連泊のときのみ有効)となります。</inlineHelpText>
        <label>予約ステータス</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>確認中</fullName>
                </value>
                <value>
                    <fullName>確定</fullName>
                    <default>true</default>
                    <label>確定</label>
                </value>
                <value>
                    <fullName>会場おさえ</fullName>
                </value>
                <value>
                    <fullName>仮予約</fullName>
                </value>
                <value>
                    <fullName>キャンセルまち</fullName>
                </value>
                <value>
                    <fullName>NO SHOW</fullName>
                </value>
                <value>
                    <fullName>キャンセル</fullName>
                </value>
                <value>
                    <fullName>削除</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ご予約</label>
    <nameField>
        <label>予約名</label>
        <type>Text</type>
    </nameField>
    <recordTypes>
        <fullName>BookingRecType</fullName>
        <active>true</active>
        <description>施設[ホテル]</description>
        <label>宿泊</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LeadIndex__c.object
<CustomObject>
    <description>Index record of Booking record day by day</description>
    <fields>
        <fullName>EntryDate__c</fullName>
        <label>到着日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EntryTime__c</fullName>
        <defaultValue>&apos;15:00&apos;</defaultValue>
        <description>HH:MM</description>
        <label>到着時刻</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusLst__c</fullName>
        <label>状態</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>通常</fullName>
                    <default>true</default>
                    <label>通常</label>
                </value>
                <value>
                    <fullName>キャンセル</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>contactRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>お客様</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>予約インデックス</relationshipLabel>
        <relationshipName>IndexContactRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>予約インデックス</label>
    <nameField>
        <displayFormat>I_{YYYY}_{0000000000}</displayFormat>
        <label>予約名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>IsAlarmPopup__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to check if alarm popup is already opened in current user&apos;s browser</description>
        <label>IsAlarmPopup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isCallInformationEnabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isCallInformationEnabled</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CallInformationTest.cls
/*
 * @Author: persistent systems ltd.
 * @Date: 4th December 2013 
 * @Description: This is a test class for CallInformationSync Controller
 */
@isTest(seeAllData=false)
private class CallInformationTest{

    static Contact con;
    static Account acc;
    
    /**
    * Create test data
    */
    static void createSetupData(){
        CommDefine__c def = new CommDefine__c(maxRecords_DB__c = 1, maxRecords_DSP__c = 1);
        insert def;
        con = new Contact(LastName = 'Test Contact', Phone = '1234567890');
        insert con;
        acc = new Account(Name= 'Test Account', Phone = '1234567890');
        insert acc;
        Test.setFixedSearchResults(new Id[]{con.Id,acc.Id});
        List<Document> docList = [select id from document where name = 'CTI Call Columns xml'];
        delete docList;
        
        Document doc = new Document(Name = 'CTI Call Columns xml');
        doc.FolderId = userinfo.getUserId();
        doc.Body = Blob.valueof('<fields>'+
	        						 '<field show="true">'+
	        						 	'<labelAPIName>Contact.Usage_Count__c:ご利用回数</labelAPIName>'+
	        						 '</field> 	'+
	        						 '<field show="true">  '+      	
	        						 	'<labelAPIName>Contact.Account.AccountType__c:取引先種別</labelAPIName>'+ 	
	        						 '</field>'+ 	 	
	        						 '<field show="true">'+ 		
	        						 	'<DefaultLayout>Lead__c-BookingRecType</DefaultLayout>'+ 		
	        						 	'<labelAPIName>Lead__c.Name:ご予約</labelAPIName>'+ 		
	        						 	'<latestCheckInDate>Contact-reservetg85__r.EntryTime__c</latestCheckInDate>'+ 		
	        						 	'<latestCheckInTime>Contact-reservetg85__r.Field4__c</latestCheckInTime>'+   	 	
	        						 '</field>'+ 	
	        						 '<field show="true">'+        	
	        						 	'<PageLayout>BookingApp</PageLayout>'+ 		
	        						 	'<labelAPIName>LeadIndex__c.Name:一括予約</labelAPIName>'+ 		
	        						 	'<latestCheckInDate>Contact-IndexContactRef__r.EntryDate__c</latestCheckInDate>'+ 		
	        						 	'<latestCheckInTime>Contact-IndexContactRef__r.EntryTime__c</latestCheckInTime>'+ 	
	        						 '</field>'+ 
        						 '</fields>');
        insert doc;
    }
    
    
     static void createSetupDataByScreenType(){
        CommDefine__c def = new CommDefine__c(maxRecords_DB__c = 1, maxRecords_DSP__c = 1, CTI_Call_Columns_xml_Name__c = 'CTI Call Columns xml V1.1');
        insert def;
        con = new Contact(LastName = 'Test Contact', Phone = '1234567890');
        insert con;
        acc = new Account(Name= 'Test Account', Phone = '1234567890');
        insert acc;
        Test.setFixedSearchResults(new Id[]{con.Id,acc.Id});
        List<Document> docList = [select id from document where name = 'CTI Call Columns xml'];
        delete docList;
        
        Document doc = new Document(Name = 'CTI Call Columns xml V1.1');
        doc.FolderId = userinfo.getUserId();
        doc.Body = Blob.valueof('<screens>'+
									'<screen name="callinfostickywindow">'+
										'<active>true</active>'+
										'<description>'+
										'</description>'+
										'<width>750</width>'+ 
										'<fields>'+	
											'<field show="false">'+
												'<labelAPIName>Contact.Usage_Count__c:ご利用回数</labelAPIName>'+
											'</field>'+
											'<field show="true">'+
												'<DefaultLayout>ps__Lead__c-BookingRecType</DefaultLayout>'+
												'<labelAPIName>Lead__c.Name:ご予約</labelAPIName>'+
												'<latestCheckInDate>Contact-reservetg85__r.EntryTime__c</latestCheckInDate>'+
												'<latestCheckInTime>Contact-reservetg85__r.Field4__c</latestCheckInTime>'+
												'<filters>ReservedStatus__c not in (\'NO SHOW\',\'キャンセル\',\'削除\')</filters>'+
											'</field>'+
											'<field show="true">'+
												'<PageLayout>BookingApp</PageLayout>'+
												'<labelAPIName>LeadIndex__c.Name:一括予約</labelAPIName>'+
												'<latestCheckInDate>Contact-IndexContactRef__r.EntryDate__c</latestCheckInDate>'+
												'<latestCheckInTime>Contact-IndexContactRef__r.EntryTime__c</latestCheckInTime>'+
												'<filters>StatusLst__c in (\'通常\')</filters>'+
												  
											'</field>'+
										'</fields>'+
									'</screen>'+
									'<screen name="alarmpopupwindow">'+
										'<active>true</active>'+
										'<description>'+
											
										'</description>'+
										'<fields>'+	
											'<field show="false">'+
												'<labelAPIName>Contact.Usage_Count__c:ご利用回数</labelAPIName>'+
											'</field>'+
											'<field show="true">'+
												'<DefaultLayout>ps__Lead__c-BookingRecType</DefaultLayout>'+
												'<labelAPIName>Lead__c.Name:ご予約</labelAPIName>'+
												'<latestCheckInDate>Contact-reservetg85__r.EntryTime__c</latestCheckInDate>'+
												'<latestCheckInTime>Contact-reservetg85__r.Field4__c</latestCheckInTime>'+
												'<filters>ReservedStatus__c not in (\'NO SHOW\',\'キャンセル\',\'削除\')</filters>'+
											'</field>'+
											'<field show="true">'+
												'<PageLayout>BookingApp</PageLayout>'+
												'<labelAPIName>LeadIndex__c.Name:一括予約</labelAPIName>'+
												'<latestCheckInDate>Contact-IndexContactRef__r.EntryDate__c</latestCheckInDate>'+
												'<latestCheckInTime>Contact-IndexContactRef__r.EntryTime__c</latestCheckInTime>'+
												'<filters>StatusLst__c in (\'通常\')</filters>'+
											'</field>'+
										'</fields>'+
									 '</screen>'+
								'</screens>');
        insert doc;
    }
    
    /**
    * This method test CallInformationSync's web service createCallInformation for type 1 call information
    */
    private static testmethod void testCreateCallInformationType1(){
        createSetupData();
        CallInformationSync.CallInformation cInfo = new CallInformationSync.CallInformation();
        cInfo.SNO = '1234567890';
        cInfo.cdt = '20131212';
        cInfo.ctm = '121212';
        cInfo.dcd1 = false;
        Test.startTest();
        CallInformationSync.CallInformationSyncResult result = CallInformationSync.createCallInformation(cInfo);
        Test.stopTest();
        System.assertNotEquals(0,[select id from Call_Information__c].size());
        System.assertEquals(con.Id,[select Contact__c from Call_Information__c][0].contact__c);
        System.assertEquals(true,result.isSuccess);
    }
    
    /**
    * This method test CallInformationSync's web service createCallInformation for type 2 call information
    */
    private static testmethod void testCreateCallInformationType2(){
        createSetupData();
        CallInformationSync.CallInformation cInfo = new CallInformationSync.CallInformation();
        cInfo.SNO = '1234567890';
        cInfo.dcd1 = true;
        cInfo.cdt = '20131212';
        cInfo.ctm = '121212';
        Test.startTest();
        CallInformationSync.CallInformationSyncResult result = CallInformationSync.createCallInformation(cInfo);
        Test.stopTest();
        System.assertNotEquals(0,[select id from Call_Information__c].size());
        System.assertEquals(acc.Id,[select Account__c from Call_Information__c][0].Account__c);
        System.assertEquals(true,result.isSuccess);
    }
    
    /**
    * This method test CallInformationSync's web service createCallInformation when maxRecords_DB is reached
    */
    private static testmethod void testCreateCallInformationMaxDBReached(){
        createSetupData();
        Call_information__c information = new Call_information__c(LNO__c = '01',SNO__c = '1234567899',Call_Time__c = System.now());
        insert information;
        CallInformationSync.CallInformation cInfo = new CallInformationSync.CallInformation();
        cInfo.SNO = '1234567890';
        cInfo.dcd1 = true;
        cInfo.cdt = '20131212';
        cInfo.ctm = '121212';
        Test.startTest();
        CallInformationSync.CallInformationSyncResult result = CallInformationSync.createCallInformation(cInfo);
        Test.stopTest();
        System.assertNotEquals(0,[select id from Call_Information__c].size());
        System.assertEquals(acc.Id,[select Account__c from Call_Information__c where id =: result.sfdcId][0].Account__c);
        System.assertEquals(true,result.isSuccess);
    }
    
    /**
    * This method test CallManagementController's Constructor
    */
    private static testmethod void testCallManagementController(){
        createSetupData();
        Call_information__c information = new Call_information__c(LNO__c = '01',SNO__c = '1234567899',Call_Time__c = System.now(),Contact__c = con.Id);
        insert information;
        Test.startTest();
        CallManagementController controller = new CallManagementController();
        Test.stopTest();
        System.assertNotEquals(0,controller.lstCallInfo.size());
    }
    
    /**
    * This method test CallManagementController's Constructor
    */
    private static testmethod void testCallManagementControllerByScreenName(){
        createSetupDataByScreenType();
        Call_information__c information = new Call_information__c(LNO__c = '01',SNO__c = '1234567899',Call_Time__c = System.now(),Contact__c = con.Id);
        insert information;
        Test.startTest();
        CallManagementController controller = new CallManagementController();
        Test.stopTest();
        System.assertNotEquals(0,controller.lstCallInfo.size());
    }
    
    /**
    * This method test CallManagementController's checkAlarmOpened method
    */
    private static testmethod void testCheckAlarmOpened(){
    	User curUser = [select id, isCallInformationEnabled__c from User where Id = :UserInfo.getUserId()];
    	curUser.isCallInformationEnabled__c = true;
    	update curUser;
    	System.runAs(curUser) {
        CallManagementController controller = new CallManagementController();
        Test.startTest();
        controller.checkAlarmOpened();
        Test.stopTest();
       	System.assertEquals(true,[select isCallInformationEnabled__c from User where id =: userinfo.getUserId()][0].isCallInformationEnabled__c);
    	}
    }

	 /**
    * This method test CallManagementController's checkAlarmOpened method
    */
    private static testmethod void testResetIsAlarmOpened(){
        CallManagementController controller = new CallManagementController();
        Test.startTest();
        controller.resetIsAlarmPopup();
        Test.stopTest();
        System.assertEquals(false,[select IsAlarmPopup__c from User where id =: userinfo.getUserId()][0].IsAlarmPopup__c);
      
    
    }
    
    private static testmethod void testCustomerCallInfoSyncHandler(){
    	Call_Information__c info = new Call_Information__c(sno__c = '1111111111');
    	insert info;
    	
    	Contact newContact = new Contact();
    	newContact.phone = '1111111111';
    	newContact.lastName = 'Test';
    	Test.startTest();
    	insert newContact;
    	Test.stopTest();
    	
    	System.assertEquals(newContact.id, [select contact__c from call_Information__c where id =: info.id][0].Contact__c);
    }
    
    static testMethod void TestContainsFun() {
    	String src = '中板 自家用 湘南580ひ33 中板 自家用 湘南580ひ3 中板 自家用 湘南580ひ3606';
    	String key = '湘南580ひ3';
    	System.assert(CallInformationSync.isContains(src, key));
    	key = '湘南580ひA';
    	System.assert(!CallInformationSync.isContains(src, key));
    	key = '湘南580ひ';
    	System.assert(!CallInformationSync.isContains(src, key));
    	key = '湘南580ひ333';
    	System.assert(!CallInformationSync.isContains(src, key));
    	key = '湘南580ひ3606';
    	System.assert(CallInformationSync.isContains(src, key));
    	key = '湘南580ひ33';
    	System.assert(CallInformationSync.isContains(src, key));
    	src = '中板 自家用 湘南580ひ33\n'
    		+ '中板 自家用 湘南580ひ3\n'
    		+ '中板 自家用 湘南580ひ3606';
    	key = '湘南580ひ3';
    	System.assert(CallInformationSync.isContains(src, key));
    	key = '湘南580ひA';
    	System.assert(!CallInformationSync.isContains(src, key));
    	key = '湘南580ひ';
    	System.assert(!CallInformationSync.isContains(src, key));
    	key = '湘南580ひ333';
    	System.assert(!CallInformationSync.isContains(src, key));
    	key = '湘南580ひ3606';
    	System.assert(CallInformationSync.isContains(src, key));
    	key = '湘南580ひ33';
    	System.assert(CallInformationSync.isContains(src, key));
    }
}