src/objects/AccountAcount__c.object
<CustomObject>
    <description>*** Account Header</description>
    <fields>
        <fullName>ShopCode__c</fullName>
        <label>店舗コード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitPriceDefKb__c</fullName>
        <defaultValue>TEXT($Setup.CommDefine__c.UnitPriceDefKb__c)</defaultValue>
        <description>会計新規作成場合、共通定義の「会計商品単価定義区分」設定値から項目にコピーする</description>
        <label>会計商品単価定義区分</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>会計</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>Account#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AccountMaster__c.object
<CustomObject>
    <description>Master of account items</description>
    <fields>
        <fullName>ActionType__c</fullName>
        <description>普通の商品は　デフォルト値：通常で設定する、特別商品に対して、別々、商品種別に設定する
前受付金の場合、会計商品マスたに、価格はNull設定して、入力画面に自由入力する</description>
        <label>商品処理種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>通常</fullName>
                    <default>true</default>
                    <label>通常</label>
                </value>
                <value>
                    <fullName>前受付金</fullName>
                </value>
                <value>
                    <fullName>プラン</fullName>
                </value>
                <value>
                    <fullName>室料</fullName>
                </value>
                <value>
                    <fullName>朝食</fullName>
                </value>
                <value>
                    <fullName>夕食</fullName>
                </value>
                <value>
                    <fullName>非表示</fullName>
                </value>
                <value>
                    <fullName>支払</fullName>
                </value>
                <value>
                    <fullName>サービス料</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PaymentType__c</fullName>
        <label>支払種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>現金</fullName>
                </value>
                <value>
                    <fullName>カード</fullName>
                </value>
                <value>
                    <fullName>売掛金</fullName>
                </value>
                <value>
                    <fullName>クーポン</fullName>
                </value>
                <value>
                    <fullName>割引</fullName>
                </value>
                <value>
                    <fullName>値引</fullName>
                </value>
                <value>
                    <fullName>予約金</fullName>
                </value>
                <value>
                    <fullName>現金返金</fullName>
                </value>
                <value>
                    <fullName>カード返金</fullName>
                </value>
                <value>
                    <fullName>割増</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ShopInfoRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>店舗情報</label>
        <referenceTo>ShopInformation__c</referenceTo>
        <relationshipLabel>会計商品</relationshipLabel>
        <relationshipName>AccountShopInfoRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SpecialTax__c</fullName>
        <defaultValue>0</defaultValue>
        <label>特別税</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>会計商品</label>
    <nameField>
        <label>商品名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BookingEstimateItem__c.object
<CustomObject>
    <description>Details Estimate for Booking</description>
    <fields>
        <fullName>ActionType__c</fullName>
        <description>普通の商品は　デフォルト値：通常で設定する、特別商品に対して、別々、商品種別に設定する
前受付金の場合、会計商品マスたに、価格はNull設定して、入力画面に自由入力する</description>
        <label>商品処理種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>通常</fullName>
                    <default>true</default>
                    <label>通常</label>
                </value>
                <value>
                    <fullName>前受付金</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>商品の数量を入力してください</inlineHelpText>
        <label>数量</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ParentBookingItemRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>親予約見積明細</label>
        <referenceTo>BookingEstimateItem__c</referenceTo>
        <relationshipLabel>予約見積明細</relationshipLabel>
        <relationshipName>ParentBookingItemRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentType__c</fullName>
        <label>支払種別</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SpecialTax__c</fullName>
        <defaultValue>0</defaultValue>
        <label>特別税</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UnitPriceDefKb__c</fullName>
        <defaultValue>TEXT($Setup.CommDefine__c.UnitPriceDefKb__c)</defaultValue>
        <label>会計商品単価定義区分</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <inlineHelpText>空欄のまま保存すると、会計商品で定義した単価が設定されます</inlineHelpText>
        <label>単価</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>refAccountMaster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>商品を選択して下さい</inlineHelpText>
        <label>商品名</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipLabel>予約見積明細</relationshipLabel>
        <relationshipName>BookingEstimateItemhSGP</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>予約見積明細</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>予約見積明細#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CommDefine__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>AccountServiceChargeNoTaxFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>「サービス料別表示制御」は「2」で定義されている場合、該当フラグ定義により、サビース料税込み・税抜き切替できる
TRUE：サービス料は税抜き金額を出力する
FALSE:サービス料は税込みき金額を出力する(デフォルト値)</inlineHelpText>
        <label>サービス料税抜表示フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BillReportCommentAutoBreakFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>請求書、見積書、予約確認書コメント文字列の自動改行制御フラグ
TRUE:画面入力の改行を無視して、入力行の文字数により、自動改行を行う
FALSE:画面入力の改行により、その文字はそのまま請求書、見積書、予約確認書に表示する（デフォルト値）</inlineHelpText>
        <label>請求書、見積書、予約確認書コメント自動改行制御</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BookingReportStampIsShowFlg__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>見積書にハンコ表示・非表示
TRUE:ハンコ表示(Default値）
FALSE:ハンコ非表示</inlineHelpText>
        <label>見積書ハンコ表示・非表示</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UnitPriceDefKb__c</fullName>
        <inlineHelpText>1:税込、サービス料抜き
2:税込、サービス料込
3:税抜、サービス料抜き
4:税抜、サビース料込</inlineHelpText>
        <label>会計商品単価定義区分</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>共通定義</label>
</CustomObject>

src/objects/ExchangeRate__c.object
<CustomObject>
    <fields>
        <fullName>RateDate__c</fullName>
        <label>レート日</label>
        <type>Date</type>
    </fields>
    <label>為替レート</label>
    <nameField>
        <label>為替レート名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead__c.object
<CustomObject>
    <description>Booking sheet with record type</description>
    <fields>
        <fullName>EntryTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <inlineHelpText>お客様が来られる予定の日付を選択してください。</inlineHelpText>
        <label>到着日</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UnitPriceDefKb__c</fullName>
        <defaultValue>TEXT($Setup.CommDefine__c.UnitPriceDefKb__c)</defaultValue>
        <label>会計商品単価定義区分</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>ご予約</label>
    <nameField>
        <label>予約名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ReportLogo__c.object
<CustomObject>
    <description>Logo image file for Statement sheet, Estimate sheet and Invoice sheet</description>
    <fields>
        <fullName>ReportLogo__c</fullName>
        <label>レポートロゴ</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ShopInfoRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>店舗情報</label>
        <referenceTo>ShopInformation__c</referenceTo>
        <relationshipName>ShopInfoRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>レポートロゴ</label>
    <nameField>
        <label>請求書ロゴ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ShopInformation__c.object
<CustomObject>
    <description>Shoppers</description>
    <fields>
        <fullName>AccountServiceChargeNoTaxFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>「サービス料別表示制御」は「2」で定義されている場合、該当フラグ定義により、サービス料税込み・税抜き切替できる
TRUE：サービス料は税抜き金額を出力する
FALSE:サービス料は税込みき金額を出力する(デフォルト値)</inlineHelpText>
        <label>サービス料税抜表示フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payee1__c</fullName>
        <label>振込先１</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payee2__c</fullName>
        <label>振込先２</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payee3__c</fullName>
        <label>振込先３</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PayeeAcount__c</fullName>
        <label>振込先口座</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceChargeIsShow__c</fullName>
        <defaultValue>&quot;0&quot;</defaultValue>
        <inlineHelpText>会計書(施設コード33/34) 、請求書、見積書にサービス料合計金額は利用明細に表示する・しない制御 
0/空欄：サービス料合計金額は明細行に追加表示しない（デフォルト値） 
1：サービス料合計金額は明細行に追加表示 
2：サービス料合計金額は内税消費税行の下に表示</inlineHelpText>
        <label>サービス料別表示制御</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShopCode__c</fullName>
        <externalId>true</externalId>
        <label>店舗コード</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>店舗情報</label>
    <nameField>
        <label>店舗名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ShopCode__c</fullName>
        <description>従業員所属店舗の店舗コードを指定可能、複数店舗を兼務の場合、カンマで複数店舗コードを一括設定可能
例：複数店舗兼務：01,02,03　→店舗01,02,03兼務になる、デフォルト所属店舗：01
デフォルト所属店舗を指定したい場合、店舗コードの後ろに、「:1」を指定すると、デフォルト店舗を指定可能
例：複数店舗兼務、店舗02はデフォルト所属店舗の場合、下記様に定義可能
-&gt;01,02:1,03</description>
        <inlineHelpText>従業員所属店舗の店舗コードを指定可能、複数店舗を兼務の場合、カンマで複数店舗コードを一括設定可能
例：複数店舗兼務：01,02,03　→店舗01,02,03兼務になる、デフォルト所属店舗：01
デフォルト所属店舗を指定したい場合、店舗コードの後ろに、「:1」を指定すると、デフォルト店舗を指定可能
例：複数店舗兼務、店舗02はデフォルト所属店舗の場合、下記様に定義可能
-&gt;01,02:1,03</inlineHelpText>
        <label>店舗コード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LeadBillPDFCtrlTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class LeadBillPDFCtrlTest {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        getCsvSetupConfig();
        // 2018/12/15 請求書レイアウト改善 BY zyz BEGIN 
        getBillPdfConfig();
        // 2018/12/15 請求書レイアウト改善 BY zyz END 
    	Test.startTest();
    	// 店舗情報を初期化する
    	CommDefine__c comDef = TestCommon.createCommDefine();
    	// 施設コード    
    	comDef.BillReportCommentAutoBreakFlg__c = true;
		comDef.BookingReportStampIsShowFlg__c = false;
    	//comDef.UnitPriceDefKb__c = 1; 	//会計商品単価定義区分
    	update comDef;
    	ShopInformation__c shopInfo = TestCommon.createShopInfo();
    	shopInfo.payee1__c = '23';
    	shopInfo.payee2__c = '23';
    	shopInfo.payee3__c = '23';
    	shopInfo.payeeAcount__c = '23';
		shopInfo.ServiceChargeIsShow__c = '2';
		shopInfo.AccountServiceChargeNoTaxFlg__c = true;
    	update shopInfo;
    	ReportLogo__c tempShopLogo = TestCommon.createRepLogo();
        tempShopLogo.ShopInfoRef__c = shopInfo.Id;
        update tempShopLogo;
    	User currUser = [select id, ShopCode__c from user where id = :UserInfo.getUserId()];
    	currUser.ShopCode__c = shopInfo.ShopCode__c;
    	update currUser;
    	ExchangeRate__c rate = TestCommon.createExchangeRate();
    	// 予約情報を作成する
    	Lead__c leadInfo = TestCommon.createLead();
    	rate.Name = UserInfo.getDefaultCurrency() + 'JPY_' + CommUtils.getRandom(3);
    	rate.RateDate__c = leadInfo.EntryTime__c.Date();
    	update rate;
    	// 商品情報を作成する
    	List<AccountMaster__c> productLst = TestCommon.createProductMst(4);
    	productLst[0].ActionType__c = CommConst.PROD_ACTION_TYPE_PY;
    	productLst[0].SpecialTax__c = 2000;
    	productLst[0].PaymentType__c = '予約金';
    	productLst[1].ActionType__c = CommConst.PROD_ACTION_TYPE_AR;
    	productLst[1].SpecialTax__c = 2000;
    	productLst[1].PaymentType__c = '予約金';
		update productLst;
    	// 見積明細を作成する
    	BookingEstimateItem__c bookingItem = TestCommon.createBookEstItem(leadInfo, productLst[0]);
    	// 予約情報のステータス：チェックインに変更する
    	bookingItem.UnitPrice__c = 20000;
    	bookingItem.SpecialTax__c = 7900;
    	bookingItem.ActionType__c = CommConst.PROD_ACTION_TYPE_PY;
    	bookingItem.PaymentType__c = '予約金';
    	bookingItem.refAccountMaster__c = productLst[0].Id;
    	bookingItem.Amount__c = 4;
    	bookingItem.ParentBookingItemRef__c = null;
    	update bookingItem;
    	BookingEstimateItem__c bookingItem1 = TestCommon.createBookEstItem(leadInfo, productLst[1]);
    	// 予約情報のステータス：チェックインに変更する
    	bookingItem1.UnitPrice__c = 1000;
    	bookingItem1.SpecialTax__c = 1000;
    	bookingItem1.ActionType__c = '前受付金';
    	bookingItem1.PaymentType__c = '予約金';
    	bookingItem1.refAccountMaster__c = productLst[1].Id;
    	bookingItem1.Amount__c = 4;
    	bookingItem1.ParentBookingItemRef__c = null;
    	update bookingItem;
    	Test.stopTest();
        ApexPages.StandardController contr3 = new ApexPages.StandardController(leadInfo);
        Apexpages.currentPage().getParameters().put('cy','cy');
        LeadBillPDFCtrl lbPdf = new LeadBillPDFCtrl(contr3);
        
        lbPdf.getNumberFormat();
        lbPdf.extInitAction();
        lbPdf.getReportLogo();
        lbPdf.getAccoutInfo();
        lbPdf.getAccountNo();
        lbPdf.getCustomer();
        lbPdf.getCharge();
        lbPdf.getRequestAmount();
        lbPdf.getTax();
        lbPdf.getIssueDate();
        lbPdf.getAdvancesReceived();
        lbPdf.getTran();
        lbPdf.getAmoutIncDiscont();
        lbPdf.getServiceDate();
        AccountAcount__c comment = lbPdf.comment;
        lbPdf.getServiceAmount();
    }
    static testMethod void myUnitTest01() {
        // TO DO: implement unit test
        getCsvSetupConfig();
        // 2018/12/15 請求書レイアウト改善 BY zyz BEGIN 
        getBillPdfConfig();
        // 2018/12/15 請求書レイアウト改善 BY zyz END 
    	Test.startTest();
    	// 店舗情報を初期化する
    	CommDefine__c comDef = TestCommon.createCommDefine();
    	// 施設コード    
    	comDef.BillReportCommentAutoBreakFlg__c = true;
		comDef.BookingReportStampIsShowFlg__c = false;
    	//comDef.UnitPriceDefKb__c = 1; 	//会計商品単価定義区分
    	update comDef;
    	ShopInformation__c shopInfo = TestCommon.createShopInfo();
    	shopInfo.payee1__c = '23';
    	shopInfo.payee2__c = '23';
    	shopInfo.payee3__c = '23';
    	shopInfo.payeeAcount__c = '23';
		shopInfo.ServiceChargeIsShow__c = '2';
		shopInfo.AccountServiceChargeNoTaxFlg__c = true;
    	update shopInfo;
    	ReportLogo__c tempShopLogo = TestCommon.createRepLogo();
        tempShopLogo.ShopInfoRef__c = shopInfo.Id;
        update tempShopLogo;
    	User currUser = [select id, ShopCode__c from user where id = :UserInfo.getUserId()];
    	currUser.ShopCode__c = shopInfo.ShopCode__c;
    	update currUser;
    	ExchangeRate__c rate = TestCommon.createExchangeRate();
    	// 予約情報を作成する
    	Lead__c leadInfo = TestCommon.createLead();
    	rate.Name = UserInfo.getDefaultCurrency() + 'JPY_' + CommUtils.getRandom(3);
    	rate.RateDate__c = leadInfo.EntryTime__c.Date();
    	update rate;
    	// 商品情報を作成する
    	List<AccountMaster__c> productLst = TestCommon.createProductMst(4);
    	productLst[0].ActionType__c = CommConst.PROD_ACTION_TYPE_PY;
    	productLst[0].PaymentType__c = '予約金';
    	productLst[1].ActionType__c = CommConst.PROD_ACTION_TYPE_AR;
    	productLst[1].PaymentType__c = '予約金';
		update productLst;
    	// 見積明細を作成する
    	BookingEstimateItem__c bookingItem = TestCommon.createBookEstItem(leadInfo, productLst[0]);
    	// 予約情報のステータス：チェックインに変更する
    	bookingItem.UnitPrice__c = 0;
    	bookingItem.ActionType__c = CommConst.PROD_ACTION_TYPE_PY;
    	bookingItem.PaymentType__c = '予約金';
    	bookingItem.refAccountMaster__c = productLst[0].Id;
    	bookingItem.Amount__c = 4;
    	bookingItem.ParentBookingItemRef__c = null;
    	update bookingItem;
    	BookingEstimateItem__c bookingItem1 = TestCommon.createBookEstItem(leadInfo, productLst[1]);
    	// 予約情報のステータス：チェックインに変更する
    	bookingItem1.UnitPrice__c = 0;
    	bookingItem1.ActionType__c = '前受付金';
    	bookingItem1.PaymentType__c = '予約金';
    	bookingItem1.refAccountMaster__c = productLst[1].Id;
    	bookingItem1.Amount__c = 4;
    	bookingItem1.ParentBookingItemRef__c = null;
    	update bookingItem;
    	Test.stopTest();
        ApexPages.StandardController contr3 = new ApexPages.StandardController(leadInfo);
        Apexpages.currentPage().getParameters().put('cy','cy');
        LeadBillPDFCtrl lbPdf = new LeadBillPDFCtrl(contr3);
        
        lbPdf.getNumberFormat();
        lbPdf.extInitAction();
        lbPdf.getReportLogo();
        lbPdf.getAccoutInfo();
        lbPdf.getAccountNo();
        lbPdf.getCustomer();
        lbPdf.getCharge();
        lbPdf.getRequestAmount();
        lbPdf.getTax();
        lbPdf.getIssueDate();
        lbPdf.getAdvancesReceived();
        lbPdf.getTran();
        lbPdf.getAmoutIncDiscont();
        lbPdf.getServiceDate();
        AccountAcount__c comment = lbPdf.comment;
        lbPdf.getServiceAmount();
    }
    static testMethod void myUnitTest02() {
        // TO DO: implement unit test
        getCsvSetupConfig();
        // 2018/12/15 請求書レイアウト改善 BY zyz BEGIN 
        getBillPdfConfig();
        // 2018/12/15 請求書レイアウト改善 BY zyz END 
    	Test.startTest();
    	// 店舗情報を初期化する
    	CommDefine__c comDef = TestCommon.createCommDefine();
    	// 施設コード    
    	comDef.BillReportCommentAutoBreakFlg__c = true;
		comDef.BookingReportStampIsShowFlg__c = false;
    	//comDef.UnitPriceDefKb__c = 1; 	//会計商品単価定義区分
    	update comDef;
    	ShopInformation__c shopInfo = TestCommon.createShopInfo();
    	shopInfo.payee1__c = '23';
    	shopInfo.payee2__c = '23';
    	shopInfo.payee3__c = '23';
    	shopInfo.payeeAcount__c = '23';
		shopInfo.ServiceChargeIsShow__c = '2';
		shopInfo.AccountServiceChargeNoTaxFlg__c = true;
    	update shopInfo;
    	ReportLogo__c tempShopLogo = TestCommon.createRepLogo();
        tempShopLogo.ShopInfoRef__c = shopInfo.Id;
        update tempShopLogo;
    	User currUser = [select id, ShopCode__c from user where id = :UserInfo.getUserId()];
    	currUser.ShopCode__c = shopInfo.ShopCode__c;
    	update currUser;
    	// 予約情報を作成する
    	Lead__c leadInfo = TestCommon.createLead();
    	// 商品情報を作成する
    	List<AccountMaster__c> productLst = TestCommon.createProductMst(4);
    	productLst[0].ActionType__c = CommConst.PROD_ACTION_TYPE_PY;
    	productLst[0].PaymentType__c = '予約金';
    	productLst[1].ActionType__c = CommConst.PROD_ACTION_TYPE_AR;
    	productLst[1].PaymentType__c = '予約金';
		update productLst;
    	// 見積明細を作成する
    	BookingEstimateItem__c bookingItem = TestCommon.createBookEstItem(leadInfo, productLst[0]);
    	// 予約情報のステータス：チェックインに変更する
    	bookingItem.UnitPrice__c = 20000;
    	bookingItem.ActionType__c = CommConst.PROD_ACTION_TYPE_PY;
    	bookingItem.PaymentType__c = '予約金';
    	bookingItem.refAccountMaster__c = productLst[0].Id;
    	bookingItem.Amount__c = 4;
    	bookingItem.ParentBookingItemRef__c = null;
    	update bookingItem;
    	BookingEstimateItem__c bookingItem1 = TestCommon.createBookEstItem(leadInfo, productLst[1]);
    	// 予約情報のステータス：チェックインに変更する
    	bookingItem1.UnitPrice__c = 20000;
    	bookingItem1.ActionType__c = '前受付金';
    	bookingItem1.PaymentType__c = '予約金';
    	bookingItem1.refAccountMaster__c = productLst[1].Id;
    	bookingItem1.Amount__c = 4;
    	bookingItem1.ParentBookingItemRef__c = null;
    	update bookingItem;
    	Test.stopTest();
        ApexPages.StandardController contr3 = new ApexPages.StandardController(leadInfo);
        LeadBillPDFCtrl lbPdf = new LeadBillPDFCtrl(contr3);
        lbPdf.getNumberFormat();
        lbPdf.extInitAction();
        lbPdf.getReportLogo();
        lbPdf.getAccoutInfo();
        lbPdf.getAccountNo();
        lbPdf.getCustomer();
        lbPdf.getCharge();
        lbPdf.getRequestAmount();
        lbPdf.getTax();
        lbPdf.getIssueDate();
        lbPdf.getAdvancesReceived();
        lbPdf.getTran();
        lbPdf.getAmoutIncDiscont();
        lbPdf.getServiceDate();
        AccountAcount__c comment = lbPdf.comment;
        lbPdf.getServiceAmount();
    }
    private static void getCsvSetupConfig() {
        String csv = '<?xml version="1.0" encoding="UTF-8"?><root><SHOP><SHOPCODE></SHOPCODE><PAYMENT><CONVERT><PAYTYPE>現金</PAYTYPE><MEIDALAB>預り／現計</MEIDALAB></CONVERT><CONVERT><PAYTYPE>カード</PAYTYPE><MEIDALAB>ｸﾚ計・掛計等</MEIDALAB></CONVERT><CONVERT><PAYTYPE>売掛金</PAYTYPE><MEIDALAB>掛計</MEIDALAB></CONVERT><CONVERT><PAYTYPE>クーポン</PAYTYPE><MEIDALAB>クーポン</MEIDALAB></CONVERT><CONVERT><PAYTYPE>値引</PAYTYPE><MEIDALAB>値引・割引券</MEIDALAB></CONVERT><CONVERT><PAYTYPE>予約金</PAYTYPE><MEIDALAB>予約金</MEIDALAB></CONVERT></PAYMENT><PAYMEIDA><CONVERT><MEIDALAB>預り／現計</MEIDALAB><PRODCODE>87001</PRODCODE></CONVERT><CONVERT><MEIDALAB>ｸﾚ計・掛計等</MEIDALAB><PRODCODE>85201</PRODCODE></CONVERT><CONVERT><MEIDALAB>掛計</MEIDALAB><PRODCODE>85101</PRODCODE></CONVERT><CONVERT><MEIDALAB>クーポン</MEIDALAB><PRODCODE>85610</PRODCODE></CONVERT><CONVERT><MEIDALAB>値引・割引券</MEIDALAB><PRODCODE>87005</PRODCODE></CONVERT><CONVERT><MEIDALAB>予約金</MEIDALAB><PRODCODE>87001</PRODCODE></CONVERT></PAYMEIDA></SHOP></root>';
        
        Document doc = new Document();
        doc.Name = 'BillSimpleHelpConfig';
        doc.DeveloperName = doc.Name;
        doc.FolderId = UserInfo.getUserId();
        doc.Body = Blob.valueOf(csv);
        insert doc;
    }
    // 2018/12/15 請求書レイアウト改善 BY zyz BEGIN 
    private static void getBillPdfConfig() {
        String csv = '<?xml version="1.0" encoding="UTF-8"?><root><SHOP><SHOPCODE></SHOPCODE><BILLLAYOUTNAME><LEAD_PDF STYLE="font-size:12pt;" AOTUSPLIT="true">御支払 : $$_Field315__c_$$&lt;br/&gt;$$_Relcontact__r.Name_$$ 様&lt;br/&gt;予約名 : $$_Name_$$</LEAD_PDF></BILLLAYOUTNAME><BILLPDFLAYOUT><TITLELABEL>御  請  求  書</TITLELABEL><ROWSLABEL><ROW><COL STYLE="font-size:9pt;">毎度格別の御引立に預かり厚く御礼申し上げます。</COL></ROW><ROW><COL STYLE="font-size:9pt;">下記の通り御請求申し上げます。</COL></ROW></ROWSLABEL><PAYLABEL>お振込先お振込先</PAYLABEL></BILLPDFLAYOUT><LETTERLAYOUT><SUBJECTLABEL>書 類 送 付 の ご 案 内</SUBJECTLABEL><CUSTOM_SHIPPING>拝啓&lt;br/&gt;時下ますますご清栄のこととお喜び申し上げます。</CUSTOM_SHIPPING><REGARDSLABEL>敬具</REGARDSLABEL><RECORDLABEL>記</RECORDLABEL><DEPARTLABEL>■請求書 1部</DEPARTLABEL><ABOVELABEL>以上</ABOVELABEL></LETTERLAYOUT></SHOP></root>';
        Document doc = new Document();
        doc.Name = 'BillPdfConfig';
        doc.DeveloperName = doc.Name;
        doc.FolderId = UserInfo.getUserId();
        doc.Body = Blob.valueOf(csv);
        insert doc;
    }
    // 2018/12/15 請求書レイアウト改善 BY zyz END 
}