src/objects/AccountMaster__c.object
<CustomObject>
    <description>Master of account items</description>
    <fields>
        <fullName>SalesnoneTax__c</fullName>
        <formula>/* 2016/01/08 EDIT
if ( StsTaxfee__c = &quot;0&quot;, if ( MOD(Field5__c,(1 + TaxRateCal__c)) = 0, Field5__c /(1 + TaxRateCal__c), if ( ROUND(MOD(Field5__c,(1 + TaxRateCal__c)),2) &gt;= 0.30, ROUND(Field5__c /(1 + TaxRateCal__c),0), Field5__c /(1 + TaxRateCal__c) )), Field5__c)
*/
/*2017/06/23 EDIT
Case (
NULLVALUE($Setup.ps__CommDefine__c.ps__UnitPriceDefKb__c, 2) ,
1, if ( ps__StsTaxfee__c = &quot;0&quot;, if ( MOD(ps__Field5__c,(1 + ps__TaxRateCal__c)) = 0, ps__Field5__c /(1 + ps__TaxRateCal__c), if ( ROUND(MOD(ps__Field5__c,(1 + ps__TaxRateCal__c)),2) &gt;=  (NULLVALUE (ps__TargetCost__c, 0.30)), ROUND(ps__Field5__c /(1 + ps__TaxRateCal__c),0), ps__Field5__c /(1 + ps__TaxRateCal__c) )), ps__Field5__c),
2, if ( ps__StsTaxfee__c = &quot;0&quot;, if ( MOD(ps__Field5__c,(1 + ps__TaxRateCal__c)) = 0, ps__Field5__c /(1 + ps__TaxRateCal__c), if ( ROUND(MOD(ps__Field5__c,(1 + ps__TaxRateCal__c)),2) &gt;=  (NULLVALUE (ps__TargetCost__c, 0.30)), ROUND(ps__Field5__c /(1 + ps__TaxRateCal__c),0), ps__Field5__c /(1 + ps__TaxRateCal__c) )), ps__Field5__c),
3, ps__Field5__c,
4, ps__Field5__c,
ps__Field5__c)
*/

IF (NULLVALUE (TankawithoutTaxSys__c, 0) != 0, TankawithoutTaxSys__c, 

IF ( 
$Setup.CommDefine__c.AccountNoTaxCalFlg__c != true || 
$Setup.CommDefine__c.RoundType__c = 2, 
Case ( 
NULLVALUE( $Setup.CommDefine__c.UnitPriceDefKb__c, 0) , 
1, CEILING( NULLVALUE( Field5__c, 0) * ( 1 + NULLVALUE (ServiceRate__c, 0) ) / ( 1 + NULLVALUE (TaxRateCal__c, 0) ) ), 
2, CEILING( NULLVALUE( Field5__c, 0) / ( 1 + NULLVALUE (TaxRateCal__c, 0) ) ), 
3, CEILING( NULLVALUE( Field5__c, 0) * ( 1 + NULLVALUE (ServiceRate__c, 0) ) ), 
4, CEILING( NULLVALUE( Field5__c, 0)), 
0) 
, 
IF($Setup.CommDefine__c.RoundType__c = 0, 
Case ( 
NULLVALUE( $Setup.CommDefine__c.UnitPriceDefKb__c, 0) , 
1, FLOOR( NULLVALUE( Field5__c, 0) * ( 1 + NULLVALUE (ServiceRate__c, 0) ) / ( 1 + NULLVALUE (TaxRateCal__c, 0) ) ), 
2, FLOOR( NULLVALUE( Field5__c, 0) / ( 1 + NULLVALUE (TaxRateCal__c, 0) ) ), 
3, FLOOR( NULLVALUE( Field5__c, 0) * ( 1 + NULLVALUE (ServiceRate__c, 0) ) ), 
4, FLOOR( NULLVALUE( Field5__c, 0) ), 
0) 
, 
Case ( 
NULLVALUE( $Setup.CommDefine__c.UnitPriceDefKb__c, 0) , 
1, ROUND( NULLVALUE( Field5__c, 0) * ( 1 + NULLVALUE (ServiceRate__c, 0) ) / ( 1 + NULLVALUE (TaxRateCal__c, 0) ) , 0), 
2, ROUND( NULLVALUE( Field5__c, 0) / ( 1 + NULLVALUE (TaxRateCal__c, 0) ) , 0), 
3, ROUND( NULLVALUE( Field5__c, 0) * ( 1 + NULLVALUE (ServiceRate__c, 0) ) , 0), 
4, ROUND( NULLVALUE( Field5__c, 0) , 0), 
0) 
) 
) 

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>会計明細の$単価(税抜)</inlineHelpText>
        <label>$単価(税抜)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>会計商品</label>
    <nameField>
        <label>商品名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProcessedProduct__c.object
<CustomObject>
    <fields>
        <fullName>ItemProdcutRef__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>原材料</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipLabel>加工品</relationshipLabel>
        <relationshipName>ItemProcessedProdcutRef</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductRef__c</fullName>
        <label>完成商品</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipLabel>加工品（原材料）</relationshipLabel>
        <relationshipName>ProcessedProductRef</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Usage__c</fullName>
        <label>使用量</label>
        <precision>8</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>加工品</label>
    <nameField>
        <displayFormat>PP-{00000000}</displayFormat>
        <label>No#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProductOutStock__c.object
<CustomObject>
    <fields>
        <fullName>AccountMasterRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会計商品</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipLabel>ProductOutStock</relationshipLabel>
        <relationshipName>ProductOutStock</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OutStockDate__c</fullName>
        <description>売上日・受注日の日付、YYYYMMDD</description>
        <externalId>true</externalId>
        <label>出庫日</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductNumber__c</fullName>
        <label>商品数量</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductStock__c</fullName>
        <label>商品在庫情報</label>
        <referenceTo>ProductStock__c</referenceTo>
        <relationshipLabel>ProductOutStock</relationshipLabel>
        <relationshipName>ProductOutStock</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tankanonetax__c</fullName>
        <label>販売単価（税抜)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>商品出庫情報</label>
    <nameField>
        <displayFormat>POS-{000000000}</displayFormat>
        <label>商品出庫情報</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProductStock__c.object
<CustomObject>
    <fields>
        <fullName>ProductOutStock__c</fullName>
        <label>商品出庫数(理論）</label>
        <summarizedField>ProductOutStock__c.ProductNumber__c</summarizedField>
        <summaryFilterItems>
            <field>ProductOutStock__c.IsNotTarget__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>ProductOutStock__c.ProductStock__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ProductRef__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>会計商品</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipLabel>商品在庫情報</relationshipLabel>
        <relationshipName>StockProductRef</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>商品在庫情報</label>
    <nameField>
        <displayFormat>PS-{000000000}</displayFormat>
        <label>番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductOutStockTriggerProcess.cls
/**
* 商品出庫共通トリガー
* 
**/
public with sharing class ProductOutStockTriggerProcess {
	// 商品の加工品が存在する場合、関連の加工品連携処理を行う
	// 注意１LEVELまで対応する
	public void setStockInfo(List<ProductOutStock__c> nw, List<ProductOutStock__c> od, CommConst.TriggerMethod act) {
		Set<String> productSet = new Set<String>(); // 商品ID SET
		// 2018/12/15 販売単価对应 WGCH BEGIN
		// Set<String> outStockDtSet = new Set<String>(); // 売上日 SET
		Map<String, ProductOutStock__c> outStockMap = new Map<String, ProductOutStock__c>(); // KEY MAP
		// 2018/12/15 販売単価对应 WGCH END
		Map<String, Decimal> qtyOfStockMap = new Map<String, Decimal>(); // 商品ID + '_' + 売上日  => 最终变更的数量
		Map<String, Decimal> processedProductMap = new Map<String, Decimal>(); // 原材料商品ID => 最终变更的数量
		if(act == CommConst.TriggerMethod.IsInsert){ // 新規作業場合
			for(Integer i = 0; i < nw.size(); i++){
				ProductOutStock__c nwItem = nw[i];
				if(CommUtils.isBlank(nwItem.AccountMasterRef__c)) continue;
				// 2018/12/15 販売単価对应 WGCH BEGIN
				// String key = nwItem.AccountMasterRef__c + '_' + nwItem.OutStockDate__c; // 合成Key
				String key = getKey(nwItem); // 合成Key
				// 2018/12/15 販売単価对应 WGCH END
				qtyOfStockMap.put(key, CommUtils.nullToZero(nwItem.ProductNumber__c));
				productSet.add(nwItem.AccountMasterRef__c); // 获取商品ID ADD
				// 2018/12/15 販売単価对应 WGCH BEGIN
				// outStockDtSet.add(nwItem.OutStockDate__c); // 获取売上日 ADD
				if(!outStockMap.containsKey(getKeyEnd(nwItem))) outStockMap.put(getKeyEnd(nwItem), nwItem);
				// 2018/12/15 販売単価对应 WGCH END
				// 存在旧数据时处理
				if(od == null || od.isEmpty()) continue;
				ProductOutStock__c odItem = od[i];
				qtyOfStockMap.put(key, (CommUtils.nullToZero(nwItem.ProductNumber__c) - CommUtils.nullToZero(odItem.ProductNumber__c))); // 重置该商品对应的数量
			}
		}
		// 処理中止
		if (productSet.isEmpty()) return;
		// 2018/12/15 販売単価对应 WGCH BEGIN
		Map<String, ProcessedProduct__c> processedProductDataMap = new Map<String, ProcessedProduct__c>();
		// 查出加工品
		// List<ProcessedProduct__c> processedProductLst = [Select Id, ProductRef__c, ItemProdcutRef__c, Usage__c From ProcessedProduct__c Where ProductRef__c in: productSet And ItemProdcutRef__c != null and Usage__c > 0];
		List<ProcessedProduct__c> processedProductLst = [Select Id, ProductRef__c, ItemProdcutRef__c, Usage__c, ItemProdcutRef__r.SalesnoneTax__c From ProcessedProduct__c Where ProductRef__c in: productSet And ItemProdcutRef__c != null and Usage__c > 0];
		// 2018/12/15 販売単価对应 WGCH END
		// 処理中止
		if (processedProductLst.isEmpty()) return;
		Set<Id> processedProductSet = new Set<Id>(); // 原材料商品ID
		for(ProcessedProduct__c product : processedProductLst){
			// 2018/12/15 販売単価对应 WGCH BEGIN
			/*
			for(String outStockDt : outStockDtSet){
				String key = product.ProductRef__c + '_' + outStockDt; // 合成完成商品Key
				String itemKey = product.ItemProdcutRef__c + '_' + outStockDt; // 合成原材料商品Key
			*/
			// 集计原材料,对应的数据集
			processedProductDataMap.put(product.ItemProdcutRef__c, product);
			for(String outStockKey : outStockMap.keySet()){
				String key = product.ProductRef__c + '_' + outStockKey; // 合成完成商品Key
				String itemKey = product.ItemProdcutRef__c + '_' + outStockKey; // 合成原材料商品Key
			// 2018/12/15 販売単価对应 WGCH END
				if(!qtyOfStockMap.containsKey(key)) continue;
				if(!processedProductMap.containsKey(itemKey)) processedProductMap.put(itemKey, 0); // 为了处理重复商品
				Decimal wkUsage = processedProductMap.get(itemKey) + CommUtils.nullToZero(product.Usage__c) * qtyOfStockMap.get(key); // 算出此原材料一共用的数量;
				processedProductMap.put(itemKey, wkUsage); // 原材料商品,数量集计
				processedProductSet.add(product.ItemProdcutRef__c); 
			}
		}
		// 会計商品在庫情報のIDを取得、自動作成処理を行う
		StockChangeHelpUtils help = new StockChangeHelpUtils();
		// 商品在庫の親IDを取得する
		// map<商品ID、商品在庫ID>
		map<id,id> parentIdMap = help.getProdcutStockById(processedProductSet);
		// 加工品の在庫情報を自動登録する
		List<ProductOutStock__c> newProOutStockLst = new List<ProductOutStock__c>(); // 出库商品信息
		for(Id productId : parentIdMap.keySet()){ // 遍历当前的所有在库
			// 2018/12/15 販売単価对应 WGCH BEGIN
			/*
			for(String outStockDt : outStockDtSet){
				String outStockDtKey = productId + '_' + outStockDt;
				if(!processedProductMap.containsKey(outStockDtKey) || CommUtils.nullToIntZero(processedProductMap.get(outStockDtKey)) == 0) continue;
			*/
			ProcessedProduct__c processedProduct = processedProductDataMap.get(productId); // 获取原材料信息
			for(String outStockKey : outStockMap.keySet()){
				ProductOutStock__c outStock = outStockMap.get(outStockKey); // 获取主出库
				String itemKey = productId + '_' + outStockKey; // 合成完成商品Key
				// 2018/12/29 BugFix 数量は小数点の場合不具合対応 WSQ BEGNIN
				if(!processedProductMap.containsKey(itemKey) || CommUtils.nullToZero(processedProductMap.get(itemKey)) == 0) continue;
				//if(!processedProductMap.containsKey(itemKey) || CommUtils.nullToIntZero(processedProductMap.get(itemKey)) == 0) continue;
				// 2018/12/29 BugFix 数量は小数点の場合不具合対応 WSQ END
			// 2018/12/15 販売単価对应 WGCH END
				newProOutStockLst.add(new ProductOutStock__c(
											ProductStock__c = parentIdMap.get(productId),
											AccountMasterRef__c = productId,
											// 2018/12/15 販売単価对应 WGCH BEGIN
											// ProductNumber__c = processedProductMap.get(outStockDtKey),
											// OutStockDate__c = CommUtils.nullToBlank(outStockDt)
											ProductNumber__c = processedProductMap.get(itemKey)
											, OutStockDate__c = CommUtils.nullToBlank(outStock.OutStockDate__c)
											//, AccountAcountRef__c = outStock.AccountAcountRef__c
											, Tankanonetax__c = processedProduct == null ? 0 : CommUtils.nullToZero(processedProduct.ItemProdcutRef__r.SalesnoneTax__c)
											// 2018/12/15 販売単価对应 WGCH END
											));
			}
			
		}
		if(!newProOutStockLst.isEmpty()) {
			DataFixManagerUtils.stopTranTriggger();
			insert newProOutStockLst;
			DataFixManagerUtils.begTranTriggger();
		}
	}
	// 2018/12/15 販売単価对应 WGCH BEGIN
	// 商品ID_売上日_販売単価（税抜)でキーを返却する
	private String getKey(ProductOutStock__c outStock) {
		return (outStock.AccountMasterRef__c + '_' + getKeyEnd(outStock));
	}
	// 売上日_販売単価（税抜)でキーを返却する
	private String getKeyEnd(ProductOutStock__c outStock) {
		return (outStock.OutStockDate__c + '_' + CommUtils.nullToZero(outStock.Tankanonetax__c));
	}
	// 2018/12/15 販売単価对应 WGCH END
}