src/objects/AccountMaster__c.object
<CustomObject>
    <description>Master of account items</description>
    <fields>
        <fullName>Field4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>リンクＤＰコード</label>
        <referenceTo>DP__c</referenceTo>
        <relationshipName>AccountMasterKmH3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会計商品</label>
    <nameField>
        <label>商品名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BookingEstimateItem__c.object
<CustomObject>
    <description>Details Estimate for Booking</description>
    <fields>
        <fullName>Field4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>リンクＤＰコード</label>
        <referenceTo>DP__c</referenceTo>
        <relationshipLabel>会計マスタ</relationshipLabel>
        <relationshipName>BookingEstimateItemKmH3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>予約見積明細</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>予約見積明細#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead__c.object
<CustomObject>
    <description>Booking sheet with record type</description>
    <fields>
        <fullName>EntryTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <inlineHelpText>お客様が来られる予定の日付を選択してください。</inlineHelpText>
        <label>到着日</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Field4__c</fullName>
        <inlineHelpText>お着きの時間を選択してください。</inlineHelpText>
        <label>到着時刻</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>11:00</fullName>
                </value>
                <value>
                    <fullName>11:10</fullName>
                </value>
                <value>
                    <fullName>11:20</fullName>
                </value>
                <value>
                    <fullName>11:30</fullName>
                </value>
                <value>
                    <fullName>11:40</fullName>
                </value>
                <value>
                    <fullName>11:50</fullName>
                </value>
                <value>
                    <fullName>12:00</fullName>
                </value>
                <value>
                    <fullName>12:10</fullName>
                </value>
                <value>
                    <fullName>12:20</fullName>
                </value>
                <value>
                    <fullName>12:30</fullName>
                </value>
                <value>
                    <fullName>12:40</fullName>
                </value>
                <value>
                    <fullName>12:50</fullName>
                </value>
                <value>
                    <fullName>13:00</fullName>
                </value>
                <value>
                    <fullName>13:10</fullName>
                </value>
                <value>
                    <fullName>13:20</fullName>
                </value>
                <value>
                    <fullName>13:30</fullName>
                </value>
                <value>
                    <fullName>13:40</fullName>
                </value>
                <value>
                    <fullName>13:50</fullName>
                </value>
                <value>
                    <fullName>14:00</fullName>
                </value>
                <value>
                    <fullName>14:10</fullName>
                </value>
                <value>
                    <fullName>14:20</fullName>
                </value>
                <value>
                    <fullName>14:30</fullName>
                </value>
                <value>
                    <fullName>14:40</fullName>
                </value>
                <value>
                    <fullName>14:50</fullName>
                </value>
                <value>
                    <fullName>15:00</fullName>
                    <default>true</default>
                    <label>15:00</label>
                </value>
                <value>
                    <fullName>15:10</fullName>
                </value>
                <value>
                    <fullName>15:20</fullName>
                </value>
                <value>
                    <fullName>15:30</fullName>
                </value>
                <value>
                    <fullName>15:40</fullName>
                </value>
                <value>
                    <fullName>15:50</fullName>
                </value>
                <value>
                    <fullName>10:00</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Morningfood__c</fullName>
        <defaultValue>false</defaultValue>
        <description>朝食をつける場合チェック！</description>
        <inlineHelpText>朝食7:30〜または8:30〜</inlineHelpText>
        <label>朝食</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Relcontact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>お客様</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ご予約</relationshipLabel>
        <relationshipName>reservetg85</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReservedContact__c</fullName>
        <label>予約受付者</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ono</fullName>
                    <color>#0B6FCE</color>
                    <label>Ono</label>
                </value>
                <value>
                    <fullName>Kino</fullName>
                    <color>#78C953</color>
                    <label>Kino</label>
                </value>
                <value>
                    <fullName>Takahashi</fullName>
                </value>
                <value>
                    <fullName>Yamaga</fullName>
                </value>
                <value>
                    <fullName>Nishina</fullName>
                </value>
                <value>
                    <fullName>Aoki</fullName>
                    <color>#FF6600</color>
                    <label>Aoki</label>
                </value>
                <value>
                    <fullName>Katou</fullName>
                    <color>#FF0000</color>
                    <label>Katou</label>
                </value>
                <value>
                    <fullName>Ebata</fullName>
                    <color>#663366</color>
                    <label>Ebata</label>
                </value>
                <value>
                    <fullName>Akiyama</fullName>
                </value>
                <value>
                    <fullName>Kobayashi</fullName>
                </value>
                <value>
                    <fullName>Miyazaki-President</fullName>
                </value>
                <value>
                    <fullName>Miyazaki-Okami</fullName>
                </value>
                <value>
                    <fullName>Igarashi</fullName>
                </value>
                <value>
                    <fullName>Yaegashi</fullName>
                </value>
                <value>
                    <fullName>Sugimoto</fullName>
                </value>
                <value>
                    <fullName>Morimoto</fullName>
                    <color>#33FFFF</color>
                    <label>Morimoto</label>
                </value>
                <value>
                    <fullName>----------------</fullName>
                </value>
                <value>
                    <fullName>--(Yuuki)--</fullName>
                </value>
                <value>
                    <fullName>--(Horikoshi)--</fullName>
                </value>
                <value>
                    <fullName>--(Kasaba-Manager)--</fullName>
                    <color>#A845DC</color>
                    <label>--(Kasaba-Manager)--</label>
                </value>
                <value>
                    <fullName>--(Yamanashi)--</fullName>
                    <color>#666666</color>
                    <label>--(Yamanashi)--</label>
                </value>
                <value>
                    <fullName>--(Mineo)--</fullName>
                    <color>#419249</color>
                    <label>--(Mineo)--</label>
                </value>
                <value>
                    <fullName>--(Yamauchi)--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReservedDate__c</fullName>
        <description>ご予約の受付日</description>
        <label>予約受付日</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ReservedStatus__c</fullName>
        <inlineHelpText>NO SHOW、キャンセルまたは、削除への変更について、パラメータにより一括キャンセルする／しないを選択可能(連泊のときのみ有効)となります。</inlineHelpText>
        <label>予約ステータス</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>確認中</fullName>
                </value>
                <value>
                    <fullName>確定</fullName>
                    <default>true</default>
                    <label>確定</label>
                </value>
                <value>
                    <fullName>会場おさえ</fullName>
                </value>
                <value>
                    <fullName>仮予約</fullName>
                </value>
                <value>
                    <fullName>キャンセルまち</fullName>
                </value>
                <value>
                    <fullName>NO SHOW</fullName>
                </value>
                <value>
                    <fullName>キャンセル</fullName>
                </value>
                <value>
                    <fullName>削除</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rroom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>本予約にお部屋を一つ割当てください。
お部屋を2つ以上割り当てる場合は、同一お客様名の新規予約を作成してください。</inlineHelpText>
        <label>部屋</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Room__c.TypeRoomRef__c</field>
                <operation>equals</operation>
                <valueField>$Source.refTypeOfRooms__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>ご予約</relationshipLabel>
        <relationshipName>R00N10000000rzUoEAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>room1__c</fullName>
        <label>室料1</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>ご予約</label>
    <nameField>
        <label>予約名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Room__c.object
<CustomObject>
    <description>Master Gest Room, Hall and Resource</description>
    <fields>
        <fullName>CapacityHaku__c</fullName>
        <label>定員 宿泊</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>定員 食事</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Field4__c</fullName>
        <label>名の由来</label>
        <length>400</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ParentRoomRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>宴会場は分ける利用したい場合、分けている場所の親部屋は設定が必要</inlineHelpText>
        <label>親部屋</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>お部屋</relationshipLabel>
        <relationshipName>ParentRoomRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seq__c</fullName>
        <inlineHelpText>予定表レポートの表示順序</inlineHelpText>
        <label>Seq#</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UseOfRoom__c</fullName>
        <label>UseOfRoom</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>客室</fullName>
                </value>
                <value>
                    <fullName>広間</fullName>
                </value>
                <value>
                    <fullName>レストラン</fullName>
                </value>
                <value>
                    <fullName>その他</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>宴会場</fullName>
                </value>
                <value>
                    <fullName>架空</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>heyadashiryou__c</fullName>
        <label>サービス料[通常]</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>heyadashiryouryou__c</fullName>
        <label>サービス料[正月]</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>お部屋</label>
    <nameField>
        <label>お部屋</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BookingTimeTableTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class BookingTimeTableTest {
	
	@isTest(SeeAllData=false)
	static void testBookingTimeTable(){	// Testmethod of BookingTimeTable 
		Room__c proom = new Room__c(Name = CommUtils.getRandom(10), UseOfRoom__c = CommConst.ROOM_UseOfType_PTY, Seq__c = Integer.valueOf(CommUtils.getRandom(6)), CapacityHaku__c = 0, Capacity__c = 80, heyadashiryou__c = 20000, heyadashiryouryou__c = 20000);
		insert proom;
		Room__c roomtest = new Room__c(Name = CommUtils.getRandom(10), ParentRoomRef__c= proom.Id, UseOfRoom__c = CommConst.ROOM_UseOfType_PTY, Seq__c = Integer.valueOf(CommUtils.getRandom(6)), CapacityHaku__c = 1, Capacity__c = 180, heyadashiryou__c = 22000, heyadashiryouryou__c = 24000);
		insert roomtest;
		Date curDay  = Date.today();
		DateTime startDate = DateTime.newInstance(curDay.addDays(30), Time.newInstance(0, 0, 0, 0));
//		Lead__c bookingtest = new Lead__c(Name = 'TestBooking', Morningfood__c = true, room1__c = 20000, EntryTime__c = datetime.now(), ReservedDate__c = datetime.now(), Rroom__c = roomtest.Id);
		Lead__c bookingtest = new Lead__c(
		   name = '予約単体テスト_UNIT_TEST_LEAD' + System.now(), // 予約名
    	   Relcontact__c = TestCommon.createContact().Id,                  // 顧客名
    	   ReservedStatus__c = '確認中',
    	   ReservedDate__c = System.now(),
    	   ReservedContact__c = 'Ono',
    	   EntryTime__c = startDate,
    	   Field4__c = '15:30',
    	   Departure__c = startDate.addDays(1),
    	   Field3__c = '10:00',
    	   StayPersons__c = 4,
    	   Field2__c = 'FAX',
    	   Rroom__c = roomtest.Id);
		insert bookingtest;
		BookingTimeTable__c btttest = new BookingTimeTable__c(Checkinday__c = bookingtest.EntryTime__c.date());
		insert btttest;

		OP__c opothertest = new OP__c(Name = 'その他');
		insert opothertest;
		AccountMaster__c amtest = new AccountMaster__c(OP__c = opothertest.Id);
		insert amtest;
		BookingEstimateItem__c beifoodtest  = new BookingEstimateItem__c(refBooking__c = bookingtest.Id, refAccountMaster__c = amtest.Id);
		insert beifoodtest;

		BookingTimeTable btt = new BookingTimeTable();
		btt.selectDate.Checkinday__c = bookingtest.EntryTime__c.date();
		btt.gotoDate();
		System.assertEquals(btt.cdate, bookingtest.EntryTime__c.date());

		List<Room__c>	wgetRoom		= btt.getRoom();
//		Object[]		wgetBookingData	= btt.getBookingData();
//		Object[]		wgetRoomData	= btt.getRoomData();

        for (BookingTimeTable.OneRoomAssingInfo obj: btt.roomBookingMap.values()) {
        	System.assertNotEquals(obj.tdHtml, null);
        }
		List<integer>	wgetHours		= btt.getHours();
		btt.refreshTimePanel();
		PageReference	wbookingCreate	= btt.bookingCreate();
		btt.toNext();
		btt.toPrev();
		btt.toToday();
		btt.toPrevWeek();
		btt.toNextWeek();
		btt.setTimeLineHtml();
		//BookingTimeTable btt2 = new BookingTimeTable(new ApexPages.StandardController(btttest));

	}
	
	@isTest(SeeAllData=false)
    static void testCustomInputFields(){
    	// ドキュメントを作成する
    	Document item = new Document();
    	item.Name = 'BookingTimeLeadInputExtendFieldsXml';
    	item.DeveloperName = item.Name;
    	item.FolderId = UserInfo.getUserId();
    	item.Body = Blob.valueOf('<root><shop><SHOPCODE></SHOPCODE><FIELDS>Mans__c,Femails__c,Morningfood__c</FIELDS></shop></root>');
    	insert item;
    	// 2015/12/01 Assert BEGIN
		System.assertEquals([select Id from Document where Name = 'BookingTimeLeadInputExtendFieldsXml'].size(), 1);
		// 2015/12/01 Assert END

		//Room__c proom = new Room__c(Name = CommUtils.getRandom(10), UseOfRoom__c = ROOM_TYPE_PTY, Seq__c = Integer.valueOf(CommUtils.getRandom(6)), CapacityHaku__c = 0, Capacity__c = 80, heyadashiryou__c = 20000, heyadashiryouryou__c = 20000);
		Room__c proom = new Room__c(Name = CommUtils.getRandom(10), UseOfRoom__c = CommConst.ROOM_UseOfType_PTY, Seq__c = Integer.valueOf(CommUtils.getRandom(6)), CapacityHaku__c = 0, Capacity__c = 80, heyadashiryou__c = 20000, heyadashiryouryou__c = 20000);
		insert proom;
		//Room__c roomtest = new Room__c(Name = CommUtils.getRandom(10), ParentRoomRef__c= proom.Id, UseOfRoom__c = ROOM_TYPE_PTY, Seq__c = Integer.valueOf(CommUtils.getRandom(6)), CapacityHaku__c = 1, Capacity__c = 180, heyadashiryou__c = 22000, heyadashiryouryou__c = 24000);
		Room__c roomtest = new Room__c(Name = CommUtils.getRandom(10), ParentRoomRef__c= proom.Id, UseOfRoom__c = CommConst.ROOM_UseOfType_PTY, Seq__c = Integer.valueOf(CommUtils.getRandom(6)), CapacityHaku__c = 1, Capacity__c = 180, heyadashiryou__c = 22000, heyadashiryouryou__c = 24000);
		insert roomtest;
		Date curDay  = Date.today();
		DateTime startDate = DateTime.newInstance(curDay.addDays(30), Time.newInstance(0, 0, 0, 0));
		
		BookingTimeTable ctrl = new BookingTimeTable();
		ctrl.getInputExtendFields();
	}
}