src/objects/AccountMaster__c.object
<CustomObject>
    <description>Master of account items</description>
    <fields>
        <fullName>ActionType__c</fullName>
        <description>普通の商品は　デフォルト値：通常で設定する、特別商品に対して、別々、商品種別に設定する
前受付金の場合、会計商品マスたに、価格はNull設定して、入力画面に自由入力する</description>
        <label>商品処理種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>通常</fullName>
                    <default>true</default>
                    <label>通常</label>
                </value>
                <value>
                    <fullName>前受付金</fullName>
                </value>
                <value>
                    <fullName>プラン</fullName>
                </value>
                <value>
                    <fullName>室料</fullName>
                </value>
                <value>
                    <fullName>朝食</fullName>
                </value>
                <value>
                    <fullName>夕食</fullName>
                </value>
                <value>
                    <fullName>非表示</fullName>
                </value>
                <value>
                    <fullName>支払</fullName>
                </value>
                <value>
                    <fullName>サービス料</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BatchProcessStatusDiv__c</fullName>
        <description>増税処理するため、データ処理される状態を標識する、画面へ非表示する</description>
        <label>バッチ処理区分</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field7__c</fullName>
        <label>原価</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ServiceRate__c</fullName>
        <description>サービス料金（％）</description>
        <label>サービス料(%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SpecialTax__c</fullName>
        <defaultValue>0</defaultValue>
        <label>特別税</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>jmstRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>消費税マスタ</label>
        <referenceTo>JMST__c</referenceTo>
        <relationshipName>jmst</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会計商品</label>
    <nameField>
        <label>商品名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BookingEstimateItem__c.object
<CustomObject>
    <description>Details Estimate for Booking</description>
    <fields>
        <fullName>ActionType__c</fullName>
        <description>普通の商品は　デフォルト値：通常で設定する、特別商品に対して、別々、商品種別に設定する
前受付金の場合、会計商品マスたに、価格はNull設定して、入力画面に自由入力する</description>
        <label>商品処理種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>通常</fullName>
                    <default>true</default>
                    <label>通常</label>
                </value>
                <value>
                    <fullName>前受付金</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BatchProcessStatusDiv__c</fullName>
        <description>増税処理するため、データ処理される状態を標識する、画面へ非表示する</description>
        <label>バッチ処理区分</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field7__c</fullName>
        <label>原価</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ParentBookingItemRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>親予約見積明細</label>
        <referenceTo>BookingEstimateItem__c</referenceTo>
        <relationshipLabel>予約見積明細</relationshipLabel>
        <relationshipName>ParentBookingItemRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PlanDetailSyncInfo__c</fullName>
        <description>見積明細編集画面、直接入力のプラン明細の単価を格納する、該当項目で、明細自動作成・更新する場合、該当単価で、明細へ連携更新を行う 
Format: プラン明細ID/見積明細ID:単価;プラン明細ID/見積明細ID:単価 書式で複数件格納する（最大600件明細格納可能です）</description>
        <label>プラン明細個別設定情報</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ServiceRate__c</fullName>
        <description>サービス料金（％）</description>
        <label>サービス料(%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SpecialTax__c</fullName>
        <defaultValue>0</defaultValue>
        <label>特別税</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TaxRate__c</fullName>
        <label>消費税</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <formula>NULLVALUE(SpTotal__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>$合計金額(税込)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UnitPriceDefKb__c</fullName>
        <defaultValue>TEXT($Setup.CommDefine__c.UnitPriceDefKb__c)</defaultValue>
        <label>会計商品単価定義区分</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <inlineHelpText>空欄のまま保存すると、会計商品で定義した単価が設定されます</inlineHelpText>
        <label>単価</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>refAccountMaster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>商品を選択して下さい</inlineHelpText>
        <label>商品名</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipLabel>予約見積明細</relationshipLabel>
        <relationshipName>BookingEstimateItemhSGP</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>refBooking__c</fullName>
        <label>ご予約</label>
        <referenceTo>Lead__c</referenceTo>
        <relationshipLabel>予約見積明細</relationshipLabel>
        <relationshipName>BookingEstimateItemFgKu</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>予約見積明細</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>予約見積明細#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CommDefine__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>AutoCreateBookingEstFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>ご予約内にある「プラン」という項目を入力する、このプランが予約見積明細に登録する、しない切り替えフラグ
TRUE:プランが見積明細へ反映されない
FALSE：プランが見積明細へ反映する（デフォルト値）</inlineHelpText>
        <label>ご予約のプランが見積明細に反映する・しないフラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PDDetailsInputDefaultLines__c</fullName>
        <defaultValue>10</defaultValue>
        <inlineHelpText>プラン設定画面の明細のデフォルト行数 10（デフォルト値）</inlineHelpText>
        <label>プラン明細デフォルト行数</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnitPriceDefKb__c</fullName>
        <inlineHelpText>1:税込、サービス料抜き
2:税込、サービス料込
3:税抜、サービス料抜き
4:税抜、サビース料込</inlineHelpText>
        <label>会計商品単価定義区分</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>共通定義</label>
</CustomObject>

src/objects/JMST__c.object
<CustomObject>
    <description>Tax of sales</description>
    <fields>
        <fullName>TaxRate__c</fullName>
        <label>税率</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <label>消費税</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>消費税マスタ名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead__c.object
<CustomObject>
    <description>Booking sheet with record type</description>
    <fields>
        <fullName>EntryTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <inlineHelpText>お客様が来られる予定の日付を選択してください。</inlineHelpText>
        <label>到着日</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Field298__c</fullName>
        <inlineHelpText>チェックインへ変更することで、予約見積明細の内容が会計計上されます、連泊のお客様のときも日ごとにチェックインステータスへ変更する必要がありますのでご注意が必要です。</inlineHelpText>
        <label>お客様ステータス</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>チェックイン完</fullName>
                </value>
                <value>
                    <fullName>チェックアウト完</fullName>
                </value>
                <value>
                    <fullName>外出中</fullName>
                </value>
                <value>
                    <fullName>入浴中</fullName>
                </value>
                <value>
                    <fullName>滞在中</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PlanDetailSyncInfo__c</fullName>
        <description>該当予約のプラン項目を設定される場合、プラン明細情報設定情報がカスタムマイズの場合、カスタムマイズ情報は該当項目に格納する
Format: 商品ID,単価:商品ID,単価</description>
        <label>プラン明細個別設定情報</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>UnitPriceDefKb__c</fullName>
        <defaultValue>TEXT($Setup.CommDefine__c.UnitPriceDefKb__c)</defaultValue>
        <label>会計商品単価定義区分</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>ご予約</label>
    <nameField>
        <label>予約名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>Master Package code Plan</description>
    <fields>
        <fullName>JmstRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>消費税</label>
        <referenceTo>JMST__c</referenceTo>
        <relationshipLabel>プラン</relationshipLabel>
        <relationshipName>PlanJmsRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PackageCode__c</fullName>
        <label>パッケージコード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PlanNo__c</fullName>
        <label>PlanNo</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>プラン金額</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ServiceRate__c</fullName>
        <label>サービス料(%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>プラン</label>
    <nameField>
        <label>Plan</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tran1__c.object
<CustomObject>
    <description>*** Account Order Details</description>
    <fields>
        <fullName>ActionType__c</fullName>
        <description>普通の商品は　デフォルト値：通常で設定する、特別商品に対して、別々、商品種別に設定する
前受付金の場合、会計商品マスたに、価格はNull設定して、入力画面に自由入力する</description>
        <label>商品処理種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>通常</fullName>
                    <default>true</default>
                    <label>通常</label>
                </value>
                <value>
                    <fullName>前受付金</fullName>
                </value>
                <value>
                    <fullName>室料</fullName>
                </value>
                <value>
                    <fullName>朝食</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BatchProcessStatusDiv__c</fullName>
        <label>バッチ処理区分</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field7__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>商品コード</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipName>Tran1Service</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentTran1Ref__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>親会計明細</label>
        <referenceTo>Tran1__c</referenceTo>
        <relationshipLabel>会計明細</relationshipLabel>
        <relationshipName>ParentTran1Ref</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PlanDetailSyncInfo__c</fullName>
        <description>会計編集画面、直接入力のプラン明細の単価を格納する、該当項目で、明細自動作成・更新する場合、該当単価で、明細へ連携更新を行う 
Format: 商品ID/会計明細ID,単価:商品ID/会計明細ID,単価 書式で複数件格納する（最大600件明細格納可能です）</description>
        <label>プラン明細個別設定情報</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SpecialTax__c</fullName>
        <label>特別税</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TaxRate__c</fullName>
        <label>消費税</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>UnitPriceDefKb__c</fullName>
        <defaultValue>TEXT($Setup.CommDefine__c.UnitPriceDefKb__c)</defaultValue>
        <label>会計商品単価定義区分</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>会計明細</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>会計明細TranR#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SalesTax8UpdaterChouManTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class SalesTax8UpdaterChouManTest {
    // 2019/08/12 消費税は8%から10%に変更対応 WGCH BEGIN
    /*
    @isTest(SeeAllData=false)
	static void testCase1() {
		CommDefine__c comDef = TestCommon.createCommDefine();
		comDef.UnitPriceDefKb__c = 2;
		update comDef; 
		// ２０１４・０３・３０開始４連泊予約情報を設定する
		Date startDt = Date.newInstance(2014,3,30);
		Date changeDate = Date.newInstance(2014,4,1);
    	// 予約情報を作成する(4連泊予約情報を作成する)
    	List<Lead__c> leadInfos = TestCommon.createLead(startDt, 1, 4);
		// 見積もり明細情報を更新を行う（消費税マスタは５％のまま、更新する場合、2014/04/01以後の見積もり明細の消費税率は全部８％に変更されるの確認
		List<BookingEstimateItem__c> confirms = [select Id, TaxRate__c from BookingEstimateItem__c where TaxRate__c > 0];
		Integer oneDateDetails = confirms.size() / 4;
		Test.startTest();
		SalesTax8UpdaterChouMan m = new SalesTax8UpdaterChouMan();
		DateTime nowTime = DateTime.now().addSeconds(10);
		// 起動ＣＲＯＮを設定する
		String timeStr = nowTime.format('yyyyMMddHHmmss');
		String yy = timeStr.substring(0,4);
		String mm = timeStr.substring(4,6);
		String dd = timeStr.substring(6,8);
		String hh = timeStr.substring(8,10);
		String ms = timeStr.substring(10,12);
		String ss = timeStr.substring(12,14);
		String sch = ss + ' ' +
		       ms + ' ' +
		       hh + ' ' +
		       dd + ' ' +
		       mm + ' ' +
		       ' ? ' + yy;
		String jobName = DateTime.now().format('yyyyMMddHHmmssSSS') + '|' + String.valueof(Crypto.getRandomLong());
		String jobId = system.schedule(jobName, sch, m);
		
		SalesTax8UpdaterChouMan batch = new SalesTax8UpdaterChouMan(UserInfo.getUserId());
		ID batchprocessid = Database.executeBatch(batch);
		Test.stopTest();
		// 処理結果確認を行う
		List<BookingEstimateItem__c> items = [select Id, TaxRate__c from BookingEstimateItem__c where DAY_ONLY(convertTimezone(refBooking__r.EntryTime__c)) >= :changeDate];
		// 全部明細件数を計算する
		System.assertEquals(items.size(), oneDateDetails * 2);
		for (BookingEstimateItem__c item : items) {
			system.assertEquals(item.TaxRate__c, 8, item);
		}
	}
	*/
	@isTest(SeeAllData=false)
	static void testCase2() {
		CommDefine__c comDef = TestCommon.createCommDefine();
		comDef.UnitPriceDefKb__c = 2;
		update comDef; 
		// ２０１４・０３・３０開始４連泊予約情報を設定する
		Date startDt = Date.newInstance(2019,9,29);
		Date changeDate = Date.newInstance(2019,10,1);
    	// 予約情報を作成する(4連泊予約情報を作成する)
    	List<Lead__c> leadInfos = TestCommon.createLead(startDt, 1, 4);
		// 見積もり明細情報を更新を行う（消費税マスタは５％のまま、更新する場合、2014/04/01以後の見積もり明細の消費税率は全部８％に変更されるの確認
		List<BookingEstimateItem__c> confirms = [select Id, TaxRate__c from BookingEstimateItem__c where TaxRate__c > 0];
		Integer oneDateDetails = confirms.size() / 4;
		Test.startTest();
		SalesTax8UpdaterChouMan m = new SalesTax8UpdaterChouMan();
		DateTime nowTime = DateTime.now().addSeconds(10);
		// 起動ＣＲＯＮを設定する
		String timeStr = nowTime.format('yyyyMMddHHmmss');
		String yy = timeStr.substring(0,4);
		String mm = timeStr.substring(4,6);
		String dd = timeStr.substring(6,8);
		String hh = timeStr.substring(8,10);
		String ms = timeStr.substring(10,12);
		String ss = timeStr.substring(12,14);
		String sch = ss + ' ' +
		       ms + ' ' +
		       hh + ' ' +
		       dd + ' ' +
		       mm + ' ' +
		       ' ? ' + yy;
		String jobName = DateTime.now().format('yyyyMMddHHmmssSSS') + '|' + String.valueof(Crypto.getRandomLong());
		String jobId = system.schedule(jobName, sch, m);
		
		SalesTax8UpdaterChouMan batch = new SalesTax8UpdaterChouMan(UserInfo.getUserId());
		ID batchprocessid = Database.executeBatch(batch);
		Test.stopTest();
		// 処理結果確認を行う
		List<BookingEstimateItem__c> items = [select Id, TaxRate__c from BookingEstimateItem__c where DAY_ONLY(convertTimezone(refBooking__r.EntryTime__c)) >= :changeDate];
		// 全部明細件数を計算する
		System.assertEquals(items.size(), oneDateDetails * 2);
		for (BookingEstimateItem__c item : items) {
			system.assertEquals(item.TaxRate__c, 10, item);
		}
	}
	// 2019/08/12 消費税は8%から10%に変更対応 WGCH END
	// 2019/09/17 消費税は8%から10%に変更対応 WSQ BEGIN(総金額そのまま、単価を自動調整バッチ) BEGIN
	@isTest(SeeAllData=false)
	static void testCase3_1() {
		// 単価定義区分が1
		CommDefine__c comDef = TestCommon.createCommDefine();
		comDef.UnitPriceDefKb__c = 1;
		comdef.AutoCreateBookingEstFlg__c = false;
		update comDef; 
		// ２０１４・０３・３０開始４連泊予約情報を設定する
		Date startDt = Date.newInstance(2019,10,1);
		// プラン作成する
		// ご予約と見積もり作成
    	// 予約情報を作成する(4連泊予約情報を作成する)
    	List<Lead__c> leadInfos = TestCommon.createLead2IncRoomRate(startDt, 1, 3,null);
		List<BookingEstimateItem__c> confirms = [select Id, TaxRate__c,UnitPrice__c,Total__c from BookingEstimateItem__c where TaxRate__c > 0 order by name];	
system.debug(loggingLevel.info, 'confirms[BEG]='+confirms);
		map<id, BookingEstimateItem__c> existMap = new map<id, BookingEstimateItem__c>();
		for (BookingEstimateItem__c est : confirms) {
			existMap.put(est.id, est);
		}
		for(Lead__c ld : leadInfos){
			ld.Field298__c = 'チェックイン完';
		}
    	update leadInfos;
		// ================== 更新処理 ================== 
		Test.startTest();
		SalesTax8UpdaterChouMan2 m = new SalesTax8UpdaterChouMan2();
		DateTime nowTime = DateTime.now().addSeconds(10);
		// 起動ＣＲＯＮを設定する
		String timeStr = nowTime.format('yyyyMMddHHmmss');
		String yy = timeStr.substring(0,4);
		String mm = timeStr.substring(4,6);
		String dd = timeStr.substring(6,8);
		String hh = timeStr.substring(8,10);
		String ms = timeStr.substring(10,12);
		String ss = timeStr.substring(12,14);
		String sch = ss + ' ' +
		       ms + ' ' +
		       hh + ' ' +
		       dd + ' ' +
		       mm + ' ' +
		       ' ? ' + yy;
		String jobName = DateTime.now().format('yyyyMMddHHmmssSSS') + '|' + String.valueof(Crypto.getRandomLong());
		String jobId = system.schedule(jobName, sch, m);
	
		SalesTax8UpdaterChouMan2 batch = new SalesTax8UpdaterChouMan2(UserInfo.getUserId());
		ID batchprocessid = Database.executeBatch(batch);
		
		Test.stopTest();
		// ================== 更新処理 ================== 

		List<BookingEstimateItem__c> confirms2 = [select Id, TaxRate__c,UnitPrice__c,Total__c,ParentBookingItemRef__c,SpecialTax__c,UnitPriceDefKb__c from BookingEstimateItem__c 
			where TaxRate__c > 0 
			//and ParentBookingItemRef__c = null
			order by name];			
		system.debug(logginglevel.info, 'confirms2='+confirms2);
		for (BookingEstimateItem__c nw : confirms2) {
			BookingEstimateItem__c org = existMap.get(nw.id);
			system.assert(nw.TaxRate__c == 10, nw);
			system.assert(nw.Total__c == org.Total__c, nw);
		}
	}
	@isTest(SeeAllData=false)
	static void testCase3_2() {
		// 単価定義区分が２
		CommDefine__c comDef = TestCommon.createCommDefine();
		comDef.UnitPriceDefKb__c = 2;
		comdef.AutoCreateBookingEstFlg__c = false;
		update comDef; 
		// ２０１４・０３・３０開始４連泊予約情報を設定する
		Date startDt = Date.newInstance(2019,10,1);
		// プラン作成する
		// ご予約と見積もり作成
    	// 予約情報を作成する(4連泊予約情報を作成する)
    	List<Lead__c> leadInfos = TestCommon.createLead2IncRoomRate(startDt, 1, 3,null);
		List<BookingEstimateItem__c> confirms = [select Id, TaxRate__c,UnitPrice__c,Total__c from BookingEstimateItem__c where TaxRate__c > 0 order by name];	
system.debug(loggingLevel.info, 'confirms[BEG]='+confirms);
		map<id, BookingEstimateItem__c> existMap = new map<id, BookingEstimateItem__c>();
		for (BookingEstimateItem__c est : confirms) {
			existMap.put(est.id, est);
		}
		for(Lead__c ld : leadInfos){
			ld.Field298__c = 'チェックイン完';
		}
    	update leadInfos;
		// ================== 更新処理 ================== 
		Test.startTest();
		SalesTax8UpdaterChouMan2 m = new SalesTax8UpdaterChouMan2();
		DateTime nowTime = DateTime.now().addSeconds(10);
		// 起動ＣＲＯＮを設定する
		String timeStr = nowTime.format('yyyyMMddHHmmss');
		String yy = timeStr.substring(0,4);
		String mm = timeStr.substring(4,6);
		String dd = timeStr.substring(6,8);
		String hh = timeStr.substring(8,10);
		String ms = timeStr.substring(10,12);
		String ss = timeStr.substring(12,14);
		String sch = ss + ' ' +
		       ms + ' ' +
		       hh + ' ' +
		       dd + ' ' +
		       mm + ' ' +
		       ' ? ' + yy;
		String jobName = DateTime.now().format('yyyyMMddHHmmssSSS') + '|' + String.valueof(Crypto.getRandomLong());
		String jobId = system.schedule(jobName, sch, m);
	
		SalesTax8UpdaterChouMan2 batch = new SalesTax8UpdaterChouMan2(UserInfo.getUserId());
		ID batchprocessid = Database.executeBatch(batch);
		
		Test.stopTest();
		// ================== 更新処理 ================== 

		List<BookingEstimateItem__c> confirms2 = [select Id, TaxRate__c,UnitPrice__c,Total__c,ParentBookingItemRef__c,SpecialTax__c,UnitPriceDefKb__c from BookingEstimateItem__c 
			where TaxRate__c > 0 
			//and ParentBookingItemRef__c = null
			order by name];		
		system.debug(logginglevel.info, 'confirms2='+confirms2);
		for (BookingEstimateItem__c nw : confirms2) {
			BookingEstimateItem__c org = existMap.get(nw.id);
			system.assert(nw.TaxRate__c == 10, nw);
			system.assert(nw.Total__c == org.Total__c, nw);
		}
	}
	
	@isTest(SeeAllData=false)
	static void testCase3_3() {
		// 単価定義区分が3
		CommDefine__c comDef = TestCommon.createCommDefine();
		comDef.UnitPriceDefKb__c = 3;
		comdef.PDDetailsInputDefaultLines__c = 10;
		comdef.AutoCreateBookingEstFlg__c = false;
		update comDef; 
		// ２０１４・０３・３０開始４連泊予約情報を設定する
		Date startDt = Date.newInstance(2019,10,1);
		// プラン作成する
		// ご予約と見積もり作成
    	// 予約情報を作成する(4連泊予約情報を作成する)
    	List<Lead__c> leadInfos = TestCommon.createLead2IncRoomRate(startDt, 1, 3,null);
		List<BookingEstimateItem__c> confirms = [select Id, TaxRate__c,UnitPrice__c,Total__c from BookingEstimateItem__c 
			where TaxRate__c > 0 
			and ParentBookingItemRef__c = null
			order by name];	
system.debug(loggingLevel.info, 'confirms[BEG]='+confirms);
		map<id, BookingEstimateItem__c> existMap = new map<id, BookingEstimateItem__c>();
		for (BookingEstimateItem__c est : confirms) {
			existMap.put(est.id, est);
		}
		for(Lead__c ld : leadInfos){
			ld.Field298__c = 'チェックイン完';
		}
    	update leadInfos;
		// ================== 更新処理 ================== 
		Test.startTest();
		SalesTax8UpdaterChouMan2 m = new SalesTax8UpdaterChouMan2();
		DateTime nowTime = DateTime.now().addSeconds(10);
		// 起動ＣＲＯＮを設定する
		String timeStr = nowTime.format('yyyyMMddHHmmss');
		String yy = timeStr.substring(0,4);
		String mm = timeStr.substring(4,6);
		String dd = timeStr.substring(6,8);
		String hh = timeStr.substring(8,10);
		String ms = timeStr.substring(10,12);
		String ss = timeStr.substring(12,14);
		String sch = ss + ' ' +
		       ms + ' ' +
		       hh + ' ' +
		       dd + ' ' +
		       mm + ' ' +
		       ' ? ' + yy;
		String jobName = DateTime.now().format('yyyyMMddHHmmssSSS') + '|' + String.valueof(Crypto.getRandomLong());
		String jobId = system.schedule(jobName, sch, m);
	
		SalesTax8UpdaterChouMan2 batch = new SalesTax8UpdaterChouMan2(UserInfo.getUserId());
		ID batchprocessid = Database.executeBatch(batch);
		
		Test.stopTest();
		// ================== 更新処理 ================== 

		List<BookingEstimateItem__c> confirms2 = [select Id, TaxRate__c,UnitPrice__c,Total__c,ParentBookingItemRef__c,SpecialTax__c,UnitPriceDefKb__c from BookingEstimateItem__c 
			where TaxRate__c > 0 
			and ParentBookingItemRef__c = null
			order by name];	
		system.debug(logginglevel.info, 'confirms2='+confirms2);
		for (BookingEstimateItem__c nw : confirms2) {
			BookingEstimateItem__c org = existMap.get(nw.id);
			system.assert(nw.TaxRate__c == 10, nw);
			system.assert(nw.Total__c == org.Total__c, nw.Total__c+'='+org.Total__c);
		}
	}
	
	@isTest(SeeAllData=false)
	static void testCase3_4() {
		// 単価定義区分が4
		CommDefine__c comDef = TestCommon.createCommDefine();
		comDef.UnitPriceDefKb__c = 4;
		comdef.PDDetailsInputDefaultLines__c = 10;
		comdef.AutoCreateBookingEstFlg__c = false;
		update comDef; 
		// ２０１４・０３・３０開始４連泊予約情報を設定する
		Date startDt = Date.newInstance(2019,10,1);
		// プラン作成する
		// ご予約と見積もり作成
    	// 予約情報を作成する(4連泊予約情報を作成する)
    	List<Lead__c> leadInfos = TestCommon.createLead2IncRoomRate(startDt, 1, 3,null);
		List<BookingEstimateItem__c> confirms = [select Id, TaxRate__c,UnitPrice__c,Total__c from BookingEstimateItem__c 
			where TaxRate__c > 0 
			and ParentBookingItemRef__c = null
			order by name];	
system.debug(loggingLevel.info, 'confirms[BEG]='+confirms);
		map<id, BookingEstimateItem__c> existMap = new map<id, BookingEstimateItem__c>();
		for (BookingEstimateItem__c est : confirms) {
			existMap.put(est.id, est);
		}
		for(Lead__c ld : leadInfos){
			ld.Field298__c = 'チェックイン完';
		}
    	update leadInfos;
		// ================== 更新処理 ================== 
		Test.startTest();
		SalesTax8UpdaterChouMan2 m = new SalesTax8UpdaterChouMan2();
		DateTime nowTime = DateTime.now().addSeconds(10);
		// 起動ＣＲＯＮを設定する
		String timeStr = nowTime.format('yyyyMMddHHmmss');
		String yy = timeStr.substring(0,4);
		String mm = timeStr.substring(4,6);
		String dd = timeStr.substring(6,8);
		String hh = timeStr.substring(8,10);
		String ms = timeStr.substring(10,12);
		String ss = timeStr.substring(12,14);
		String sch = ss + ' ' +
		       ms + ' ' +
		       hh + ' ' +
		       dd + ' ' +
		       mm + ' ' +
		       ' ? ' + yy;
		String jobName = DateTime.now().format('yyyyMMddHHmmssSSS') + '|' + String.valueof(Crypto.getRandomLong());
		String jobId = system.schedule(jobName, sch, m);
	
		SalesTax8UpdaterChouMan2 batch = new SalesTax8UpdaterChouMan2(UserInfo.getUserId());
		ID batchprocessid = Database.executeBatch(batch);
		
		Test.stopTest();
		// ================== 更新処理 ================== 

		List<BookingEstimateItem__c> confirms2 = [select Id, TaxRate__c,UnitPrice__c,Total__c,ParentBookingItemRef__c,SpecialTax__c,UnitPriceDefKb__c from BookingEstimateItem__c 
			where TaxRate__c > 0 
			and ParentBookingItemRef__c = null
			order by name];	
		system.debug(logginglevel.info, 'confirms2='+confirms2);
		for (BookingEstimateItem__c nw : confirms2) {
			BookingEstimateItem__c org = existMap.get(nw.id);
			system.assert(nw.TaxRate__c == 10, nw);
			system.assert(nw.Total__c == org.Total__c, nw.Total__c+'='+org.Total__c);
		}
	}
	
	
	@isTest(SeeAllData=false)
	static void testCase4_1() {
		// 単価定義区分が4
		CommDefine__c comDef = TestCommon.createCommDefine();
		comDef.UnitPriceDefKb__c = 4;
		comdef.PDDetailsInputDefaultLines__c = 10;
		comdef.AutoCreateBookingEstFlg__c = false;
		update comDef; 
		// ２０１４・０３・３０開始４連泊予約情報を設定する
		Date startDt = Date.newInstance(2019,10,1);
		// プラン作成する
		// ご予約と見積もり作成
    	// 予約情報を作成する(4連泊予約情報を作成する)
    	List<Lead__c> leadInfos = TestCommon.createLead2IncRoomRate(startDt, 1, 3,createLocSingePlanIncRoom());
		List<BookingEstimateItem__c> confirms = [select Id, TaxRate__c,UnitPrice__c,Total__c from BookingEstimateItem__c 
			where TaxRate__c > 0 
			//and ParentBookingItemRef__c = null
			order by name];	
system.debug(loggingLevel.info, 'confirms[BEG]='+confirms);
		map<id, BookingEstimateItem__c> existMap = new map<id, BookingEstimateItem__c>();
		for (BookingEstimateItem__c est : confirms) {
			existMap.put(est.id, est);
		}
		for(Lead__c ld : leadInfos){
			ld.Field298__c = 'チェックイン完';
		}
    	update leadInfos;
		// ================== 更新処理 ================== 
		Test.startTest();
		SalesTax8UpdaterChouMan2 m = new SalesTax8UpdaterChouMan2();
		DateTime nowTime = DateTime.now().addSeconds(10);
		// 起動ＣＲＯＮを設定する
		String timeStr = nowTime.format('yyyyMMddHHmmss');
		String yy = timeStr.substring(0,4);
		String mm = timeStr.substring(4,6);
		String dd = timeStr.substring(6,8);
		String hh = timeStr.substring(8,10);
		String ms = timeStr.substring(10,12);
		String ss = timeStr.substring(12,14);
		String sch = ss + ' ' +
		       ms + ' ' +
		       hh + ' ' +
		       dd + ' ' +
		       mm + ' ' +
		       ' ? ' + yy;
		String jobName = DateTime.now().format('yyyyMMddHHmmssSSS') + '|' + String.valueof(Crypto.getRandomLong());
		String jobId = system.schedule(jobName, sch, m);
	
		SalesTax8UpdaterChouMan2 batch = new SalesTax8UpdaterChouMan2(UserInfo.getUserId());
		ID batchprocessid = Database.executeBatch(batch);
		
		Test.stopTest();
		// ================== 更新処理 ================== 

		List<BookingEstimateItem__c> confirms2 = [select Id, TaxRate__c,UnitPrice__c,Total__c,ParentBookingItemRef__c,SpecialTax__c,UnitPriceDefKb__c from BookingEstimateItem__c 
			where TaxRate__c > 0 
			//and ParentBookingItemRef__c = null
			order by name];	
		system.debug(logginglevel.info, 'confirms2='+confirms2);
		for (BookingEstimateItem__c nw : confirms2) {
			BookingEstimateItem__c org = existMap.get(nw.id);
			system.assert(nw.TaxRate__c == 10, nw);
			system.assert(nw.Total__c == org.Total__c, nw.Total__c+'='+org.Total__c);
		}
	}
	
	@isTest(SeeAllData=false)
	static void testCase5_1() {
		// プラン明細に室料が非存在場合
		// 単価定義区分が3
		CommDefine__c comDef = TestCommon.createCommDefine();
		comDef.UnitPriceDefKb__c = 3;
		comdef.PDDetailsInputDefaultLines__c = 10;
		comdef.AutoCreateBookingEstFlg__c = false;
		update comDef; 
		// ２０１４・０３・３０開始４連泊予約情報を設定する
		Date startDt = Date.newInstance(2019,10,1);
		// プラン作成する
		// ご予約と見積もり作成
    	// 予約情報を作成する(4連泊予約情報を作成する)
    	List<Lead__c> leadInfos = TestCommon.createLead2IncRoomRate(startDt, 1, 3,createLocPlanIncRoom());
		List<BookingEstimateItem__c> confirms = [select Id, TaxRate__c,UnitPrice__c,Total__c from BookingEstimateItem__c 
			where TaxRate__c > 0 
			//and ParentBookingItemRef__c = null
			order by name];	
system.debug(loggingLevel.info, 'confirms[BEG]='+confirms);
		map<id, BookingEstimateItem__c> existMap = new map<id, BookingEstimateItem__c>();
		for (BookingEstimateItem__c est : confirms) {
			existMap.put(est.id, est);
		}
		for(Lead__c ld : leadInfos){
			ld.Field298__c = 'チェックイン完';
		}
    	update leadInfos;
		// ================== 更新処理 ================== 
		Test.startTest();
		SalesTax8UpdaterChouMan2 m = new SalesTax8UpdaterChouMan2();
		DateTime nowTime = DateTime.now().addSeconds(10);
		// 起動ＣＲＯＮを設定する
		String timeStr = nowTime.format('yyyyMMddHHmmss');
		String yy = timeStr.substring(0,4);
		String mm = timeStr.substring(4,6);
		String dd = timeStr.substring(6,8);
		String hh = timeStr.substring(8,10);
		String ms = timeStr.substring(10,12);
		String ss = timeStr.substring(12,14);
		String sch = ss + ' ' +
		       ms + ' ' +
		       hh + ' ' +
		       dd + ' ' +
		       mm + ' ' +
		       ' ? ' + yy;
		String jobName = DateTime.now().format('yyyyMMddHHmmssSSS') + '|' + String.valueof(Crypto.getRandomLong());
		String jobId = system.schedule(jobName, sch, m);
	
		SalesTax8UpdaterChouMan2 batch = new SalesTax8UpdaterChouMan2(UserInfo.getUserId());
		ID batchprocessid = Database.executeBatch(batch);
		
		Test.stopTest();
		// ================== 更新処理 ================== 

		List<BookingEstimateItem__c> confirms2 = [select Id, TaxRate__c,UnitPrice__c,Total__c,ParentBookingItemRef__c,SpecialTax__c,UnitPriceDefKb__c from BookingEstimateItem__c 
			where TaxRate__c > 0 
			//and ParentBookingItemRef__c = null
			order by name];	
		system.debug(logginglevel.info, 'confirms2='+confirms2);
		List<BookingEstimateItem__c> books = [select id,refAccountMaster__c from BookingEstimateItem__c where ActionType__c ='プラン' and ParentBookingItemRef__c = null ];
		if (!books.isEmpty()) {
			books[0].TaxRate__c = 10;
			books[0].BatchProcessStatusDiv__c = '2';
			books[0].PlanDetailSyncInfo__c = books[0].refAccountMaster__c + ':' + 1000 + ':' + books[0].refAccountMaster__c + ':abc' + ';';
			update books[0]; 
		}
		SalesTax8UpdaterChouMan3 schedult = new SalesTax8UpdaterChouMan3(UserUtil.CurrentUserInfo.u.id);
        
		jobName = 'SalesTax8UpdaterChouMan3_' + DateTime.now().format('yyyyMMddHHmmssSSS') + '|' + String.valueof(Crypto.getRandomLong());
		jobId = system.schedule(jobName, sch, schedult);

		SalesTax8UpdaterChouMan3 batch1 = new SalesTax8UpdaterChouMan3();
        DataBase.executeBatch(batch1,50);
		List<Tran1__c> tran1s = [select id,Field7__c from Tran1__c where ActionType__c ='プラン' and ParentTran1Ref__c = null ];
		if (!tran1s.isEmpty()) {
			tran1s[0].TaxRate__c = 10;
			tran1s[0].BatchProcessStatusDiv__c = '2';
			tran1s[0].PlanDetailSyncInfo__c = tran1s[0].Field7__c + ':' + 1000 + ':' + tran1s[0].Field7__c + ':abc' + ';';
			update tran1s[0]; 
		}
		batch1 = new SalesTax8UpdaterChouMan3();
		batch1.currentStatus = 'tran1';
        DataBase.executeBatch(batch1,50);
		SalesTax8UpdaterChouMan2 batch3 = new SalesTax8UpdaterChouMan2(UserInfo.getUserId());
		batch3.currentStatus = '3';
		batchprocessid = Database.executeBatch(batch3);
	}
	// 2019/09/17 消費税は8%から10%に変更対応 WSQ BEGIN(総金額そのまま、単価を自動調整バッチ) END
	
	
    public static Plan__c createLocPlanIncRoom() {
    	JMST__c taxMst =  TestCommon.createTaxMst_8();
    	Plan__c plan = new Plan__c();
    	plan.name = 'テストプランデータ' + CommUtils.getRandom(5);
    	plan.PlanNo__c = CommUtils.getRandom(10);
    	plan.Price__c = 35000;
    	plan.PackageCode__c = 'PK_'+CommUtils.getRandom(10);
    	plan.JmstRef__c = taxMst.Id;
    	plan.ServiceRate__c = 10;
    	plan.PlanStartDateandtime__c = Date.newInstance(2000,1,1);
    	plan.Planclosedateandtime__c = Date.newInstance(2999,1,1);
    	insert plan;
        // 商品情報を作成する
        List<AccountMaster__c> productLst = TestCommon.createProductMst(3);
        AccountMaster__c roomProductItem = TestCommon.createRoomProductMst();
        ApexPages.StandardController contrl = new ApexPages.StandardController(plan);
        PlanProductSetup ctrl = new PlanProductSetup(contrl);
        List<PlanProductSetup.PlanDetail> planDeLst = ctrl.planDetailList;
        planDeLst[0].productNm = productLst[0].Name;
        planDeLst[0].sobj.AccountMasterRef__c = productLst[0].Id;
        planDeLst[0].sobj.Price__c = 10000;
        planDeLst[0].sobj.ServiceRate__c = 10;
        planDeLst[0].sobj.taxRate__c = taxMst.taxRate__c;
        planDeLst[1].productNm = productLst[1].Name;
        planDeLst[1].sobj.AccountMasterRef__c = productLst[1].Id;
        planDeLst[1].sobj.Price__c = 20000;
        planDeLst[1].sobj.ServiceRate__c = 10;
        planDeLst[1].sobj.taxRate__c = taxMst.taxRate__c;
        planDeLst[2].productNm = productLst[2].Name;
        planDeLst[2].sobj.AccountMasterRef__c = productLst[2].Id;
        planDeLst[2].sobj.Price__c = 5000;
        planDeLst[2].sobj.ServiceRate__c = 10;
        planDeLst[2].sobj.taxRate__c = taxMst.taxRate__c;
        ctrl.savePlanDetail();
    	return plan;
    }
    // 1明細のプラン
    public static Plan__c createLocSingePlanIncRoom() {
    	JMST__c taxMst =  TestCommon.createTaxMst_8();
    	Plan__c plan = new Plan__c();
    	plan.name = 'テストプランデータ' + CommUtils.getRandom(5);
    	plan.PlanNo__c = CommUtils.getRandom(10);
    	plan.Price__c = 10000;
    	plan.PackageCode__c = 'PK_'+CommUtils.getRandom(10);
    	plan.JmstRef__c = taxMst.Id;
    	plan.ServiceRate__c = 10;
    	plan.PlanStartDateandtime__c = Date.newInstance(2000,1,1);
    	plan.Planclosedateandtime__c = Date.newInstance(2999,1,1);
    	insert plan;
        // 商品情報を作成する
        List<AccountMaster__c> productLst = TestCommon.createProductMst(3);
        AccountMaster__c roomProductItem = TestCommon.createRoomProductMst();
        ApexPages.StandardController contrl = new ApexPages.StandardController(plan);
        PlanProductSetup ctrl = new PlanProductSetup(contrl);
        List<PlanProductSetup.PlanDetail> planDeLst = ctrl.planDetailList;
        planDeLst[0].productNm = productLst[0].Name;
        planDeLst[0].sobj.AccountMasterRef__c = productLst[0].Id;
        planDeLst[0].sobj.Price__c = 10000;
        planDeLst[0].sobj.ServiceRate__c = 10;
        planDeLst[0].sobj.taxRate__c = taxMst.taxRate__c;
        ctrl.savePlanDetail();
    	return plan;
    }
}