src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BankAccountNo__c</fullName>
        <label>口座番号</label>
        <length>7</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>BankBranchNameKana__c</fullName>
        <inlineHelpText>半角カタカナを入力してください</inlineHelpText>
        <label>支店名(カナ）</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankBranchName__c</fullName>
        <label>支店名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankBranchNumber__c</fullName>
        <label>支店番号</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankName__c</fullName>
        <label>金融機関名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankNumber__c</fullName>
        <label>金融機関番号</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DepositsType__c</fullName>
        <label>預金種目</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>普通</fullName>
                </value>
                <value>
                    <fullName>当座</fullName>
                </value>
                <value>
                    <fullName>貯蓄</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TransferChargeKbn__c</fullName>
        <inlineHelpText>振込には所定の手数料がかかります
ご依頼人さま：振込金額と手数料をご指定の出金口座から引き落とします。
お受取人さま：振込金額から手数料を除いた金額がお受取人さまに入金されます。</inlineHelpText>
        <label>振込手数料負担先</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>先方負担</fullName>
                </value>
                <value>
                    <fullName>自社負担</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ShopAccountInfo__c.object
<CustomObject>
    <fields>
        <fullName>AccountRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>口座情報</relationshipLabel>
        <relationshipName>AccountRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AccountTypeLst__c</fullName>
        <label>口座種別</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>買掛支払</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BankAccountNo__c</fullName>
        <label>口座番号</label>
        <length>7</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>BankBranchNameKana__c</fullName>
        <inlineHelpText>半角カタカナを入力してください</inlineHelpText>
        <label>支店名(カナ）</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankBranchName__c</fullName>
        <label>支店名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankBranchNumber__c</fullName>
        <label>支店番号</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankName__c</fullName>
        <label>金融機関名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankNumber__c</fullName>
        <label>金融機関番号</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DepositsType__c</fullName>
        <label>預金種目</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>普通</fullName>
                </value>
                <value>
                    <fullName>当座</fullName>
                </value>
                <value>
                    <fullName>貯蓄</fullName>
                </value>
                <value>
                    <fullName>その他</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RequestUserCode__c</fullName>
        <label>委託者コード</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestUserName__c</fullName>
        <inlineHelpText>半角カタカナを入力してください</inlineHelpText>
        <label>委託者名(名義人)</label>
        <length>40</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ShopInfoRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>店舗情報</label>
        <referenceTo>ShopInformation__c</referenceTo>
        <relationshipLabel>店舗口座情報</relationshipLabel>
        <relationshipName>KozaShopInfoRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransferChargeKbn__c</fullName>
        <label>振込手数料負担先</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>先方負担</fullName>
                </value>
                <value>
                    <fullName>自社負担</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>口座情報</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ShopInformation__c.object
<CustomObject>
    <description>Shoppers</description>
    <fields>
        <fullName>ShopCode__c</fullName>
        <externalId>true</externalId>
        <label>店舗コード</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>店舗情報</label>
    <nameField>
        <label>店舗名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ShopCode__c</fullName>
        <description>従業員所属店舗の店舗コードを指定可能、複数店舗を兼務の場合、カンマで複数店舗コードを一括設定可能
例：複数店舗兼務：01,02,03　→店舗01,02,03兼務になる、デフォルト所属店舗：01
デフォルト所属店舗を指定したい場合、店舗コードの後ろに、「:1」を指定すると、デフォルト店舗を指定可能
例：複数店舗兼務、店舗02はデフォルト所属店舗の場合、下記様に定義可能
-&gt;01,02:1,03</description>
        <inlineHelpText>従業員所属店舗の店舗コードを指定可能、複数店舗を兼務の場合、カンマで複数店舗コードを一括設定可能
例：複数店舗兼務：01,02,03　→店舗01,02,03兼務になる、デフォルト所属店舗：01
デフォルト所属店舗を指定したい場合、店舗コードの後ろに、「:1」を指定すると、デフォルト店舗を指定可能
例：複数店舗兼務、店舗02はデフォルト所属店舗の場合、下記様に定義可能
-&gt;01,02:1,03</inlineHelpText>
        <label>店舗コード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/InfoOutputProcessCtrlTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class InfoOutputProcessCtrlTest {

	// 店舗あり
    static testMethod void Case1() {
    	// 店舗作成
    	ShopInformation__c shop = TestCommon.createShopInfo();
    	// 取引先
    	Account account = TestCommon.createNormalAccount();
		// 口座情報の作成
		String shopAccLocalName = ShopAccountInfo__c.sObjectType.getDescribe().getName();
        List<RecordType> rts = [SELECT Id,Name FROM RecordType WHERE SobjectType  = :shopAccLocalName];
        String kouzaIds = createShopAccount(5,account,rts,shop.id);
		
		User loginUser = [select id, ShopCode__c from user where id = :UserInfo.getUserId()];
        loginUser.ShopCode__c = shop.shopcode__c;
        update loginUser;
        
		ApexPages.currentPage().getParameters().put('rIds',kouzaIds);
		InfoOutputProcessCtrl ctrl = new InfoOutputProcessCtrl();
		Pagereference page = ctrl.generalKouzaInfo();
		System.assert(page.getUrl().contains('rid'),page.getUrl());
    }

    // 店舗なし
    static testMethod void Case2() {
    	// 取引先
    	Account account = TestCommon.createNormalAccount();
		// 口座情報の作成
		String shopAccLocalName = ShopAccountInfo__c.sObjectType.getDescribe().getName();
        List<RecordType> rts = [SELECT Id,Name FROM RecordType WHERE SobjectType  = :shopAccLocalName];
        String kouzaIds = createShopAccount(5,account,rts,null);
		
		User loginUser = [select id, ShopCode__c from user where id = :UserInfo.getUserId()];
        loginUser.ShopCode__c = null;
        update loginUser;
		ApexPages.currentPage().getParameters().put('rIds',kouzaIds);
		InfoOutputProcessCtrl ctrl = new InfoOutputProcessCtrl();
		Pagereference page = ctrl.generalKouzaInfo();
		System.assert(page.getUrl().contains('rid'),page.getUrl());
    }
    
    public static String createShopAccount(Integer size,account acc,List<RecordType> recs, id shopid) {
		List<ShopAccountInfo__c> saLst = new List<ShopAccountInfo__c>();
		for (Integer i= 0; i<size; i++) {
			for (RecordType rectype : recs) {
				ShopAccountInfo__c dsa = new ShopAccountInfo__c(
					BankNumber__c = CommUtils.getRandom(4),
					BankBranchNumber__c = CommUtils.getRandom(3),         
				    DepositsType__c = '普通',
				    BankAccountNo__c = CommUtils.getRandom(7),
				    BankName__c = '住友銀行' + CommUtils.getRandom(10),
				    BankBranchName__c = '目黒支店' + CommUtils.getRandom(10),
				    BankBranchNameKana__c = 'してんバンゴの確認',
				    RequestUserName__c = 'ｶﾏﾙｷ' + CommUtils.getRandom(10),
				    TransferChargeKbn__c = '先方負担',
				    RequestUserCode__c = 'REQ_'+CommUtils.getRandom(6),
				    AccountTypeLst__c = '買掛入金',
				    ShopInfoRef__c = shopid,
					AccountRef__c = acc.id,
					recordTypeId = rectype.id
				);
				saLst.add(dsa);
			}
		}
		insert saLst;
		String kouzaIds = '';
		for(ShopAccountInfo__c info : saLst){
			kouzaIds += info.Id + ',';
		}
		return kouzaIds;
	}
    
    
}