src/objects/BookingTimeTable__c.object
<CustomObject>
    <description>Booking for Hall and resource, Visual Time Schedule</description>
    <fields>
        <fullName>Checkinday__c</fullName>
        <label>到着日</label>
        <type>Date</type>
    </fields>
    <label>タイムテーブル</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>タイムテーブル#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Field1__c</fullName>
        <label>コメント</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead__c.object
<CustomObject>
    <description>Booking sheet with record type</description>
    <fields>
        <fullName>CancelBool__c</fullName>
        <formula>If (ISPICKVAL( ReservedStatus__c , &quot;キャンセル&quot;) || ISPICKVAL( ReservedStatus__c , &quot;NO SHOW&quot;) || ISPICKVAL( ReservedStatus__c , &quot;削除&quot;) ,1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>予約ステータスがキャンセルであれば1でなければ0を返す</inlineHelpText>
        <label>CancelBool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Field15__c</fullName>
        <label>コンパニオン[洋]</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Field2__c</fullName>
        <inlineHelpText>予約発生元[流通経路 RM用語 Channel]を選択してください。
当館ご利用の経緯を選択してください。</inlineHelpText>
        <label>予約チャネル</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>電話</fullName>
                </value>
                <value>
                    <fullName>FAX</fullName>
                </value>
                <value>
                    <fullName>自社サイト</fullName>
                </value>
                <value>
                    <fullName>自社サイト[English]</fullName>
                </value>
                <value>
                    <fullName>自社サイト[China]</fullName>
                </value>
                <value>
                    <fullName>自社サイト[Korea]</fullName>
                </value>
                <value>
                    <fullName>自社サイト[Thailand]</fullName>
                </value>
                <value>
                    <fullName>AGT[JTB]</fullName>
                </value>
                <value>
                    <fullName>AGT[KNT]</fullName>
                </value>
                <value>
                    <fullName>AGT[NTA]</fullName>
                </value>
                <value>
                    <fullName>AGT[小田急トラベル]</fullName>
                </value>
                <value>
                    <fullName>AGT[相鉄観光]</fullName>
                </value>
                <value>
                    <fullName>AGT[一休]</fullName>
                </value>
                <value>
                    <fullName>AGT[らくだ]</fullName>
                </value>
                <value>
                    <fullName>AGT[じゃらん]</fullName>
                </value>
                <value>
                    <fullName>AGT[楽天]</fullName>
                </value>
                <value>
                    <fullName>AGT[るるぶ]</fullName>
                </value>
                <value>
                    <fullName>AGT[トクー]</fullName>
                </value>
                <value>
                    <fullName>AGT[ゆこゆこ]</fullName>
                </value>
                <value>
                    <fullName>AGT[リロクラブ]</fullName>
                </value>
                <value>
                    <fullName>AGT[ウェルボックス]</fullName>
                </value>
                <value>
                    <fullName>AGT[ベネフィットワン]</fullName>
                </value>
                <value>
                    <fullName>AGT[リゾートソリューション]</fullName>
                </value>
                <value>
                    <fullName>AGT[ベストリザーブ・宿ぷらざ]</fullName>
                </value>
                <value>
                    <fullName>AGT[e-hotel]</fullName>
                </value>
                <value>
                    <fullName>AGT[マル得]</fullName>
                </value>
                <value>
                    <fullName>AGT[お宿NET]</fullName>
                </value>
                <value>
                    <fullName>AGT[ANA]</fullName>
                </value>
                <value>
                    <fullName>AGT[HIS]</fullName>
                </value>
                <value>
                    <fullName>AGT[expedia]</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LeadIndexRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>予約インデックス</label>
        <referenceTo>LeadIndex__c</referenceTo>
        <relationshipLabel>ご予約</relationshipLabel>
        <relationshipName>LeadIndexRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nights__c</fullName>
        <formula>IF ( ISPICKVAL(ReservedType__c, &quot;泊 素&quot;) || ISPICKVAL(ReservedType__c, &quot;泊 ２食&quot;) || ISPICKVAL(ReservedType__c, &quot;泊 朝半&quot;) || ISPICKVAL(ReservedType__c, &quot;泊 夕半&quot;) || ( DATEVALUE(EntryTime__c) &lt;&gt; DATEVALUE(Departure__c) &amp;&amp; (Femails__c + StayPersons__c + Mans__c) &lt;&gt; 0 ) || ( DATEVALUE(EntryTime__c) &lt;&gt; DATEVALUE(Departure__c) &amp;&amp; CONTAINS(Name, &quot;の方&quot;) &amp;&amp; (Femails__c + StayPersons__c + Mans__c) &lt;&gt; 0 ), 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>宿泊予約の判断は、まず予約タイプ、到着日と出発日かつ予約人数、到着日と出発日かつ予約人数かつ&quot;の方&quot;となる</inlineHelpText>
        <label>Nights</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Relcontact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>お客様</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ご予約</relationshipLabel>
        <relationshipName>reservetg85</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReservedType__c</fullName>
        <inlineHelpText>ご予約のときのタイプを指定してください。</inlineHelpText>
        <label>予約タイプ</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>昼 賑</fullName>
                    <color>#0B6FCE</color>
                    <label>昼 賑</label>
                </value>
                <value>
                    <fullName>夕 賑</fullName>
                    <color>#78C953</color>
                    <label>夕 賑</label>
                </value>
                <value>
                    <fullName>昼 部屋</fullName>
                    <color>#E27001</color>
                    <label>昼 部屋</label>
                </value>
                <value>
                    <fullName>夕 部屋</fullName>
                    <color>#A845DC</color>
                    <label>夕 部屋</label>
                </value>
                <value>
                    <fullName>泊 素</fullName>
                    <color>#F3D904</color>
                    <label>泊 素</label>
                </value>
                <value>
                    <fullName>泊 朝半</fullName>
                    <color>#66E9BD</color>
                    <label>泊 朝半</label>
                </value>
                <value>
                    <fullName>泊 昼半</fullName>
                </value>
                <value>
                    <fullName>泊 夕半</fullName>
                    <color>#0B24BE</color>
                    <label>泊 夕半</label>
                </value>
                <value>
                    <fullName>泊 ２食</fullName>
                    <color>#A53711</color>
                    <label>泊 ２食</label>
                </value>
                <value>
                    <fullName>泊 ２食 朝昼</fullName>
                </value>
                <value>
                    <fullName>泊 ２食 昼夕</fullName>
                </value>
                <value>
                    <fullName>泊 ３食</fullName>
                </value>
                <value>
                    <fullName>団体 夕</fullName>
                    <color>#419249</color>
                    <label>団体 夕</label>
                </value>
                <value>
                    <fullName>団体 昼</fullName>
                    <color>#B6E32E</color>
                    <label>団体 昼</label>
                </value>
                <value>
                    <fullName>婚礼</fullName>
                </value>
                <value>
                    <fullName>昼 特企</fullName>
                    <color>#8F6429</color>
                    <label>昼 特企</label>
                </value>
                <value>
                    <fullName>お弁当 取りに参ります！</fullName>
                </value>
                <value>
                    <fullName>お弁当 持って行きます！</fullName>
                </value>
                <value>
                    <fullName>宴会</fullName>
                </value>
                <value>
                    <fullName>ケータリング</fullName>
                </value>
                <value>
                    <fullName>会議</fullName>
                </value>
                <value>
                    <fullName>法事</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>セグメント</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>通常料金</fullName>
                </value>
                <value>
                    <fullName>自社プラン</fullName>
                </value>
                <value>
                    <fullName>特別料金</fullName>
                </value>
                <value>
                    <fullName>WEB個人</fullName>
                </value>
                <value>
                    <fullName>AGT個人</fullName>
                </value>
                <value>
                    <fullName>海外個人</fullName>
                </value>
                <value>
                    <fullName>コンプ</fullName>
                </value>
                <value>
                    <fullName>ダイレクト団体</fullName>
                </value>
                <value>
                    <fullName>AGT団体</fullName>
                </value>
                <value>
                    <fullName>修学旅行</fullName>
                </value>
                <value>
                    <fullName>募集団体</fullName>
                </value>
                <value>
                    <fullName>海外団体</fullName>
                </value>
                <value>
                    <fullName>挙式列席者</fullName>
                </value>
                <value>
                    <fullName>個人</fullName>
                </value>
                <value>
                    <fullName>団体</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StayPersons__c</fullName>
        <defaultValue>$Setup.CommDefine__c.BookingMansDef__c +  $Setup.CommDefine__c.BookingFemailsDef__c +
$Setup.CommDefine__c.BookingChildrenDef__c</defaultValue>
        <label>予約人数</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ご予約</label>
    <nameField>
        <label>予約名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Yadochou__c.object
<CustomObject>
    <description>Guest Book Header</description>
    <fields>
        <fullName>Field11__c</fullName>
        <formula>Field1__r.Rroom__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>御部屋名</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field15__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>顧客</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>宿帳</relationshipLabel>
        <relationshipName>guestbookkAF4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ご予約</label>
        <referenceTo>Lead__c</referenceTo>
        <relationshipLabel>宿帳</relationshipLabel>
        <relationshipName>Yadouchou8DYp</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>宿帳</label>
    <nameField>
        <label>宿帳名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CashPdfBulkPrintCtrl.cls
public with sharing class CashPdfBulkPrintCtrl extends CommBaseCtrl{
	public list<Yadochou__c> yadoList {get;set;} // 宿帳
	public Yadochou__c yadoNew {get;set;} // 宿帳
	public BookingTimeTable__c selectDate{get; private set;} // 日期
	public List<String> shopCode{get; set;} //店铺
	public Integer cancelFlg = CommConst.LEAD_ST_CANCEL_FLG;
	public String isShowMoneyUrlInfo{get; private set;} // 全画面から金額表示する・しないパラメータ情報を格納
	//public Boolean conFirmFlg {get; set;} // 记忆check
	// 初期値设定
    public CashPdfBulkPrintCtrl(){
    	selectDate = new BookingTimeTable__c();
    	yadoNew = new Yadochou__c();
    	// 获取店铺和时间
    	shopCode = new List<String>();
    	// ルームインジケータ画面から金額表示する、しないフラグを格納する[]
    	if (ApexPages.currentPage().getParameters().containsKey('smy')) isShowMoneyUrlInfo = '&smy=1';
    	else isShowMoneyUrlInfo = '';
    	String branchShopNm = ApexPages.currentPage().getParameters().get('spcd');
        if (!CommUtils.isBlank(branchShopNm)) shopCode.addAll(CommUtils.nullToBlank(branchShopNm).split(','));
    	String workDateStr = ApexPages.currentPage().getParameters().get('cardDate');
    	Date workDate = CommUtils.isBlank(workDateStr) ? Date.today() : CommUtils.stringToDate(workDateStr);
    	selectDate.Checkinday__c = workDate;
    	String queryNewStr = ' select Id,Name,Field11__c,Field15__c,Field15__r.Name,Field1__c,Field1__r.Name,Field1__r.StayPersons__c,Field1__r.LeadIndexRef__r.EntryDate__c,Field1__r.LeadIndexRef__r.DepartureDate__c,Field1__r.LeadIndexRef__r.Nights__c,Field1__r.Field2__c,Field1__r.ReservedType__c,Field1__r.Segment__c,Field1__r.Relcontact__r.Name,Field1__r.Relcontact__c from Yadochou__c where Field1__r.CancelBool__c != :cancelFlg ';
    	if (!shopCode.isEmpty()) queryNewStr += ' AND (Field1__r.Rroom__r.ShopInfoRef__r.ShopCode__c  =:shopCode or Field1__r.refTypeOfRooms__r.ShopInfoRef__r.ShopCode__c  =:shopCode) ' ;
    	if(selectDate.Checkinday__c != null) queryNewStr += ' AND DAY_ONLY(convertTimezone(Field1__r.EntryTime__c)) = :workDate ' ;
		queryNewStr += ' Order By Field1__r.Rroom__r.Seq__c,Field1__r.LeadIndexRef__c, Field1__r.LeadIndexSubId__c, Field1__r.RoomGroupNo__c'; 
		yadoList = DataBase.query(queryNewStr);
		getyadoLayoutInfo();
    	getRoomType();
    	
		// DBから設定情報を取得する
		/*
		conFirmFlg = false;
		map<string,string> userConfigMap = UserConfigCompCtrl.getKrepConfig(userId, '');
		String configSwapFlgKey = UserConfigCompCtrl.KREP_SUBTYPE.YADOFLG.name();
		String configSwapFlgVal = '';
		if (userConfigMap.containsKey(configSwapFlgKey)) configSwapFlgVal = CommUtils.nullToBlank(userConfigMap.get(configSwapFlgKey));
		if (!CommUtils.isBlank(configSwapFlgVal)) conFirmFlg = Boolean.valueOf(configSwapFlgVal);
		*/
    }
    // 获取对应房型
    public List<SelectOption> RoomTypeLst{get; private set;}
    public String RoomTypeNm{get; set;}
    private void getRoomType() {
    	roomTypeNm = '';
    	RoomTypeLst = new List<SelectOption>();
    	String RTqueryStr = ' select id,name from TypeOfRooms__c ';
    	if (!shopCode.isEmpty()) RTqueryStr +=' where ShopInfoRef__r.ShopCode__c =: shopCode ';
    	list<TypeOfRooms__c> rooms = DataBase.query(RTqueryStr);
    	for(TypeOfRooms__c RT : rooms){
    		RoomTypeLst.add(new SelectOption(RT.id, RT.name));
    	}
    }
	public void gotoDate() {
		// 获取数据集
		//yadoList = new list<Yadochou__c>();
		Date workDate = selectDate.Checkinday__c;
		String strWorkDate = null;
		Id contactId = yadoNew.Field15__c;
		String queryStr =' Select Id,Name,Field11__c,Field15__c,Field15__r.Name,Field1__c,Field1__r.Name,Field1__r.StayPersons__c,Field1__r.LeadIndexRef__r.EntryDate__c,Field1__r.LeadIndexRef__r.DepartureDate__c,Field1__r.LeadIndexRef__r.Nights__c,Field1__r.Field2__c,Field1__r.ReservedType__c,Field1__r.Segment__c,Field1__r.Relcontact__r.Name,Field1__r.Relcontact__c from Yadochou__c where Field1__r.CancelBool__c != :cancelFlg ' ;
		if (!shopCode.isEmpty()) queryStr += ' AND (Field1__r.Rroom__r.ShopInfoRef__r.ShopCode__c  =:shopCode or Field1__r.refTypeOfRooms__r.ShopInfoRef__r.ShopCode__c  =:shopCode) ' ;
		if(!CommUtils.isBlank(RoomTypeNm)) queryStr += ' AND Field1__r.refTypeOfRooms__c =:RoomTypeNm ' ;
		if(workDate != null) {
			// 20万件以上制限対応済み場合、「EntryDateKey__c」項目で到着日として検索を行う
			if (DataFixManagerUtils.isLeadKeyFixed()) {
				strWorkDate = CommUtils.dateToYYYYMMDD(workDate);
				queryStr += ' AND Field1__r.EntryDateKey__c = :strWorkDate ' ;
			} else {
				queryStr += ' AND DAY_ONLY(convertTimezone(Field1__r.EntryTime__c)) = :workDate ' ;
			}
		}
		if(!CommUtils.isBlank(yadoNew.Field15__c)) queryStr += ' AND (Field15__c =:contactId or Field1__r.Relcontact__c = :contactId)' ;
		queryStr += ' Order By Field1__r.Rroom__r.Seq__c,Field1__r.LeadIndexRef__c, Field1__r.LeadIndexSubId__c, Field1__r.RoomGroupNo__c'; 
		yadoList = DataBase.query(queryStr);
		getyadoLayoutInfo();
	}
	// 数据处理
    private void getyadoLayoutInfo(){
		yadoItemLst = new List<ItemInfo>();
		for(Yadochou__c yado : yadoList) {
			ItemInfo layoutItem = new ItemInfo(yado);
			yadoItemLst.add(layoutItem);
		}
		yadoItemJson = JSON.serialize(yadoItemLst);
    }
    public List<ItemInfo> yadoItemLst{get;set;}
    public String yadoItemJson{get;set;}
    public class ItemInfo{
    	// 页面的check
    	public Boolean checkFlg{get; set;}
    	// 页面的宿帐
    	public String yadoId{get; set;}
    	// 页面的顾客
    	public String conId{get; set;}
    	public String conName{get; set;}
    	// 页面的予约
    	public String leadId{get; set;}
    	public String leadName{get; set;}
    	// 页面的予约人数
    	public Decimal leadStayPersons{get; set;}
    	// 页面的予约到着日/出发日
    	public String leadEntry{get; set;}
    	public String leadDepar{get; set;}
    	// 页面的予约泊数
    	public String leadStayNight{get; set;}
    	// 页面的予約チャネル
    	public String leadChannel{get; set;}
    	// 页面的予約タイプ
    	public String leadReservedType{get; set;}
    	// 页面的予约セグメント
    	public String leadSegment{get; set;}
    	// 页面的房间
    	public String roomName{get; set;}
    	
    	public ItemInfo(Yadochou__c yd){
    		checkFlg = true;
    		yadoId = yd.Id;
    		conId = CommUtils.nullToBlank(yd.Field15__c);
    		conName = CommUtils.nullToBlank(yd.Field15__r.Name);
    		if(CommUtils.isBlank(conId)){
    			conId = CommUtils.nullToBlank(yd.Field1__r.Relcontact__c);
    			conName = CommUtils.nullToBlank(yd.Field1__r.Relcontact__r.Name);
    		}
    		leadId = CommUtils.nullToBlank(yd.Field1__c);
    		leadName = CommUtils.nullToBlank(yd.Field1__r.Name);
    		roomName = CommUtils.nullToBlank(yd.Field11__c);
    		leadStayPersons = CommUtils.nullToZero(yd.Field1__r.StayPersons__c);
    		leadEntry = CommUtils.nullToBlank(yd.Field1__r.LeadIndexRef__r.EntryDate__c == null ? '' : yd.Field1__r.LeadIndexRef__r.EntryDate__c.format());
    		leadDepar = CommUtils.nullToBlank(yd.Field1__r.LeadIndexRef__r.DepartureDate__c == null ? '' : yd.Field1__r.LeadIndexRef__r.DepartureDate__c.format());
    		leadStayNight = CommUtils.nullToBlank(yd.Field1__r.LeadIndexRef__r.Nights__c);
    		leadChannel = CommUtils.nullToBlank(yd.Field1__r.Field2__c);
    		leadReservedType = CommUtils.nullToBlank(yd.Field1__r.ReservedType__c);
    		leadSegment = CommUtils.nullToBlank(yd.Field1__r.Segment__c);
    	}
    }
	// 2020/02/29 レジカードのロゴを出力した部屋の「店舗情報」対応 BY zyz BEGIN
	public String switchCode{get{return CommConst.APPOTION_CARREGISTSWITCH_DIV_CODE;}set;}
	public String shopLst{get{
	    	Boolean CashLogoFlg = CommConst.APPOTION_CARREGISTER_LOGO_FLG;
	    	String shopLstStr ='';
	    	if(CashLogoFlg) {
	    		List<String> ShopInfoLst = ShopInfoUtil.getCanSelectShopLst(UserInfo.getUserId());
	    		if(!ShopInfoLst.isEmpty() && ShopInfoLst.size() > 1) shopLstStr = JSON.serialize(ShopInfoLst);
	    	}
	    	return shopLstStr;
	}}
	// 2020/02/29 レジカードのロゴを出力した部屋の「店舗情報」対応 BY zyz END
}