src/objects/CommDefine__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BillInputSwitchCode__c</fullName>
        <defaultValue>&quot;1&quot;</defaultValue>
        <description>会計編集画面レイアウト切替制御パラメータ</description>
        <inlineHelpText>会計編集画面レイアウト切替制御パラメータ
1: 元会計編集画面（デフォルト値） 
2: 新会計メニュー</inlineHelpText>
        <label>会計編集のレイアウト制御コード</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>共通定義</label>
</CustomObject>

src/classes/BillInputSwitchCtrl.cls
public with sharing class BillInputSwitchCtrl {

	private final Map<String,String> paramMap;
	public static final String BILL_LAYOUT_CODE_1 = '1';
	public static final String BILL_LAYOUT_CODE_2 = '2';
	
	public BillInputSwitchCtrl(ApexPages.StandardController controller){
		paramMap = ApexPages.currentPage().getParameters();
	}
	public Pagereference redirect() {
		String layoutNo = CommDefine__c.getOrgDefaults().BillInputSwitchCode__c;
		PageReference customPage = new PageReference('/apex/BillInput');
		if (layoutNo == BILL_LAYOUT_CODE_2) customPage = new PageReference('/apex/BillSimpleInput');
		customPage.getParameters().putAll(paramMap);
		customPage.setRedirect(true);
		return customPage;
	}
	// 現在は新会計レイアウトに設定する場合
	public static Boolean isNewAccountLayout() {
		return (CommDefine__c.getOrgDefaults().BillInputSwitchCode__c == BILL_LAYOUT_CODE_2);
	}
}