src/objects/CommDefine__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ApplicationFormPDFSwitchCode__c</fullName>
        <defaultValue>&quot;2&quot;</defaultValue>
        <inlineHelpText>予約確認書表示レイアウト制御
1: 予約確認書（旧)（B５）
2: 予約確認書（新)（A４）(デフォルト)
4: 入寮確認書 (A4)
5: 錦水館専用 (A4)
6: カスタム用</inlineHelpText>
        <label>予約確認書コード</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>共通定義</label>
</CustomObject>

src/objects/Lead__c.object
<CustomObject>
    <description>Booking sheet with record type</description>
    <fields>
        <fullName>CancelBool__c</fullName>
        <formula>If (ISPICKVAL( ReservedStatus__c , &quot;キャンセル&quot;) || ISPICKVAL( ReservedStatus__c , &quot;NO SHOW&quot;) || ISPICKVAL( ReservedStatus__c , &quot;削除&quot;) ,1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>予約ステータスがキャンセルであれば1でなければ0を返す</inlineHelpText>
        <label>CancelBool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LeadIndexRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>予約インデックス</label>
        <referenceTo>LeadIndex__c</referenceTo>
        <relationshipLabel>ご予約</relationshipLabel>
        <relationshipName>LeadIndexRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rroom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>本予約にお部屋を一つ割当てください。
お部屋を2つ以上割り当てる場合は、同一お客様名の新規予約を作成してください。</inlineHelpText>
        <label>部屋</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Room__c.TypeRoomRef__c</field>
                <operation>equals</operation>
                <valueField>$Source.refTypeOfRooms__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>ご予約</relationshipLabel>
        <relationshipName>R00N10000000rzUoEAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ご予約</label>
    <nameField>
        <label>予約名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApplicationFormPDFSwitch.cls
/**
* 予約確認書切替コントロール
* 2015/11/05 予約確認書レイアウト５を追加する
**/
global with sharing class ApplicationFormPDFSwitch {
	
	private static final String LAYOUT_CODE = CommUtils.nullToBlank(CommDefine__c.getOrgDefaults().ApplicationFormPDFSwitchCode__c);
	
	public ApplicationFormPDFSwitch(ApexPages.StandardController controller){
		paramMap = ApexPages.currentPage().getParameters();
	}

	// ログインユーザの通貨設定情報
	webservice static String getApplicationFormPdfComment() {
		// 店舗コード
		String shopCode = UserUtil.CurrentUser.ShopCode__c;
		// コメント欄情報を取得する
		String xmlConfigName = 'ApplicationFormPdfConfig';
		ApplicationFormPDFExt1.XmlConfigInfo oXmlInfo = new ApplicationFormPDFExt1.XmlConfigInfo(CommXmlUtils.parseXmlDoc(xmlConfigName, shopCode));
		return  oXmlInfo.bComment;
	}
	webservice static String getApplicationFormPdfCommentAndRooms(String leadIndex) {
		return getApplicationFormPdfComment() + ':' + isHaveAssigedRoom(leadIndex);
	}
	// 指定の予約インデックスのIDにより、部屋アサインされている予約が存在チェツクを行う
	webservice static integer isHaveAssigedRoom(String leadIndex) {
		// 2015/12/09 錦水館機能対応 BEGIN
		if (LAYOUT_CODE == '5') return 0;
		// 2015/12/09 錦水館機能対応 END
		List<Lead__c> leads = [
						select id from lead__c 
						where Rroom__c != null 
							And CancelBool__c != :CommConst.LEAD_ST_CANCEL_FLG 
							And LeadIndexRef__c = :leadIndex
						limit 1];
		return leads.size();
	}
	private final Map<String,String> paramMap;
	private static final Map<String, String> pageMap;
	static {
		pageMap = new Map<String,String>{
			// 2021/07/30 #JP10785 by zy BEGIN
			// 予約確認書のカスタマイズ
			'6'=>'ApplicationFormPDF_6',
			// 2021/07/30 #JP10785 by zy END
			// 新レイアウト（A4）[錦水館]
			'5'=>'ApplicationFormPDF_5',
			// 新レイアウト（A4）[入寮確認書]
			'4'=>'ApplicationFormPDF_4',
			// 新レイアウト（B5）
			//'3'=>'ApplicationFormPDF_3',
			// 新レイアウト（A4）
			'2'=>'ApplicationFormPDF_2',
			// JINYA会社DefaultPDF専用ページ
			'1'=>'ApplicationFormPDF'};
	}
	
	// ページ遷移制御処理
	public PageReference redirect() {
		// 予約確認書レイアウトコード
		PageReference customPage = new PageReference( pageMap.get(LAYOUT_CODE) == null ? '/apex/ApplicationFormPDF_2' : '/apex/' + pageMap.get(LAYOUT_CODE) );
		paramMap.put('lc',LAYOUT_CODE);
		customPage.getParameters().putAll(paramMap);
		customPage.setRedirect(true);
		return customPage;
	}
}