src/objects/CommDefine__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>UserBeginTimeCalMethodType__c</fullName>
        <defaultValue>&quot;切り上げ&quot;</defaultValue>
        <label>勤怠_出勤時間端数処理</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserBeginTimeUnit__c</fullName>
        <defaultValue>&quot;30分&quot;</defaultValue>
        <label>勤怠_出勤時間単位</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserCalMethodType__c</fullName>
        <defaultValue>&quot;切り捨て&quot;</defaultValue>
        <label>勤怠_退勤端数処理</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserOutRestCalMethodType__c</fullName>
        <defaultValue>&quot;切り捨て&quot;</defaultValue>
        <label>勤怠_外出時間端数処理</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserOutRestTimeUnit__c</fullName>
        <defaultValue>&quot;30分&quot;</defaultValue>
        <label>勤怠_外出時間単位</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserRestCalMethodType__c</fullName>
        <defaultValue>&quot;切り上げ&quot;</defaultValue>
        <label>勤怠_入室時間端数処理</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserRestTimeUnit__c</fullName>
        <defaultValue>&quot;30分&quot;</defaultValue>
        <label>勤怠_入室時間単位</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserTimeUnit__c</fullName>
        <defaultValue>&quot;30分&quot;</defaultValue>
        <label>勤怠_退勤時間単位</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>共通定義</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BeginTimeCalMethodType__c</fullName>
        <label>出勤時間端数処理</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>切り捨て</fullName>
                </value>
                <value>
                    <fullName>切り上げ</fullName>
                </value>
                <value>
                    <fullName>四捨五入</fullName>
                    <default>true</default>
                    <label>四捨五入</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BeginTimeUnit__c</fullName>
        <label>出勤時間単位</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1分</fullName>
                </value>
                <value>
                    <fullName>5分</fullName>
                    <default>true</default>
                    <label>5分</label>
                </value>
                <value>
                    <fullName>10分</fullName>
                </value>
                <value>
                    <fullName>15分</fullName>
                </value>
                <value>
                    <fullName>20分</fullName>
                </value>
                <value>
                    <fullName>30分</fullName>
                </value>
                <value>
                    <fullName>60分</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CalMethodType__c</fullName>
        <label>退勤端数処理</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>切り捨て</fullName>
                </value>
                <value>
                    <fullName>切り上げ</fullName>
                </value>
                <value>
                    <fullName>四捨五入</fullName>
                    <default>true</default>
                    <label>四捨五入</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DefaultShopCode__c</fullName>
        <label>デイフォル店舗コード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OutRestCalMethodType__c</fullName>
        <label>外出時間端数処理</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>切り捨て</fullName>
                </value>
                <value>
                    <fullName>切り上げ</fullName>
                </value>
                <value>
                    <fullName>四捨五入</fullName>
                    <default>true</default>
                    <label>四捨五入</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OutRestTimeUnit__c</fullName>
        <label>外出時間単位</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1分</fullName>
                </value>
                <value>
                    <fullName>5分</fullName>
                    <default>true</default>
                    <label>5分</label>
                </value>
                <value>
                    <fullName>10分</fullName>
                </value>
                <value>
                    <fullName>15分</fullName>
                </value>
                <value>
                    <fullName>20分</fullName>
                </value>
                <value>
                    <fullName>30分</fullName>
                </value>
                <value>
                    <fullName>60分</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RestCalMethodType__c</fullName>
        <label>入室時間端数処理</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>切り捨て</fullName>
                </value>
                <value>
                    <fullName>切り上げ</fullName>
                </value>
                <value>
                    <fullName>四捨五入</fullName>
                    <default>true</default>
                    <label>四捨五入</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RestTimeUnit__c</fullName>
        <label>入室時間単位</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1分</fullName>
                </value>
                <value>
                    <fullName>5分</fullName>
                    <default>true</default>
                    <label>5分</label>
                </value>
                <value>
                    <fullName>10分</fullName>
                </value>
                <value>
                    <fullName>15分</fullName>
                </value>
                <value>
                    <fullName>20分</fullName>
                </value>
                <value>
                    <fullName>30分</fullName>
                </value>
                <value>
                    <fullName>60分</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ShopCode__c</fullName>
        <description>従業員所属店舗の店舗コードを指定可能、複数店舗を兼務の場合、カンマで複数店舗コードを一括設定可能
例：複数店舗兼務：01,02,03　→店舗01,02,03兼務になる、デフォルト所属店舗：01
デフォルト所属店舗を指定したい場合、店舗コードの後ろに、「:1」を指定すると、デフォルト店舗を指定可能
例：複数店舗兼務、店舗02はデフォルト所属店舗の場合、下記様に定義可能
-&gt;01,02:1,03</description>
        <inlineHelpText>従業員所属店舗の店舗コードを指定可能、複数店舗を兼務の場合、カンマで複数店舗コードを一括設定可能
例：複数店舗兼務：01,02,03　→店舗01,02,03兼務になる、デフォルト所属店舗：01
デフォルト所属店舗を指定したい場合、店舗コードの後ろに、「:1」を指定すると、デフォルト店舗を指定可能
例：複数店舗兼務、店舗02はデフォルト所属店舗の場合、下記様に定義可能
-&gt;01,02:1,03</inlineHelpText>
        <label>店舗コード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TimeUnit__c</fullName>
        <label>退勤時間単位</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1分</fullName>
                </value>
                <value>
                    <fullName>5分</fullName>
                    <default>true</default>
                    <label>5分</label>
                </value>
                <value>
                    <fullName>10分</fullName>
                </value>
                <value>
                    <fullName>15分</fullName>
                </value>
                <value>
                    <fullName>20分</fullName>
                </value>
                <value>
                    <fullName>30分</fullName>
                </value>
                <value>
                    <fullName>60分</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/UserTriggerProcess.cls
public with sharing class UserTriggerProcess {
	/******************
	* ユーザの時間単位、端数処理を設定
	* 2017/02/24 復活されたユーザでもデフォルト値を現在の値で自動更新されることを対応する
	******************/
	//public void autoSetupUserTimeUnit(User[] newLst){
	public void autoSetupUserTimeUnit(User[] newLst, User[] oldLst, CommConst.TriggerMethod act){
		// 2017/02/24 復活されたユーザでもデフォルト値を現在の値で自動更新されることを対応する BEGIN
		List<User> targetLst = new List<User>();
		if (act == CommConst.TriggerMethod.IsInsert) {
			for (User userItem : newLst) {
				targetLst.add(userItem);	
			}
		} else if (act == CommConst.TriggerMethod.IsUpdate) {
			Integer maxLen = newLst.size();
			for (Integer i =0; i<maxLen; i++) {
				User nw = newLst[i];
				User od = oldLst[i];
				if (nw.IsActive != od.IsActive && nw.IsActive) {
					targetLst.add(nw);
				}
			}
		}
		if (targetLst.isEmpty()) return;
		//for (User userItem : newLst) {
		for (User userItem : targetLst) {
		// 2017/02/24 復活されたユーザでもデフォルト値を現在の値で自動更新されることを対応する END
			//出勤時間単位  30分
			userItem.BeginTimeUnit__c = CommDefine__c.getOrgDefaults().UserBeginTimeUnit__c;
			//出勤時間端数処理  切り上げ
			userItem.BeginTimeCalMethodType__c = CommDefine__c.getOrgDefaults().UserBeginTimeCalMethodType__c;
		    //退勤時間単位 30分
			userItem.TimeUnit__c = CommDefine__c.getOrgDefaults().UserTimeUnit__c;
			//退勤時間端数処理 切り捨て
			userItem.CalMethodType__c = CommDefine__c.getOrgDefaults().UserCalMethodType__c;
			//入室時間単位 30分
			userItem.RestTimeUnit__c = CommDefine__c.getOrgDefaults().UserRestTimeUnit__c;
			//入室時間端数処理 切り上げ
			userItem.RestCalMethodType__c = CommDefine__c.getOrgDefaults().UserRestCalMethodType__c;
			//外出時間単位 30分
			userItem.OutRestTimeUnit__c = CommDefine__c.getOrgDefaults().UserOutRestTimeUnit__c;
			//外出時間端数処理 切り捨て
			userItem.OutRestCalMethodType__c = CommDefine__c.getOrgDefaults().UserOutRestCalMethodType__c;
		}
	}
	/******************
	* ユーザ情報の店舗コードは複数定義を対応するため、
	******************/
	public void autoSetupDefaultShopCode(User[] newLst, User[] oldLst){
		for (Integer i = 0; i < newLst.size(); i++) {
			User nw = newLst[i];
			User od = oldLst == null ? null : oldLst[i];
			// 2019/02/28 デフォルト店舗コードの設定条件を変更する WSQ BEGIN
			//if (od == null || nw.ShopCode__c != od.ShopCode__c) {
			if (od == null || nw.ShopCode__c != od.ShopCode__c ||
				(CommUtils.isBlank(nw.DefaultShopCode__c) && !CommUtils.isBlank(nw.ShopCode__c))) {
			// 2019/02/28 デフォルト店舗コードの設定条件を変更する WSQ END
				UserUtil.UserShopInfo uInfo = new UserUtil.UserShopInfo(nw);
				nw.DefaultShopCode__c = uInfo.defaultShopCode;
			}
		}
	}
}