src/objects/CommDefine__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CustomTimeReport__c</fullName>
        <defaultValue>&quot;$$0040 カスタム時間割&quot;</defaultValue>
        <label>レポート_カスタム時間割</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tier4Report__c</fullName>
        <defaultValue>&quot;$0011 客室割当状況 - 昼と夕 [Tier4]&quot;</defaultValue>
        <label>レポート_客室割当状況 - 昼と夕 [Tier4]</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>共通定義</label>
</CustomObject>

src/objects/Lead__c.object
<CustomObject>
    <description>Booking sheet with record type</description>
    <fields>
        <fullName>ReservedDate821__c</fullName>
        <formula>DATEVALUE(EntryTime__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ReservedDate</label>
        <type>Date</type>
    </fields>
    <label>ご予約</label>
    <nameField>
        <label>予約名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomButtonCon.cls
public with sharing class CustomButtonCon {

    //予約オブジェクトのカスタムボタンで使用
    private ID RmAssNoonID;//客室割当状況 - 昼と夕
    private ID ScheduleID;//炭酸泉エステ時間割予約表

    private Date rsvdate;

    public CustomButtonCon(ApexPages.StandardController controller){
        RmAssNoonID = [select Id, name from Report where Name = :CommDefine__c.getOrgDefaults().Tier4Report__c limit 1].Id;
        ScheduleID = [select Id, name from Report where Name = :CommDefine__c.getOrgDefaults().CustomTimeReport__c limit 1].Id;

        rsvdate = [select Id, ReservedDate821__c from Lead__c where Id =: controller.getId() limit 1].ReservedDate821__c;
    }

    public PageReference ViewRmAssNoon(){
        //String wdate = String.valueOf(rsvdate.year())+'/'+String.valueOf(rsvdate.month())+'/'+String.valueOf(rsvdate.day());
        String wdate = DateTime.newinstance(rsvdate.year(),rsvdate.month(),rsvdate.day()).format(CommBaseCtrl.getDateFormat());
        return (new PageReference('/'+String.valueOf(RmAssNoonID)+'?colDt_s='+wdate+'&colDt_e='+wdate));
    }

    public PageReference ViewSchedule(){
        //String wdate = String.valueOf(rsvdate.year())+'/'+String.valueOf(rsvdate.month())+'/'+String.valueOf(rsvdate.day());
        String wdate = DateTime.newinstance(rsvdate.year(),rsvdate.month(),rsvdate.day()).format(CommBaseCtrl.getDateFormat());
        return (new PageReference('/'+String.valueOf(ScheduleID)+'?colDt_s='+wdate+'&colDt_e='+wdate));
    }

}