src/objects/ExpoUser__c.object
<CustomObject>
    <fields>
        <fullName>ChangePasswordFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <description>パスワードが忘れる場合、該当フラグを変更される</description>
        <label>パスワードリセットフラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PwdResetSendMalFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <description>該当項目を変更されると、自動ユーザへ送信を行う</description>
        <label>パスワードリセット送信</label>
        <type>Checkbox</type>
    </fields>
    <label>Expoユーザ</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ExpoForgotpwdCtrl.cls
public with sharing class ExpoForgotpwdCtrl{
	public ExpoForgotpwdCtrl(){
		username = '';
		userNotExistFlg = false;
	}
	public String userName{get; set;}
	public Boolean userNotExistFlg{get; set;}
	// userNameCheck是否存在
	public void userNameCheck(){
		userNotExistFlg = ExpoHelperUtil.getThisUserNameInfo(userName).isEmpty();
	}
	public void updateData(){
		List<ExpoUser__c> expoUserLst = ExpoHelperUtil.getThisUserNameInfo(userName);
		for(ExpoUser__c s : expoUserLst){
			s.ChangePasswordFlg__c = true;
			s.PwdResetSendMalFlg__c = !s.PwdResetSendMalFlg__c;
		}
		if(!expoUserLst.isEmpty()){
			userNotExistFlg = true;
			update expoUserLst;
		} else userNotExistFlg = false;
	}
	// 2018/10/06 システムロゴ情報を取得する WSQ BEGIN
	public String getLogoUrl() {
		return ExpoNoAuthHelp.getLogoUrl();
	}
	// 2018/10/06 システムロゴ情報を取得する WSQ END
}