src/objects/ExpoHrInfo__c.object
<CustomObject>
    <fields>
        <fullName>ExpoAccSkillLst__c</fullName>
        <label>スキル(経理)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SD01</fullName>
                    <label>簿記を活かす</label>
                </value>
                <value>
                    <fullName>SD02</fullName>
                    <label>仕訳業務</label>
                </value>
                <value>
                    <fullName>SD03</fullName>
                    <label>決算業務</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExpoDayWorkBegTimeLst__c</fullName>
        <label>始業時間</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>G_DayWorkTime</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExpoDayWorkEndTimeLst__c</fullName>
        <label>終業時間</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>G_DayWorkTime</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExpoDispatchScopeLst__c</fullName>
        <description>EXPOの人材情報利用</description>
        <label>派遣期間</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KA01</fullName>
                    <label>長期(3ヶ月以上)</label>
                </value>
                <value>
                    <fullName>KA02</fullName>
                    <label>短期</label>
                </value>
                <value>
                    <fullName>KA03</fullName>
                    <label>期間限定</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExpoEngSkillLst__c</fullName>
        <label>スキル(英語)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SB01</fullName>
                    <label>基礎レベル</label>
                </value>
                <value>
                    <fullName>SB02</fullName>
                    <label>日常会話レベル</label>
                </value>
                <value>
                    <fullName>SB03</fullName>
                    <label>ビジネス会話レベル</label>
                </value>
                <value>
                    <fullName>SB04</fullName>
                    <label>ネイティブレベル</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExpoHrOtherLst__c</fullName>
        <label>その他</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SF01</fullName>
                    <label>未経験者歓迎</label>
                </value>
                <value>
                    <fullName>SF02</fullName>
                    <label>実務経験者</label>
                </value>
                <value>
                    <fullName>SF03</fullName>
                    <label>寮社宅あり</label>
                </value>
                <value>
                    <fullName>SF04</fullName>
                    <label>食事手当あり</label>
                </value>
                <value>
                    <fullName>SF05</fullName>
                    <label>夜勤なし</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExpoLicSkillLst__c</fullName>
        <label>免許・資格</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SE01</fullName>
                    <label>レストランサービス技能士</label>
                </value>
                <value>
                    <fullName>SE02</fullName>
                    <label>自動車免許</label>
                </value>
                <value>
                    <fullName>SE03</fullName>
                    <label>サービス接遇</label>
                </value>
                <value>
                    <fullName>SE04</fullName>
                    <label>ボイラー取扱技能</label>
                </value>
                <value>
                    <fullName>SE05</fullName>
                    <label>マナー・プロトコール</label>
                </value>
                <value>
                    <fullName>SE06</fullName>
                    <label>ブライダルプランナー</label>
                </value>
                <value>
                    <fullName>SE07</fullName>
                    <label>接客サービスマナー</label>
                </value>
                <value>
                    <fullName>SE08</fullName>
                    <label>販売士（リテールマーケティング）</label>
                </value>
                <value>
                    <fullName>SE09</fullName>
                    <label>調理師免許</label>
                </value>
                <value>
                    <fullName>SE10</fullName>
                    <label>美容師免許</label>
                </value>
                <value>
                    <fullName>SE11</fullName>
                    <label>調理補助</label>
                </value>
                <value>
                    <fullName>SE12</fullName>
                    <label>栄養士免許</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExpoMaxPayLst__c</fullName>
        <label>給料（上限）</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>WorkPayType__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>G_PayRankLst</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExpoMinPayLst__c</fullName>
        <label>給料（下限）</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>WorkPayType__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>G_PayRankLst</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExpoOaSkillLst__c</fullName>
        <label>スキル(OA)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SA01</fullName>
                    <label>Wordを活かす</label>
                </value>
                <value>
                    <fullName>SA02</fullName>
                    <label>Excel 基礎レベル</label>
                </value>
                <value>
                    <fullName>SA03</fullName>
                    <label>Excel 実務レベル</label>
                </value>
                <value>
                    <fullName>SA04</fullName>
                    <label>Excel 上級レベル</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExpoOrgInfoRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expo組織情報</label>
        <referenceTo>ExpoOrgInfo__c</referenceTo>
        <relationshipLabel>EXPO人材属性情報</relationshipLabel>
        <relationshipName>ExpoOrgInfoRefForHr</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExpoOthLangSkillLst__c</fullName>
        <label>スキル(その他語)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SC01</fullName>
                    <label>中国語</label>
                </value>
                <value>
                    <fullName>SC02</fullName>
                    <label>韓国語</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExpoOvertimeWorkHourLst__c</fullName>
        <label>残業時間</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KC01</fullName>
                    <label>残業なし</label>
                </value>
                <value>
                    <fullName>KC02</fullName>
                    <label>残業20時間未満</label>
                </value>
                <value>
                    <fullName>KC03</fullName>
                    <label>残業20時間以上</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExpoWeekWorkDaysLst__c</fullName>
        <label>勤務日数</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KB01</fullName>
                    <label>週5日勤務</label>
                </value>
                <value>
                    <fullName>KB02</fullName>
                    <label>週4日勤務</label>
                </value>
                <value>
                    <fullName>KB03</fullName>
                    <label>週3日以下勤務</label>
                </value>
                <value>
                    <fullName>KB04</fullName>
                    <label>自由シフト</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkPayType__c</fullName>
        <label>給料の支払い方式</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>日給</label>
                </value>
                <value>
                    <fullName>0</fullName>
                    <label>時給</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>EXPO人材属性情報</label>
    <nameField>
        <displayFormat>HR{YYYY}-{0000}</displayFormat>
        <label>人材No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ExpoHrInfoEditCtrl.cls
public with sharing class ExpoHrInfoEditCtrl extends ExpoCommBaseCtrl{
    private static final String APPOTION_NAMESPACE = CommConst.APPOTION_NAMESPACE;
	public String parentDsJson{get;set;} // 级联主DATA
	public String childDsJson{get;set;} // 级联子DATA1
	public String childDsJsons{get;set;} // 级联子DATA2
	public ExpoHrInfo__c accMaster{get;set;} //会计商品
	public ExpoHelperUtil.ExpoFieldInfo expo{get;set;}	// 返回数据
	public String dataId{get;set;}
	// *配置API必须小写* 固定标准必填字段
	private static final set<String> fieldReqSet = new set<String>{'name'};
	// *配置API必须小写* 固定只读字段
	private static final set<String> fieldRomSet = new set<String>{};
	// *配置API必须小写* 固定不显示字段
	private static final set<String> fieldNotSet = new set<String>{'id','expoorginforef__c'};
	// XML为空时,默认显示 版块Key
	private static List<String> defOrderLst = new List<String>{'0','1','2'}; // 版块顺序
	//private static map<String,String> defMap = new map<String,String>{'0' => '人材情報の詳細;2;Name,ExpoDayWorkBegTimeLst__c,ExpoDispatchScopeLst__c	,ExpoDayWorkEndTimeLst__c ,ExpoWeekWorkDaysLst__c ,ExpoOvertimeWorkHourLst__c ,WorkPayType__c ,$_blank_$ ,ExpoMinPayLst__c ,$_blank_$ ,ExpoMaxPayLst__c;','1' => 'スキル・経験;1;ExpoOaSkillLst__c::line,ExpoEngSkillLst__c::line,ExpoOthLangSkillLst__c::line, ExpoAccSkillLst__c::line,ExpoLicSkillLst__c::line,ExpoHrOtherLst__c::line;'};
	private static map<String,String> defMap = new map<String,String>{'0' => '人材情報の詳細;1;ExpoDispatchScopeLst__c,ExpoWeekWorkDaysLst__c,WorkPayType__c	,ExpoMinPayLst__c ,ExpoMaxPayLst__c ,ExpoOvertimeWorkHourLst__c ,ExpoDayWorkBegTimeLst__c ,ExpoDayWorkEndTimeLst__c ;','1' => 'スキル・経験;1;ExpoOaSkillLst__c,ExpoEngSkillLst__c,ExpoOthLangSkillLst__c, ExpoAccSkillLst__c,ExpoLicSkillLst__c,ExpoHrOtherLst__c;'};
	// DOUBLE类型的数据的格式
	public String getNumberFormat() {
		return CommUtils.getNumberFormat();
	}
	public ExpoHrInfoEditCtrl(){
		accMaster = new ExpoHrInfo__c();
	}
	public PageReference initAct() {
		// *****************************
		// 共通処理呼び出す
		// *****************************
		PageReference pg = checkLogin();
		if (pg != null) return pg;
		// *****************************
		// 実際の業務ロジック処理展開
		// *****************************
		
		// 获取ID
		dataId = Apexpages.currentpage().getparameters().get('Id');	
		// 页面显示的数据处理
		getExpoShopInfoXML();
		return null;
	}
	// 获取数据集
	public void getExpoShopInfoXML(){
		expo = ExpoHelperUtil.getExpoXML('HRINFOFIELDS', ExpoHrInfo__c.sObjectType, fieldReqSet, fieldRomSet, fieldNotSet);
		if(expo.custApiSet.isEmpty()){
			expo = ExpoHelperUtil.getExpoDef(defOrderLst, defMap, ExpoHrInfo__c.sObjectType, fieldReqSet, fieldRomSet, fieldNotSet);
		}
		// 级联字段特殊处理
		parentDsJson = childDsJson = '[]';
		if(expo.custApiSet.contains('workpaytype__c') && expo.custApiSet.contains('expominpaylst__c')){
			ExpoHelperUtil.KendoDataSourceAll kendo = ExpoHelperUtil.getDependentOptions(APPOTION_NAMESPACE + 'ExpoHrInfo__c', APPOTION_NAMESPACE + 'WorkPayType__c', APPOTION_NAMESPACE + 'ExpoMinPayLst__c');
			parentDsJson = JSON.serialize(kendo.parentKendoDs);
			childDsJson = JSON.serialize(kendo.childKendoDs);
			expo.custFieldInfoMap.get('workpaytype__c').fieldTyp = ExpoHelperUtil.API_TYPE.CPLST.name();
			expo.custFieldInfoMap.get('expominpaylst__c').fieldTyp = ExpoHelperUtil.API_TYPE.CPLST.name();
		}
		childDsJsons = '[]';
		if(expo.custApiSet.contains('workpaytype__c') && expo.custApiSet.contains('expomaxpaylst__c') ){
			ExpoHelperUtil.KendoDataSourceAll kendo = ExpoHelperUtil.getDependentOptions(APPOTION_NAMESPACE + 'ExpoHrInfo__c', APPOTION_NAMESPACE + 'WorkPayType__c', APPOTION_NAMESPACE + 'ExpoMaxPayLst__c');
			childDsJsons = JSON.serialize(kendo.childKendoDs);
			expo.custFieldInfoMap.get('expomaxpaylst__c').fieldTyp = ExpoHelperUtil.API_TYPE.CPLST.name();
		}
		if (!CommUtils.isBlank(dataId)){
			String queryStr = ' Select ';
			for(String api : expo.custApiSet) queryStr += api + ',' ;
			queryStr = queryStr.removeEnd(',');
			queryStr += ' From ExpoHrInfo__c Where Id =: dataId ';
			List<ExpoHrInfo__c> accMasterLst = DataBase.query(queryStr);
			if (!accMasterLst.isEmpty()) {
				accMaster = accMasterLst[0];
			}
			ExpoHelperUtil.setApiVal(accMaster, expo);
		}
	}
	// 参照字段のデータ取得する
	@remoteaction 
	public static List<ExpoHelperUtil.KendoDataSource> getRefDs(String ref,String ExpoInfoRef){
		String querySQL = 'select id,name ';
		querySQL += ' from ' + ref;
		if(!CommUtils.isBlank(ExpoInfoRef)) querySQL += ' where ExpoOrgInfoRef__c =: ExpoInfoRef order by name';
		List<ExpoHelperUtil.KendoDataSource> selectOptionDsLst = new List<ExpoHelperUtil.KendoDataSource>{new ExpoHelperUtil.KendoDataSource('', '')};
		for (Sobject s : Database.query(querySQL)) {
			String textStr = CommUtils.nullToBlank(s.get('id'));
			String valueStr = CommUtils.nullToBlank(s.get('name'));
			selectOptionDsLst.add(new ExpoHelperUtil.KendoDataSource(valueStr, textStr));
		}
		return selectOptionDsLst;
	}
	// 保存
	@remoteaction 
	public static String saveInfo(String dataId, String fieldJson, String expoOrgInfoRef){
		ExpoHrInfo__c accMasterItem = new ExpoHrInfo__c();
		if(!CommUtils.isBlank(expoOrgInfoRef)) accMasterItem.ExpoOrgInfoRef__c = expoOrgInfoRef;
		return ExpoHelperUtil.saveInfo(dataId, fieldJson, accMasterItem);
	}
}