src/objects/ExpoUser__c.object
<CustomObject>
    <fields>
        <fullName>AdministratorFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <label>管理者フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChangePasswordFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <description>パスワードが忘れる場合、該当フラグを変更される</description>
        <label>パスワードリセットフラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>メール</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ExpoOrgInfoRef__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>組織情報参照</description>
        <label>Expo組織情報</label>
        <referenceTo>ExpoOrgInfo__c</referenceTo>
        <relationshipLabel>Expoユーザ</relationshipLabel>
        <relationshipName>ExpoOrgInfoRefe</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <label>Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>ユーザ有効</inlineHelpText>
        <label>有効</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PassWord__c</fullName>
        <label>パスワード</label>
        <length>127</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>電話</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ShopCode__c</fullName>
        <label>店舗コード</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TokenId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>TokenId</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>例：name@yourcompany.com</inlineHelpText>
        <label>ユーザ名</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Expoユーザ</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ShopInformation__c.object
<CustomObject>
    <description>Shoppers</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>メール</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ExpoOrgInfoRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expo組織情報</label>
        <referenceTo>ExpoOrgInfo__c</referenceTo>
        <relationshipLabel>店舗情報</relationshipLabel>
        <relationshipName>ExpoOrgInfoRefs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <label>Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>電話</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ShopCode__c</fullName>
        <externalId>true</externalId>
        <label>店舗コード</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>店舗情報</label>
    <nameField>
        <label>店舗名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ShopCode__c</fullName>
        <description>従業員所属店舗の店舗コードを指定可能、複数店舗を兼務の場合、カンマで複数店舗コードを一括設定可能
例：複数店舗兼務：01,02,03　→店舗01,02,03兼務になる、デフォルト所属店舗：01
デフォルト所属店舗を指定したい場合、店舗コードの後ろに、「:1」を指定すると、デフォルト店舗を指定可能
例：複数店舗兼務、店舗02はデフォルト所属店舗の場合、下記様に定義可能
-&gt;01,02:1,03</description>
        <inlineHelpText>従業員所属店舗の店舗コードを指定可能、複数店舗を兼務の場合、カンマで複数店舗コードを一括設定可能
例：複数店舗兼務：01,02,03　→店舗01,02,03兼務になる、デフォルト所属店舗：01
デフォルト所属店舗を指定したい場合、店舗コードの後ろに、「:1」を指定すると、デフォルト店舗を指定可能
例：複数店舗兼務、店舗02はデフォルト所属店舗の場合、下記様に定義可能
-&gt;01,02:1,03</inlineHelpText>
        <label>店舗コード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ExpoUserEditCtrl.cls
public with sharing class ExpoUserEditCtrl extends ExpoCommBaseCtrl{
	public String parentDsJson{get;set;} // 级联主DATA
	public String childDsJson{get;set;} // 级联子DATA
	public ExpoHelperUtil.ExpoFieldInfo expo{get;set;} // 所有数据集
	public String dataId{get{ return CommUtils.nullToBlank( ApexPages.currentPage().getParameters().get('Id') ); }}
	// *配置API必须小写* 固定标准必填字段
	private static final set<String> fieldReqSet = new set<String>{'name','email__c','shopcode__c'};
	// *配置API必须小写* 固定只读字段
	private static set<String> fieldRomSet = new set<String>{'username__c'};
	// *配置API必须小写* 固定不显示字段
	private static set<String> fieldNotSet = new set<String>{'id','expoorginforef__c','tokenid__c','password__c','changepasswordflg__c','administratorflg__c'};
	// XML为空时,默认显示 版块Key
	private static List<String> defOrderLst = new List<String>{'0'}; // 版块顺序
	// Key=>版块Key,Val=>配置格式{ SECTION(TITLE);SECTION(列数);API1:LAB1,API2:LAB2,API3:LAB3...; }
	private static final map<String,String> defMap = new map<String,String>{'0' => '情報;1;UserName__c,Name,Email__c,Phone__c,Fax__c,ShopCode__c,isactive__c;'};
	public PageReference initAct() {
		// *****************************
		// 共通処理呼び出す
		// *****************************
		PageReference pg = checkLogin();
		if (pg != null) return pg;
		// *****************************
		// 実際の業務ロジック処理展開
		// *****************************
		// 页面显示的数据处理
		getExpoShopInfoXML();
		return null;
	}
	// 获取数据集
	public void getExpoShopInfoXML(){
		if(CommUtils.isBlank(dataId)) fieldRomSet.remove('username__c');
		expo = ExpoHelperUtil.getExpoXML('USERINFOFIELDS', ExpoUser__c.sObjectType, fieldReqSet, fieldRomSet, fieldNotSet);
		if(expo.custApiSet.isEmpty()){
			expo = ExpoHelperUtil.getExpoDef(defOrderLst, defMap, ExpoUser__c.sObjectType, fieldReqSet, fieldRomSet, fieldNotSet);
		}
		// 级联字段特殊处理
		/*parentDsJson = childDsJson = '[]';
		if(expo.custApiSet.contains('demomin__c') && expo.custApiSet.contains('democ__c') ){
			ExpoHelperUtil.KendoDataSourceAll kendo = ExpoHelperUtil.getDependentOptions('ExpoUser__c', 'DemoMin__c', 'DemoC__c');
			parentDsJson = JSON.serialize(kendo.parentKendoDs);
			childDsJson = JSON.serialize(kendo.childKendoDs);
			expo.custFieldInfoMap.get('demomin__c').fieldTyp = ExpoHelperUtil.API_TYPE.CPLST.name();
			expo.custFieldInfoMap.get('democ__c').fieldTyp = ExpoHelperUtil.API_TYPE.CPLST.name();
		}*/
		if(CommUtils.isBlank(dataId)){
			setShopCode(currentUser.ExpoOrgInfoRef__c);
			setIsactiveDefault();
			return;
		}
		expo.custApiSet.add('expoorginforef__c'); // 防止未查询
		String queryStr = ' Select ';
		// 合成有效api
		for(String api : expo.custApiSet) queryStr += api + ',' ;
		queryStr = queryStr.removeEnd(',');
		queryStr += ' From ExpoUser__c Where Id =: dataId ';
		List<ExpoUser__c> userLst = DataBase.query(queryStr);
		for(ExpoUser__c s : userLst){
			ExpoHelperUtil.setApiVal(s, expo);
		}
		setShopCode(userLst[0].ExpoOrgInfoRef__c);
	}
	
	private void setIsactiveDefault(){
		ExpoHelperUtil.FieldInfo field = expo.custFieldInfoMap.get('isactive__c');
		if(field != null) field.fieldVal = 'true';
	}
	
	private void setShopCode(String expoOrgInfoRef){
		// 店铺Code特殊处理
		if(expo.custFieldInfoMap.containsKey('shopcode__c')){
			ExpoHelperUtil.FieldInfo field = expo.custFieldInfoMap.get('shopcode__c');
			field.fieldLab = '店舗';
			field.fieldTyp = ExpoHelperUtil.API_TYPE.PLST.name();
			for(ShopInformation__c sp : [Select Id, Name, shopCode__c From ShopInformation__c where ExpoOrgInfoRef__c =: expoOrgInfoRef order by name]){
				field.fieldPLst.add(new SelectOption(CommUtils.nullToBlank(sp.shopCode__c), CommUtils.nullToBlank(sp.Name)));
			}
		}
	}
	// 参照字段のデータ取得する
	@remoteaction 
	public static List<ExpoHelperUtil.KendoDataSource> getRefDs(String ref){
		String querySQL = 'Select Id, Name From ' + ref;
		List<ExpoHelperUtil.KendoDataSource> kendoDs = new List<ExpoHelperUtil.KendoDataSource>{new ExpoHelperUtil.KendoDataSource('', '')};
		for (Sobject s : DataBase.query(querySQL)) {
			kendoDs.add(new ExpoHelperUtil.KendoDataSource(CommUtils.nullToBlank(s.get('Name')), CommUtils.nullToBlank(s.get('Id'))));
		}
		return kendoDs;
	}
	// 判断User重复
	@remoteaction 
	public static Boolean checkUserName(String userName){
		return ([Select Id From ExpoUser__c where UserName__c =:userName].isEmpty());
	}
	// 保存处理
	@remoteaction
	public static String saveInfo(String dataId, String fieldJson, String expoOrgInfoRef){
		ExpoUser__c user = new ExpoUser__c();
		if(CommUtils.isBlank(expoOrgInfoRef)) user.ExpoOrgInfoRef__c = expoOrgInfoRef;
		return ExpoHelperUtil.saveInfo(dataId, fieldJson, new ExpoUser__c(ExpoOrgInfoRef__c = expoOrgInfoRef));
	}
	// 2018/10/06 システムロゴ情報を取得する WSQ BEGIN
	public String getLogoUrl() {
		return ExpoNoAuthHelp.getLogoUrl();
	}
	// 2018/10/06 システムロゴ情報を取得する WSQ END
}