src/objects/InventoryInfo__c.object
<CustomObject>
    <fields>
        <fullName>AccountMasterRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会計商品</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipLabel>棚卸データ</relationshipLabel>
        <relationshipName>masterRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BatchDate__c</fullName>
        <label>棚卸データ同期日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StockDate__c</fullName>
        <label>棚卸日</label>
        <type>Date</type>
    </fields>
    <label>棚卸データ</label>
    <nameField>
        <displayFormat>II#{YYYYMMDD}-{00000000}</displayFormat>
        <label>棚卸No#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductOutStock__c.object
<CustomObject>
    <fields>
        <fullName>AccountMasterRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会計商品</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipLabel>ProductOutStock</relationshipLabel>
        <relationshipName>ProductOutStock</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsNotTarget__c</fullName>
        <defaultValue>false</defaultValue>
        <label>在庫集計対象外</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OutStockDate__c</fullName>
        <description>売上日・受注日の日付、YYYYMMDD</description>
        <externalId>true</externalId>
        <label>出庫日</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>商品出庫情報</label>
    <nameField>
        <displayFormat>POS-{000000000}</displayFormat>
        <label>商品出庫情報</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PurchaseDetail__c.object
<CustomObject>
    <fields>
        <fullName>AccountMasterRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会計商品</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipLabel>仕入明細</relationshipLabel>
        <relationshipName>AccountMasterRefLUWM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InStockDate__c</fullName>
        <description>仕入の日付、YYYYMMDD</description>
        <externalId>true</externalId>
        <label>入庫日</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsNotTarget__c</fullName>
        <defaultValue>false</defaultValue>
        <label>在庫集計対象外</label>
        <type>Checkbox</type>
    </fields>
    <label>仕入明細</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>仕入明細No#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BulkStocktakingLinkBatch.cls
/**
* 棚卸し同期バッチ機能2対応
* 該当バッチは【BulkStocktakingSyncBatch】経由で起動される
**/
public with sharing class BulkStocktakingLinkBatch implements Database.Batchable<Sobject>, Database.Stateful {
	// バッチ処理区分：INSTOCK 入力情報,OUSTOCK:出庫情報
	public enum BATCH_TYPE{INSTOCK,OUSTOCK}
	private String queryYmd;
	private BATCH_TYPE bType;
	// 2018/12/30 棚卸しバッチ起動できるように改善対応 by zy BEGIN
	// 処理対象
	public Set<String> processIdSet;
	// 2018/12/30 棚卸しバッチ起動できるように改善対応 by zy END
	// バッチインスタンス化
	// ymd:該当日付以前のデータの【集計対象外】フラグをONにする、書式：YYYYMMDD
	public BulkStocktakingLinkBatch(String ymd, BATCH_TYPE ptype) {
		queryYmd = ymd;
		bType = ptype;
	}

	// ***********************************
	// バッチ処理開始
	// ***********************************
	public Database.QueryLocator start(Database.BatchableContext BC){
		// 0件返却
		Date batchDate = CommUtils.stringtoDate(queryYmd);
		// 2018/12/30 棚卸しバッチ起動できるように改善対応 by zy BEGIN
		// 該当締日以前の在庫データ
		// String qstr = 'select id,AccountMasterRef__c,StockDate__c from InventoryInfo__c where BatchDate__c = :batchDate';
		String qstr = 'select id,AccountMasterRef__c,StockDate__c from InventoryInfo__c where AccountMasterRef__c = :processIdSet';
		// 2018/12/30 棚卸しバッチ起動できるように改善対応 by zy END
		return Database.getQueryLocator(qstr);
	}
	
	// ***********************************
	// バッチロジック処理開始
	// ***********************************
	public void execute(Database.BatchableContext BC, List<InventoryInfo__c> scope){
		Set<String> processIds = new set<String>();
		Map<String,String> invenDtMap = new Map<String,String>();
		Date maxDate = null;
		for (InventoryInfo__c inven : scope) {
			processIds.add(inven.AccountMasterRef__c);
			invenDtMap.put(inven.AccountMasterRef__c,dataToFormatString(inven.StockDate__c));
			// 棚卸日取得
			if (maxDate == null || maxDate < inven.StockDate__c) maxDate = inven.StockDate__c;
		}
		if (maxDate != null) queryYmd = dataToFormatString(maxDate);
		if (bType == BATCH_TYPE.INSTOCK) {
			String qstr = 'select id,AccountMasterRef__c,IsNotTarget__c,InStockDate__c from PurchaseDetail__c where InStockDate__c <= :queryYmd and IsNotTarget__c != true and AccountMasterRef__c in :processIds';
			List<PurchaseDetail__c> sobjects = Database.query(qstr);
			for (PurchaseDetail__c s : sobjects) {
				String accId = CommUtils.nullToBlank(s.AccountMasterRef__c);
				// 入庫日
				String dtStr = s.InStockDate__c;
				if (invenDtMap.containsKey(accId)) {
					String dtFormat = invenDtMap.get(accId);
					if (dtFormat >= dtStr) s.IsNotTarget__c = true;
				}
			}
			if (!sobjects.isEmpty()) update sobjects;
		}  else if (bType == BATCH_TYPE.OUSTOCK) {
			String qstr = 'select id,AccountMasterRef__c,IsNotTarget__c,OutStockDate__c from ProductOutStock__c where OutStockDate__c <= :queryYmd and IsNotTarget__c != true and AccountMasterRef__c in :processIds';
			List<ProductOutStock__c> sobjects = Database.query(qstr);
			for (ProductOutStock__c s : sobjects) {
				String accId = CommUtils.nullToBlank(s.AccountMasterRef__c);
				// 出庫日
				String dtStr = s.OutStockDate__c;
				if (invenDtMap.containsKey(accId)) {
					String dtFormat = invenDtMap.get(accId);
					// 2018/12/15 商品在庫、指定棚卸日以前のデータ対象外設定不能　by zy BEGIN
					if (dtFormat >= dtStr) s.IsNotTarget__c = true;
					// 2018/12/15 商品在庫、指定棚卸日以前のデータ対象外設定不能　by zy END
				}
			}
			if (!sobjects.isEmpty()) update sobjects;
		}
	}
	
	// ***********************************
	// バッチ終了処理開始
	// ***********************************
	public void finish(Database.BatchableContext BC){
		
	}
	private string dataToFormatString(Date curDt){
		if (curDt == null) return '';
		return (DateTime.newInstance(curDt.year(),curDt.month(),curDt.day())).format('yyyyMMdd');
	}
}