src/objects/Lead__c.object
<CustomObject>
    <description>Booking sheet with record type</description>
    <fields>
        <fullName>Comment3__c</fullName>
        <inlineHelpText>ご予約以降に、考慮すべき重要なことがら</inlineHelpText>
        <label>特記事項</label>
        <length>2048</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>EntryTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <inlineHelpText>お客様が来られる予定の日付を選択してください。</inlineHelpText>
        <label>到着日</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Field298__c</fullName>
        <inlineHelpText>チェックインへ変更することで、予約見積明細の内容が会計計上されます、連泊のお客様のときも日ごとにチェックインステータスへ変更する必要がありますのでご注意が必要です。</inlineHelpText>
        <label>お客様ステータス</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>チェックイン完</fullName>
                </value>
                <value>
                    <fullName>チェックアウト完</fullName>
                </value>
                <value>
                    <fullName>外出中</fullName>
                </value>
                <value>
                    <fullName>入浴中</fullName>
                </value>
                <value>
                    <fullName>滞在中</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field2__c</fullName>
        <inlineHelpText>予約発生元[流通経路 RM用語 Channel]を選択してください。
当館ご利用の経緯を選択してください。</inlineHelpText>
        <label>予約チャネル</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>電話</fullName>
                </value>
                <value>
                    <fullName>FAX</fullName>
                </value>
                <value>
                    <fullName>自社サイト</fullName>
                </value>
                <value>
                    <fullName>自社サイト[English]</fullName>
                </value>
                <value>
                    <fullName>自社サイト[China]</fullName>
                </value>
                <value>
                    <fullName>自社サイト[Korea]</fullName>
                </value>
                <value>
                    <fullName>自社サイト[Thailand]</fullName>
                </value>
                <value>
                    <fullName>AGT[JTB]</fullName>
                </value>
                <value>
                    <fullName>AGT[KNT]</fullName>
                </value>
                <value>
                    <fullName>AGT[NTA]</fullName>
                </value>
                <value>
                    <fullName>AGT[小田急トラベル]</fullName>
                </value>
                <value>
                    <fullName>AGT[相鉄観光]</fullName>
                </value>
                <value>
                    <fullName>AGT[一休]</fullName>
                </value>
                <value>
                    <fullName>AGT[らくだ]</fullName>
                </value>
                <value>
                    <fullName>AGT[じゃらん]</fullName>
                </value>
                <value>
                    <fullName>AGT[楽天]</fullName>
                </value>
                <value>
                    <fullName>AGT[るるぶ]</fullName>
                </value>
                <value>
                    <fullName>AGT[トクー]</fullName>
                </value>
                <value>
                    <fullName>AGT[ゆこゆこ]</fullName>
                </value>
                <value>
                    <fullName>AGT[リロクラブ]</fullName>
                </value>
                <value>
                    <fullName>AGT[ウェルボックス]</fullName>
                </value>
                <value>
                    <fullName>AGT[ベネフィットワン]</fullName>
                </value>
                <value>
                    <fullName>AGT[リゾートソリューション]</fullName>
                </value>
                <value>
                    <fullName>AGT[ベストリザーブ・宿ぷらざ]</fullName>
                </value>
                <value>
                    <fullName>AGT[e-hotel]</fullName>
                </value>
                <value>
                    <fullName>AGT[マル得]</fullName>
                </value>
                <value>
                    <fullName>AGT[お宿NET]</fullName>
                </value>
                <value>
                    <fullName>AGT[ANA]</fullName>
                </value>
                <value>
                    <fullName>AGT[HIS]</fullName>
                </value>
                <value>
                    <fullName>AGT[expedia]</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field310__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>プラン</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>非公開に設定されたプランを選択できません。</errorMessage>
            <filterItems>
                <field>Plan__c.IsClosed__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>ご予約</relationshipLabel>
        <relationshipName>RSVfkhF</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field3__c</fullName>
        <inlineHelpText>出発の時間を選択してください。</inlineHelpText>
        <label>出発時刻</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>11:00</fullName>
                </value>
                <value>
                    <fullName>11:10</fullName>
                </value>
                <value>
                    <fullName>11:20</fullName>
                </value>
                <value>
                    <fullName>11:30</fullName>
                </value>
                <value>
                    <fullName>11:40</fullName>
                </value>
                <value>
                    <fullName>11:50</fullName>
                </value>
                <value>
                    <fullName>12:00</fullName>
                </value>
                <value>
                    <fullName>12:10</fullName>
                </value>
                <value>
                    <fullName>12:20</fullName>
                </value>
                <value>
                    <fullName>12:30</fullName>
                </value>
                <value>
                    <fullName>12:40</fullName>
                </value>
                <value>
                    <fullName>12:50</fullName>
                </value>
                <value>
                    <fullName>13:00</fullName>
                </value>
                <value>
                    <fullName>13:10</fullName>
                </value>
                <value>
                    <fullName>13:20</fullName>
                </value>
                <value>
                    <fullName>13:30</fullName>
                </value>
                <value>
                    <fullName>13:40</fullName>
                </value>
                <value>
                    <fullName>13:50</fullName>
                </value>
                <value>
                    <fullName>14:00</fullName>
                </value>
                <value>
                    <fullName>14:10</fullName>
                </value>
                <value>
                    <fullName>14:20</fullName>
                </value>
                <value>
                    <fullName>14:30</fullName>
                </value>
                <value>
                    <fullName>14:40</fullName>
                </value>
                <value>
                    <fullName>14:50</fullName>
                </value>
                <value>
                    <fullName>15:00</fullName>
                </value>
                <value>
                    <fullName>15:10</fullName>
                </value>
                <value>
                    <fullName>15:20</fullName>
                </value>
                <value>
                    <fullName>15:30</fullName>
                </value>
                <value>
                    <fullName>15:40</fullName>
                </value>
                <value>
                    <fullName>15:50</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field4__c</fullName>
        <inlineHelpText>お着きの時間を選択してください。</inlineHelpText>
        <label>到着時刻</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>11:00</fullName>
                </value>
                <value>
                    <fullName>11:10</fullName>
                </value>
                <value>
                    <fullName>11:20</fullName>
                </value>
                <value>
                    <fullName>11:30</fullName>
                </value>
                <value>
                    <fullName>11:40</fullName>
                </value>
                <value>
                    <fullName>11:50</fullName>
                </value>
                <value>
                    <fullName>12:00</fullName>
                </value>
                <value>
                    <fullName>12:10</fullName>
                </value>
                <value>
                    <fullName>12:20</fullName>
                </value>
                <value>
                    <fullName>12:30</fullName>
                </value>
                <value>
                    <fullName>12:40</fullName>
                </value>
                <value>
                    <fullName>12:50</fullName>
                </value>
                <value>
                    <fullName>13:00</fullName>
                </value>
                <value>
                    <fullName>13:10</fullName>
                </value>
                <value>
                    <fullName>13:20</fullName>
                </value>
                <value>
                    <fullName>13:30</fullName>
                </value>
                <value>
                    <fullName>13:40</fullName>
                </value>
                <value>
                    <fullName>13:50</fullName>
                </value>
                <value>
                    <fullName>14:00</fullName>
                </value>
                <value>
                    <fullName>14:10</fullName>
                </value>
                <value>
                    <fullName>14:20</fullName>
                </value>
                <value>
                    <fullName>14:30</fullName>
                </value>
                <value>
                    <fullName>14:40</fullName>
                </value>
                <value>
                    <fullName>14:50</fullName>
                </value>
                <value>
                    <fullName>15:00</fullName>
                    <default>true</default>
                    <label>15:00</label>
                </value>
                <value>
                    <fullName>15:10</fullName>
                </value>
                <value>
                    <fullName>15:20</fullName>
                </value>
                <value>
                    <fullName>15:30</fullName>
                </value>
                <value>
                    <fullName>15:40</fullName>
                </value>
                <value>
                    <fullName>15:50</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LeadIndexRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>予約インデックス</label>
        <referenceTo>LeadIndex__c</referenceTo>
        <relationshipLabel>ご予約</relationshipLabel>
        <relationshipName>LeadIndexRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LeadIndexSubId__c</fullName>
        <externalId>true</externalId>
        <label>予約インデックスSUB</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relcontact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>お客様</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ご予約</relationshipLabel>
        <relationshipName>reservetg85</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rroom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>本予約にお部屋を一つ割当てください。
お部屋を2つ以上割り当てる場合は、同一お客様名の新規予約を作成してください。</inlineHelpText>
        <label>部屋</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Room__c.TypeRoomRef__c</field>
                <operation>equals</operation>
                <valueField>$Source.refTypeOfRooms__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>ご予約</relationshipLabel>
        <relationshipName>R00N10000000rzUoEAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StayPersons__c</fullName>
        <defaultValue>$Setup.CommDefine__c.BookingMansDef__c +  $Setup.CommDefine__c.BookingFemailsDef__c +
$Setup.CommDefine__c.BookingChildrenDef__c</defaultValue>
        <label>予約人数</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ご予約</label>
    <nameField>
        <label>予約名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LeadIndex__c.object
<CustomObject>
    <description>Index record of Booking record day by day</description>
    <fields>
        <fullName>StayPersons__c</fullName>
        <label>部屋人数</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>予約インデックス</label>
    <nameField>
        <displayFormat>I_{YYYY}_{0000000000}</displayFormat>
        <label>予約名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Room__c.object
<CustomObject>
    <description>Master Gest Room, Hall and Resource</description>
    <fields>
        <fullName>Field4__c</fullName>
        <label>名の由来</label>
        <length>400</length>
        <type>Html</type>
    </fields>
    <label>お部屋</label>
    <nameField>
        <label>お部屋</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RoomIndicatorInfoDayUse.cls
public with sharing class RoomIndicatorInfoDayUse {
    // 遷移先からパラメータ情報を格納する
    private static Map<String,String> paramMap;
    public List<LeadInfo> leadInfos{get; private set;}  
    public String topLeadId	{get;set;}
    public String roomId	{get;set;}
	// 初期化処理
    public void init(){
        // 表示情報を初期化する
        leadInfos = new List<LeadInfo>();
        // 戻るページ維持する
        paramMap = Apexpages.currentPage().getParameters();
        roomId = paramMap.get('roomId');	// 部屋ID
        topLeadId = paramMap.get('topLeadId');	// 画面部屋に指定した予約ID
        // データ抽出日
        Date todayDt = (String.isEmpty(paramMap.get('queryDate'))) ? Date.today() : Date.parse(paramMap.get('queryDate'));
        // 部屋タイプの予約RecordType
        List<Id> recTypeLst = RoomIndicatorInfo.getLeadBookingRecTypeLst();
        // 処理日関連の日付
        Date searchDt = RoomIndicatorInfo.getProcessDate(todayDt, Boolean.valueOf(paramMap.get('checkflag')));
        // 部屋IDに所属する予約情報リストを取得する
        List<Lead__c> roomLeads = [	Select id, name, LeadIndexSubId__c, LeadIndexRef__c, Field298__c, Field2__c, Field310__c, Field3__c, Field4__c,
        							Comment3__c, StayPersons__c, Rroom__r.Name, Relcontact__r.name,LeadIndexRef__r.Name, Field310__r.Name,EntryTime__c,
        							Departure__c
        							From Lead__c
									Where CancelBool__c != :CommConst.LEAD_ST_CANCEL_FLG        // 有効な予約データ
                                        And RecordTypeId in :recTypeLst                         // 基本、宿泊のレコードタイプ予約データ
                                        And DAY_ONLY(convertTimezone(EntryTime__c)) = :searchDt // 到着日は指定日と一致する
                                        And Rroom__c = :roomId                             		// 部屋設定場合
                                     Order By Field4Cal__c asc 
        							];
        // 2018/04/04 DAYUSEデータは既に存在しない場合、処理中止BugFix zy
        if (roomLeads.isEmpty()) return;
		// SubIndex明細情報を取得する
      	String queryStr = ' Select Id, ParentLeadIndxRef__c, DepartureDate__c, EntryDate__c, Nights__c From LeadIndex__c ';
		String whereStr = ' Where ';
		for (Lead__c lead : roomLeads) {
			whereStr += ' ( '
					 +  ' ParentLeadIndxRef__c = \'' + String.escapeSingleQuotes(lead.LeadIndexRef__c) + '\''
// 2014/09/22 予約インデクスSUBが未設定する場合、検索条件対象外になる
					 //+  ' And Id = \'' + String.escapeSingleQuotes(lead.LeadIndexSubId__c) + '\''
					 +  (CommUtils.isBlank(lead.LeadIndexSubId__c) 
					 		? ''
					 		: ' And Id = \'' + String.escapeSingleQuotes(lead.LeadIndexSubId__c) + '\'' 
					 	)
//					 +  ' And RoomGroupNo__c = ' + lead.RoomGroupNo__c 
					 +  ' ) ';
			whereStr += ' OR ';
		}
		queryStr += whereStr.trim().removeEnd('OR');
		// 各予約の明細情報を取得する
		Map<String, LeadIndex__c> subIdxMap = new Map<String, LeadIndex__c>();
		for (LeadIndex__c subIdx : DataBase.query(queryStr)) {
			String key = subIdx.ParentLeadIndxRef__c + '_' + subIdx.Id;
			subIdxMap.put(key, subIdx);
		}
		// 出力情報を取得する
		for (Lead__c lead : roomLeads) {
			LeadInfo item = new LeadInfo(lead);
			item.checkinTime = lead.Field4__c;
			item.checkoutTime= lead.Field3__c;
			// SubIndex情報から補足情報を設定する
			String key = lead.LeadIndexRef__c + '_' + lead.LeadIndexSubId__c;
			if (subIdxMap.containsKey(key)) {
				LeadIndex__c subIdx = subIdxMap.get(key);
				item.checkinDate = DateTime.newInstance(subIdx.EntryDate__c.year(), subIdx.EntryDate__c.month(), subIdx.EntryDate__c.day()).format(CommBaseCtrl.getDateFormat());
				item.checkoutDate= DateTime.newInstance(subIdx.DepartureDate__c.year(), subIdx.DepartureDate__c.month(), subIdx.DepartureDate__c.day()).format(CommBaseCtrl.getDateFormat());
				item.nights = CommUtils.nullToIntZero(subIdx.Nights__c);
			}
			leadInfos.add(item);
		}
    }
    
    // 画面に表示する予約情報
    public class LeadInfo{   
        public LeadInfo(Lead__c lead){
            checkoutTime = lead.Field3__c;
            checkinTime = lead.Field4__c;
            s = lead;
            startTime = lead.EntryTime__c.format('yyyyMMdd') + lead.Field4__c;
            endTime = lead.Departure__c.format('yyyyMMdd') + lead.Field3__c;
        }
        //public String roomId{get;set;}
        public String checkoutTime{get;set;}
        public String checkoutDate{get;set;}
        public String checkinTime{get;set;}
        public String checkinDate{get;set;}
        public String startTime{get;set;}
        public String endTime{get;set;}
        public Integer nights{get;set;}
        // LeadInfo
        public Lead__c s{get;set;}
    }
}