src/objects/Lead__c.object
<CustomObject>
    <description>Booking sheet with record type</description>
    <fields>
        <fullName>Comment3__c</fullName>
        <inlineHelpText>ご予約以降に、考慮すべき重要なことがら</inlineHelpText>
        <label>特記事項</label>
        <length>2048</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Departure__c</fullName>
        <defaultValue>NOW()+1</defaultValue>
        <inlineHelpText>お客様が帰られる予定の日付を選択してください。
入力して頂くことで、ご宿泊数などを算出いたします。</inlineHelpText>
        <label>出発日</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EntryTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <inlineHelpText>お客様が来られる予定の日付を選択してください。</inlineHelpText>
        <label>到着日</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Field2__c</fullName>
        <inlineHelpText>予約発生元[流通経路 RM用語 Channel]を選択してください。
当館ご利用の経緯を選択してください。</inlineHelpText>
        <label>予約チャネル</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>電話</fullName>
                </value>
                <value>
                    <fullName>FAX</fullName>
                </value>
                <value>
                    <fullName>自社サイト</fullName>
                </value>
                <value>
                    <fullName>自社サイト[English]</fullName>
                </value>
                <value>
                    <fullName>自社サイト[China]</fullName>
                </value>
                <value>
                    <fullName>自社サイト[Korea]</fullName>
                </value>
                <value>
                    <fullName>自社サイト[Thailand]</fullName>
                </value>
                <value>
                    <fullName>AGT[JTB]</fullName>
                </value>
                <value>
                    <fullName>AGT[KNT]</fullName>
                </value>
                <value>
                    <fullName>AGT[NTA]</fullName>
                </value>
                <value>
                    <fullName>AGT[小田急トラベル]</fullName>
                </value>
                <value>
                    <fullName>AGT[相鉄観光]</fullName>
                </value>
                <value>
                    <fullName>AGT[一休]</fullName>
                </value>
                <value>
                    <fullName>AGT[らくだ]</fullName>
                </value>
                <value>
                    <fullName>AGT[じゃらん]</fullName>
                </value>
                <value>
                    <fullName>AGT[楽天]</fullName>
                </value>
                <value>
                    <fullName>AGT[るるぶ]</fullName>
                </value>
                <value>
                    <fullName>AGT[トクー]</fullName>
                </value>
                <value>
                    <fullName>AGT[ゆこゆこ]</fullName>
                </value>
                <value>
                    <fullName>AGT[リロクラブ]</fullName>
                </value>
                <value>
                    <fullName>AGT[ウェルボックス]</fullName>
                </value>
                <value>
                    <fullName>AGT[ベネフィットワン]</fullName>
                </value>
                <value>
                    <fullName>AGT[リゾートソリューション]</fullName>
                </value>
                <value>
                    <fullName>AGT[ベストリザーブ・宿ぷらざ]</fullName>
                </value>
                <value>
                    <fullName>AGT[e-hotel]</fullName>
                </value>
                <value>
                    <fullName>AGT[マル得]</fullName>
                </value>
                <value>
                    <fullName>AGT[お宿NET]</fullName>
                </value>
                <value>
                    <fullName>AGT[ANA]</fullName>
                </value>
                <value>
                    <fullName>AGT[HIS]</fullName>
                </value>
                <value>
                    <fullName>AGT[expedia]</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field308__c</fullName>
        <description>&lt;font color=&quot;#DC143C&quot;&gt;広告媒体</description>
        <inlineHelpText>予約の時点かまたはチェックインのとき、選択してください</inlineHelpText>
        <label>広告媒体</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Field2__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>るるぶフリーロマンスカー秋号</fullName>
                </value>
                <value>
                    <fullName>るるぶフリーロマンスカー冬号</fullName>
                </value>
                <value>
                    <fullName>旅色（ネットマガジン）</fullName>
                </value>
                <value>
                    <fullName>旅サライ</fullName>
                </value>
                <value>
                    <fullName>「幸せを呼ぶパワースポットはここだ！」</fullName>
                </value>
                <value>
                    <fullName>トラベルポーター「和の宿」</fullName>
                </value>
                <value>
                    <fullName>テレビCM</fullName>
                </value>
                <value>
                    <fullName>パンフレット[Campain code 1400]</fullName>
                </value>
                <value>
                    <fullName>パンフレット[Campain code 5300]</fullName>
                </value>
                <value>
                    <fullName>パンフレット[Campain code ****]</fullName>
                </value>
                <value>
                    <fullName>陣屋オリジナルパンフレット</fullName>
                </value>
                <value>
                    <fullName>その他</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field310__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>プラン</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>非公開に設定されたプランを選択できません。</errorMessage>
            <filterItems>
                <field>Plan__c.IsClosed__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>ご予約</relationshipLabel>
        <relationshipName>RSVfkhF</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field3__c</fullName>
        <inlineHelpText>出発の時間を選択してください。</inlineHelpText>
        <label>出発時刻</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>11:00</fullName>
                </value>
                <value>
                    <fullName>11:10</fullName>
                </value>
                <value>
                    <fullName>11:20</fullName>
                </value>
                <value>
                    <fullName>11:30</fullName>
                </value>
                <value>
                    <fullName>11:40</fullName>
                </value>
                <value>
                    <fullName>11:50</fullName>
                </value>
                <value>
                    <fullName>12:00</fullName>
                </value>
                <value>
                    <fullName>12:10</fullName>
                </value>
                <value>
                    <fullName>12:20</fullName>
                </value>
                <value>
                    <fullName>12:30</fullName>
                </value>
                <value>
                    <fullName>12:40</fullName>
                </value>
                <value>
                    <fullName>12:50</fullName>
                </value>
                <value>
                    <fullName>13:00</fullName>
                </value>
                <value>
                    <fullName>13:10</fullName>
                </value>
                <value>
                    <fullName>13:20</fullName>
                </value>
                <value>
                    <fullName>13:30</fullName>
                </value>
                <value>
                    <fullName>13:40</fullName>
                </value>
                <value>
                    <fullName>13:50</fullName>
                </value>
                <value>
                    <fullName>14:00</fullName>
                </value>
                <value>
                    <fullName>14:10</fullName>
                </value>
                <value>
                    <fullName>14:20</fullName>
                </value>
                <value>
                    <fullName>14:30</fullName>
                </value>
                <value>
                    <fullName>14:40</fullName>
                </value>
                <value>
                    <fullName>14:50</fullName>
                </value>
                <value>
                    <fullName>15:00</fullName>
                </value>
                <value>
                    <fullName>15:10</fullName>
                </value>
                <value>
                    <fullName>15:20</fullName>
                </value>
                <value>
                    <fullName>15:30</fullName>
                </value>
                <value>
                    <fullName>15:40</fullName>
                </value>
                <value>
                    <fullName>15:50</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field4Cal__c</fullName>
        <formula>TEXT(Field4__c )</formula>
        <label>到着時刻</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relcontact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>お客様</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ご予約</relationshipLabel>
        <relationshipName>reservetg85</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReservedDate__c</fullName>
        <description>ご予約の受付日</description>
        <label>予約受付日</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ReservedStatus__c</fullName>
        <inlineHelpText>NO SHOW、キャンセルまたは、削除への変更について、パラメータにより一括キャンセルする／しないを選択可能(連泊のときのみ有効)となります。</inlineHelpText>
        <label>予約ステータス</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>確認中</fullName>
                </value>
                <value>
                    <fullName>確定</fullName>
                    <default>true</default>
                    <label>確定</label>
                </value>
                <value>
                    <fullName>会場おさえ</fullName>
                </value>
                <value>
                    <fullName>仮予約</fullName>
                </value>
                <value>
                    <fullName>キャンセルまち</fullName>
                </value>
                <value>
                    <fullName>NO SHOW</fullName>
                </value>
                <value>
                    <fullName>キャンセル</fullName>
                </value>
                <value>
                    <fullName>削除</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rroom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>本予約にお部屋を一つ割当てください。
お部屋を2つ以上割り当てる場合は、同一お客様名の新規予約を作成してください。</inlineHelpText>
        <label>部屋</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Room__c.TypeRoomRef__c</field>
                <operation>equals</operation>
                <valueField>$Source.refTypeOfRooms__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>ご予約</relationshipLabel>
        <relationshipName>R00N10000000rzUoEAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StayPersons__c</fullName>
        <defaultValue>$Setup.CommDefine__c.BookingMansDef__c +  $Setup.CommDefine__c.BookingFemailsDef__c +
$Setup.CommDefine__c.BookingChildrenDef__c</defaultValue>
        <label>予約人数</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ご予約</label>
    <nameField>
        <label>予約名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>Master Package code Plan</description>
    <label>プラン</label>
    <nameField>
        <label>Plan</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Room__c.object
<CustomObject>
    <description>Master Gest Room, Hall and Resource</description>
    <label>お部屋</label>
    <nameField>
        <label>お部屋</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SSLookupHoverDetailCtrl.cls
public with sharing class SSLookupHoverDetailCtrl {

	// =========================
	// 			予約名 | Name
	//  予約ステータス | ReservedStatus__c
	// 		予約受付日 | ReservedDate__c
	// 			到着日 | EntryTime__c
	// 		  到着時刻 | Field4Cal__c
	// 			出発日 | Departure__c
	// 		  出発時刻 | Field3__c
	// 		  予約人数 | StayPersons__c
	// 	  予約チャネル | Field2__c
	// 		  広告媒体 | Field308__c
	// 			プラン | Field310__c
	// 			  部屋 | Rroom__c
	// 		  特記事項 | Comment3__c
	// 			お客様 | Relcontact__c
	// 		お客様電話 | Relcontact__r.Phone
	// 	  お客様メール | Relcontact__r.Email
	// =========================
	/*
	@RemoteAction
	public static String getLeadInfo(String leadId) {
		if(String.escapeSingleQuotes(leadId) != ''){
		    Lead__c leadDetail = [	select Id, Name, ReservedStatus__c, ReservedDate__c, EntryTime__c, Field4Cal__c, Departure__c,
		    						Field3__c, StayPersons__c, Field2__c, Field308__c, Field310__c, Rroom__c, Comment3__c,
		    						Relcontact__c, Field310__r.Name, Rroom__r.Name, Relcontact__r.Name,
		    						Relcontact__r.Phone, Relcontact__r.Email from Lead__c where Id = :leadId];

			Dom.XmlNode targetNode = CommXmlUtils.parseXmlDoc('LookupHoverDetailInfo', '');
    		Dom.XmlNode obNmNode = targetNode.getChildElement('FIELDS', null);
    		Dom.XmlNode colNumNode = targetNode.getChildElement('COLNUMS', null);
    		String strFields = (obNmNode == null ? '' : CommUtils.nullToBlank(obNmNode.getText()).deleteWhitespace());
    		String colNumFields = (colNumNode == null ? '' : CommUtils.nullToBlank(colNumNode.getText()).deleteWhitespace());
    		List<String> fieldsSplits = strFields.split(',');

    		String st = '';
			String fv = '';
    		st += '<div class="bPageBlock brandSecondaryBrd secondaryPalette" style="box-shadow: 0 0 3px #000;"><div class="pbHeader brandSecondaryBrd"><table border="0" cellpadding="0" cellspacing="0"><tbody><tr><td class="pbTitle"><h2 class="mainTitle">ご予約</h2></td></tr></tbody></table></div><div class="pbBody"><table class="detailList" border="0" cellpadding="0" cellspacing="0"><tbody>';
    		for (String fieldKey : fieldsSplits) {
    			Datetime rDate = leadDetail.ReservedDate__c;
				String reservedDate = rDate.format('yyyy/MM/dd HH:mm');
    			Datetime eDate = leadDetail.EntryTime__c;
				String entryTime = eDate.format('yyyy/MM/dd HH:mm');
    			Datetime dDate = leadDetail.Departure__c;
				String departure = dDate.format('yyyy/MM/dd HH:mm');
    			if (fieldKey == 'Name') {
    			    fv += '<tr><td class="labelCol">予約名</td><td class="dataCol">' + CommUtils.nullToBlank(leadDetail.Name) + '</td></tr>';
    			} if (fieldKey == 'ReservedStatus__c') {
    			    fv += '<tr><td class="labelCol">予約ステータス</td><td class="dataCol">' + CommUtils.nullToBlank(leadDetail.ReservedStatus__c) + '</td></tr>';
    			} if (fieldKey == 'ReservedDate__c') {
    			    fv += '<tr><td class="labelCol">予約受付日</td><td class="dataCol">' + CommUtils.nullToBlank(reservedDate) + '</td></tr>';
    			} if (fieldKey == 'EntryTime__c') {
    			    fv += '<tr><td class="labelCol">到着日</td><td class="dataCol">' + CommUtils.nullToBlank(entryTime) + '</td></tr>';
    			} if (fieldKey == 'Field4Cal__c') {
    			    fv += '<tr><td class="labelCol">到着時刻</td><td class="dataCol">' + CommUtils.nullToBlank(leadDetail.Field4Cal__c) + '</td></tr>';
    			} if (fieldKey == 'Departure__c') {
    			    fv += '<tr><td class="labelCol">出発日</td><td class="dataCol">' + CommUtils.nullToBlank(departure) + '</td></tr>';
    			} if (fieldKey == 'Field3__c') {
    			    fv += '<tr><td class="labelCol">出発時刻</td><td class="dataCol">' + CommUtils.nullToBlank(leadDetail.Field3__c) + '</td></tr>';
    			} if (fieldKey == 'StayPersons__c') {
    			    fv += '<tr><td class="labelCol">予約人数</td><td class="dataCol">' + CommUtils.nullToBlank(leadDetail.StayPersons__c) + '</td></tr>';
    			} if (fieldKey == 'Field2__c') {
    			    fv += '<tr><td class="labelCol">予約チャネル</td><td class="dataCol">' + CommUtils.nullToBlank(leadDetail.Field2__c) + '</td></tr>';
    			} if (fieldKey == 'Field308__c') {
    			    fv += '<tr><td class="labelCol">広告媒体</td><td class="dataCol">' + CommUtils.nullToBlank(leadDetail.Field308__c) + '</td></tr>';
    			} if (fieldKey == 'Field310__c') {
    			    fv += '<tr><td class="labelCol">プラン</td><td class="dataCol"><a href="/'+ leadDetail.Field310__c +'">' + CommUtils.nullToBlank(leadDetail.Field310__r.Name) + '</a></td></tr>';
    			} if (fieldKey == 'Rroom__c') {
    			    fv += '<tr><td class="labelCol">部屋</td><td class="dataCol"><a href="/'+ leadDetail.Rroom__c +'">' + CommUtils.nullToBlank(leadDetail.Rroom__r.Name) + '</a></td></tr>';
    			} if (fieldKey == 'Comment3__c') {
    			    fv += '<tr><td class="labelCol">特記事項</td><td class="dataCol">' + CommUtils.nullToBlank(leadDetail.Comment3__c) + '</td></tr>';
    			} if (fieldKey == 'Relcontact__c') {
    			    fv += '<tr><td class="labelCol">お客様</td><td class="dataCol"><a href="/'+ leadDetail.Relcontact__c +'">' + CommUtils.nullToBlank(leadDetail.Relcontact__r.Name) + '</a></td></tr>';
    			} if (fieldKey == 'Relcontact__r.Phone') {
    			    fv += '<tr><td class="labelCol">電話</td><td class="dataCol">' + CommUtils.nullToBlank(leadDetail.Relcontact__r.Phone) + '</td></tr>';
    			} if (fieldKey == 'Relcontact__r.Email') {
    			    fv += '<tr><td class="labelCol">メール</td><td class="dataCol">' + CommUtils.nullToBlank(leadDetail.Relcontact__r.Email) + '</td></tr>';
    			}
    		}
			if (colNumFields == '2') {
                String colFlg = '</tr><tr>';
                Integer counter = 0;  
                while(fv.indexOf(colFlg) != -1){
                    counter++;
                    if (math.mod(counter,2) == 0) {
                        fv = fv.replaceFirst('</tr><tr>','</tr><tr >');
                    }else{
                        fv = fv.replaceFirst('</tr><tr>','');
                    }
                    // fv=fv.substring(fv.indexOf(colFlg)+colFlg.length());
                }
            }
            st += fv;
            // st += '</tbody></table></div></div>';
            System.debug(LoggingLevel.INFO, ':::' + st);
			return st;
		}else {
			return '';
		}
	}
	*/
    @RemoteAction
    public static String getTaskInfo(String userId, String taskDt) {
        if(!CommUtils.isBlank(userId)){
            //taskDt = taskDt.replace('/', '-');
            //Date dt = Date.valueOf(taskDt);
            Date dt = CommUtils.stringToDate(taskDt);
            // 2015/07/30 Todoは表示対象になる
            //List<Task> taskDetail = [select Id, OwnerId, Subject, ActivityDate, Description, Status from Task where OwnerId =:userId and ActivityDate =:dt];
            // 2018/07/17 終了日拡張するため、拡張項目終了日を追加対応 BEGIN
            //List<Event> eventDetail = [select Id, OwnerId, Subject, ActivityDate, Description, StartDateTime, EndDateTime, IsAllDayEvent from Event where OwnerId =:userId and ActivityDate =:dt];
			List<Event> eventDetail = [select Id, OwnerId, Subject, ActivityDate, Description, StartDateTime, EndDateTime, EndDateTime__c, IsAllDayEvent 
                                        // 2019/06/30 jinya bug fix JINYABUG-1873 by zy BEGIN
                                        ,EventIndex__c
                                        // 2019/06/30 jinya bug fix JINYABUG-1873 by zy END
                                        from Event where OwnerId =:userId and ActivityDate =:dt
										// 2018/07/24 定期のタスク、親定期タスク非表示JINYABUG-745 by BEGIN
                                         and IsRecurrence = false	
                                         // 2018/07/24 定期のタスク、親定期タスク非表示JINYABUG-745 by END
										];
			// 2018/07/17 終了日拡張するため、拡張項目終了日を追加対応 END
            String st = '';
            String fv = '';
            //行動
            st += '<div class="bPageBlock brandSecondaryBrd secondaryPalette" style="box-shadow: 0 0 3px #000;"><div class="pbHeader brandSecondaryBrd"><table border="0" cellpadding="0" cellspacing="0"><tbody><tr><td class="pbTitle"><h2 class="mainTitle">'+ Label.CONST_035_0135 +'</h2></td></tr></tbody></table></div><div class="pbBody"><table class="detailList" border="0" cellpadding="0" cellspacing="0"><tbody>';

            for (Event fieldKey : eventDetail) {
                    
	            Datetime sDate = fieldKey.StartDateTime;
				//String startDate = fieldkey.IsAllDayEvent ? sDate.format('yyyy/MM/dd') : sDate.format('yyyy/MM/dd HH:mm');
				// 2016/11/25 TIMEZON fix BEGIN by zh
				//String startDate = fieldkey.IsAllDayEvent ? sDate.format(CommBaseCtrl.getDateFormat()) : sDate.format(CommBaseCtrl.getDateTimeFormat());
				String startDate = fieldkey.IsAllDayEvent ? sDate.format(CommBaseCtrl.getDateFormat()) : sDate.format();
				// 2016/11/25 TIMEZON fix END by zh
	            Datetime eDate = fieldKey.EndDateTime;
	            // 2018/07/17 終了日拡張するため、拡張項目終了日を追加対応 BEGIN
	            // 終日行動の場合、表示メッセージ不正
	            // 所以終日行動读取值用原来的enddatetime
                // 2019/06/30 jinya bug fix JINYABUG-1873 by zy BEGIN
	            if (!fieldkey.IsAllDayEvent && fieldKey.EndDateTime__c != null && fieldkey.EventIndex__c == null) eDate = fieldKey.EndDateTime__c;
	            // 2019/06/30 jinya bug fix JINYABUG-1873 by zy END
                // 2018/07/17 終了日拡張するため、拡張項目終了日を追加対応 END
				//String endDate =  fieldkey.IsAllDayEvent ? eDate.format('yyyy/MM/dd') : eDate.format('yyyy/MM/dd HH:mm');
				// 2016/11/25 TIMEZON fix BEGIN by zh
				//String endDate =  fieldkey.IsAllDayEvent ? eDate.format(CommBaseCtrl.getDateFormat()) : eDate.format(CommBaseCtrl.getDateTimeFormat());
				String endDate =  fieldkey.IsAllDayEvent ? eDate.format(CommBaseCtrl.getDateFormat()) : eDate.format();
				// 2016/11/25 TIMEZON fix END by zh
				//件名
				//開始日時
                fv += '<tr><td class="labelCol" rowspan="2">'+ Label.CONST_035_0136 +'</td><td class="dataCol" rowspan="2"><a href="/'+ fieldKey.Id +'">' + CommUtils.nullToBlank(fieldKey.Subject) + '</a></td><td class="labelCol">'+ Label.CONST_035_0137 +'</td><td class="dataCol">' + CommUtils.nullToBlank(startDate) + '</td></tr>';
                //終了日時
                fv += '<tr><td class="labelCol">'+ Label.CONST_035_0138 +'</td><td class="dataCol">' + CommUtils.nullToBlank(endDate) + '</td></tr>';
            }
            st += fv;
            return st;
        }else {
            return '';
        }
    }
    @RemoteAction
    // 2018/10/26 マルチタスクとシフトの合計欄の表示内容はカスタマイズできるように改善 by cxw BEGIN
    public static String getLeadsInfo(String leadIds, String spcd){
    //public static String getLeadsInfo(String leadIds) {
    // 2018/10/26 マルチタスクとシフトの合計欄の表示内容はカスタマイズできるように改善 by cxw END
    	// 2018/10/26 マルチタスクとシフトの合計欄の表示内容はカスタマイズできるように改善 by cxw BEGIN
    	String result = '';
		FieldStruct fieldStruct = loadDocument(spcd);
		if(!CommUtils.isBlank(leadIds)){
        /*
        !fieldStruct.allFieldSet.isEmpty()
        	List<String> leadIdLst = CommUtils.nullToBlank(leadIds).split(',');
			Integer leadCancelFlg = CommConst.LEAD_ST_CANCEL_FLG;
            // 2015/07/30 Todoは表示対象になる
            //List<Task> taskDetail = [select Id, OwnerId, Subject, ActivityDate, Description, Status from Task where OwnerId =:userId and ActivityDate =:dt];
            List<Lead__c> leadDetails = [	select Id, Name, ReservedStatus__c, ReservedDate__c, EntryTime__c, Field4Cal__c, Departure__c,
		    						Field3__c, StayPersons__c, Field2__c, Field308__c, Field310__c, Rroom__c, Comment3__c,
		    						Relcontact__c, Field310__r.Name, Rroom__r.Name, Relcontact__r.Name,
		    						Relcontact__r.Phone, Relcontact__r.Email from Lead__c where  id = :leadIdLst];
			*/
			List<String> leadIdLst = CommUtils.nullToBlank(leadIds).split(',');
			String sql = 'SELECT ' + fieldStruct.getSql() + ' FROM lead__c WHERE id = :leadIdLst';
			List<Lead__c> leadDetails = Database.query(sql);
			// 2018/10/26 マルチタスクとシフトの合計欄の表示内容はカスタマイズできるように改善 by cxw END
//System.debug(LoggingLevel.INFO, 'leadDetails:::' + leadDetails);
            String st = '';
            String fv = '';
            //ご予約
            st += '<div class="bPageBlock brandSecondaryBrd secondaryPalette" style="box-shadow: 0 0 3px #000;"><div class=" brandSecondaryBrd"><table border="0" cellpadding="0" cellspacing="0"><tbody><tr><td class="pbTitle"><h2 class="mainTitle">'+ Label.CONST_035_0139 +'</h2></td></tr></tbody></table></div><div class="pbBody"><table class="detailList" border="0" cellpadding="0" cellspacing="0"><tbody>';

            for (Lead__c fieldKey : leadDetails) {
                // 2018/10/26 マルチタスクとシフトの合計欄の表示内容はカスタマイズできるように改善 by cxw BEGIN
                /*
                // 2018/10/26 マルチタスクとシフトの合計欄の表示内容はカスタマイズできるように改善 by cxw END
	            Datetime sDate = fieldKey.EntryTime__c;
				//String startDate = sDate.format('yyyy/MM/dd');
				String startDate = sDate.format(CommBaseCtrl.getDateFormat());
	            Datetime eDate = fieldKey.Departure__c;
				//String endDate =  eDate.format('yyyy/MM/dd');
				String endDate =  eDate.format(CommBaseCtrl.getDateFormat());
				//予約
				//お客様
                fv += '<tr><td class="labelCol" >'+ Label.CONST_035_0140 +'</td><td class="dataCol" ><a href="/'+ fieldKey.Id +'" target="_blank">' + CommUtils.nullToBlank(fieldKey.Name) + '</a></td><td class="labelCol">'+ Label.CONST_035_0141 +'</td><td class="dataCol"><a href="/'+ fieldKey.Relcontact__c +'">' + CommUtils.nullToBlank(fieldKey.Relcontact__r.Name) + '</a></td></tr>';
                // 2018/10/26 マルチタスクとシフトの合計欄の表示内容はカスタマイズできるように改善 by cxw BEGIN
                */
                fv += '<tr>';
				for(String field : fieldStruct.xmlOrderLst){
					String fieldLab = fieldStruct.fieldsMap.get(field);
					String fieldVal = '';
					fieldVal = getValue(fieldKey, field);
					String fieldId = getValue(fieldKey, fieldStruct.linksMap.get(field));
					String item = generateItem(fieldVal, fieldLab, fieldId);
					fv += item;
				}
				fv += '</tr>';
				// 2018/10/26 マルチタスクとシフトの合計欄の表示内容はカスタマイズできるように改善 by cxw END
            }
            st += fv;
            st += '</tbody></table></div></div>';
///System.debug(LoggingLevel.INFO, ':::' + st);
            return st;
        }else {
            return '';
        }
    }
    // 2018/10/26 マルチタスクとシフトの合計欄の表示内容はカスタマイズできるように改善 by cxw BEGIN
    // 解析XML
    private static FieldStruct loadDocument(String spcd){
    	FieldStruct fs = new FieldStruct();
    	try{
	    	Dom.XmlNode targetNode = CommXmlUtils.parseXmlDoc('StaffScheduleConfigXml', spcd);
	    	if(targetNode != null){
	    		Dom.XmlNode node = targetNode.getChildElement('SUMMARYEXTFIELD', null);
	    		if(node != null){
	    			String field = '';
	    			String link = '';
	    			Dom.XmlNode fieldNode = node.getChildElement('FIELDS', null);
	    			if(fieldNode != null) field = CommUtils.nullToBlank(fieldNode.getText()).toLowerCase().trim();
	    			Dom.XmlNode linkNode = node.getChildElement('LINKFIELD', null);
	    			if(linkNode != null) link = CommUtils.nullToBlank(linkNode.getText()).toLowerCase().trim();
	    			parse(field, fs, 'FIELDS');
	    			parse(link, fs, 'LINKFIELD');
	    			
	    		}
	    	}
    	}catch(Exception e){
    		return new FieldStruct();
    	}
    	return fs;
    }
    // 解析xml字符串信息
    private static void parse(String text, FieldStruct fs, String tpy){
    	if(CommUtils.isBlank(text) || fs == null) return;
		for(String items : text.split(',')){
			String[] item = items.split(':');
			if(item.size() > 0){
				item[0] = item[0].trim(); // api
				if(tpy == 'FIELDS'){
					fs.add(item[0], item.size() > 1 ? item[1] : null);
				}else if(tpy == 'LINKFIELD'){
					fs.addLink(item[0], item.size() > 1 ? item[1] : null);
				}
			}
		}
    }
    // 存储所有的字段信息
    private class FieldStruct {
    	public Map<String, String> fieldsMap; // Sql 对应名字
    	public List<String> xmlOrderLst; // 遍历
    	private Map<String, Schema.DescribeFieldResult> defValMaps; // 所有字段
    	private Boolean isDefault = true; // 默认
    	public Set<String> exitSet; // sql
    	public Map<String, String> linksMap; // link 对应
    	
    	public FieldStruct(){
    		xmlOrderLst = new List<String>{'name', 'relcontact__r.name'}; // 遍历顺序
    		fieldsMap = new Map<String, String>{'name'=>Label.CONST_035_0140, 'relcontact__r.name'=>Label.CONST_035_0141}; // 别名
    		defValMaps = CommSqlUtils.getAllFieldLst(Lead__c.sobjectType, false, true); // 获取所有字段
    		linksMap = new Map<String, String>{'name'=>'id', 'relcontact__r.name'=>'relcontact__c'}; // link对应
    		exitSet = new Set<String>{'name', 'id', 'relcontact__c', 'relcontact__r.name'}; // sql
    	}
    	// 添加字段相关信息
    	public void add(String fieldName, String fieldLable){
    		if(isDefault){
    			xmlOrderLst.clear();
    			fieldsMap.clear();
    			isDefault = false;
    			linksMap.clear();
    			exitSet.clear();
    		}
    		fieldName = refTo2f(fieldName);
    		Schema.DescribeFieldResult dr = isExistForSobject(fieldName);
    		if(exitSet.contains(fieldName) || dr == null) return;
    		xmlOrderLst.add(fieldName); // 需要遍历的list
    		fieldsMap.put(fieldName, CommUtils.isBlank(fieldLable) ? dr.getLabel() : fieldLable);
    		exitSet.add(fieldName); // sql
    		
    	}
    	
    	public void addLink(String fieldApi, String linkApi){
    		if(CommUtils.isBlank(CommUtils.nullToBlank(fieldApi)) || CommUtils.isBlank(CommUtils.nullToBlank(linkApi))) return;
    		fieldApi = refTo2f(fieldApi);
    		if(!exitSet.contains(fieldApi)) return;
    		linkApi = refTo2f(linkApi);
    		// 是否为lead的字段
    		Schema.DescribeFieldResult dr = isExistForSobject(linkApi);
    		if(dr == null || (dr.getType() != DisplayType.Reference && dr.getType() != DisplayType.ID)) return;
    		if(!exitSet.contains(linkApi)) exitSet.add(linkApi);
    		linksMap.put(fieldApi, linkApi);
    	}
    	private String fieldToNormal(String fieldName, Boolean isFront){
    		return fieldName.indexOf('__r.') != -1 ? isFront ? fieldName.split('__r.')[0] + '__c' : fieldName.split('__r.')[1] : fieldName;
    	}
    	
    	private Boolean isRef(String fieldName){
    		return fieldName.indexOf('__r.') != -1;
    	}
    	
    	private Schema.DescribeFieldResult isExistForSobject(String fieldName){
    		Schema.DescribeFieldResult dr = defValMaps.get(fieldToNormal(fieldName, true));
    		if(dr != null && isRef(fieldName)){
    			List<SobjectType> sts = dr.getReferenceTo();
    			if(!sts.isEmpty()){
    				SobjectType firstST = sts.get(0);
    				Map<String, Schema.DescribeFieldResult> refAllFieldMap = CommSqlUtils.getAllFieldLst(firstST, false, true);
    				if(!refAllFieldMap.containsKey(fieldToNormal(fieldName, false))) return null;
    				return refAllFieldMap.get(fieldToNormal(fieldName, false));
    			}
    		}
    		return dr;
    	}
    	private String refTo2f(String fieldName){
    		String[] item = fieldName.split('__r.');
    		if(item.size() > 1) return item[0] + '__r.' + item[1];
    		return fieldName;
    	}
    	
    	public String getSql(){
    		return String.join(new List<String>(exitSet), ',');
    	}
    }
    // 生成item
    private static String generateItem(String fieldValue, String fieldLabel, String fieldId){
    	String result = '<td class="labelCol">';
    	result += fieldLabel;
    	result += '</td><td class="dataCol">';
    	if(!CommUtils.isBlank(fieldId)){
    		result += '<a href="/';
    		result += fieldId;
    		result += '" target="_blank">';
    		result += fieldValue;
    		result += '</a>';
    	}else{
    		result += fieldValue;
    	}
    	result += '</td>';
		return result;    	
    }
    
    // 两层或者一层的获取值
    private static String getValue(Sobject sobj, String fieldName){
    	try{
    		String[] fieldArr = fieldName.split('__r.');
	    	if(fieldArr.size() == 2){
	    		return CommUtils.nullToBlank(sobj.getSobject(fieldArr[0] + '__r').get(fieldArr[1]));
	    	}else if(fieldArr.size() == 1){
	    		return CommUtils.nullToBlank(sobj.get(fieldArr[0]));
	    	}else{
	    		return '';
	    	}
    	}catch(Exception e){
    		return '';
    	}
    }
    // 2018/10/26 マルチタスクとシフトの合計欄の表示内容はカスタマイズできるように改善 by cxw END
}