src/objects/Lead__c.object
<CustomObject>
    <description>Booking sheet with record type</description>
    <fields>
        <fullName>CancelBool__c</fullName>
        <formula>If (ISPICKVAL( ReservedStatus__c , &quot;キャンセル&quot;) || ISPICKVAL( ReservedStatus__c , &quot;NO SHOW&quot;) || ISPICKVAL( ReservedStatus__c , &quot;削除&quot;) ,1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>予約ステータスがキャンセルであれば1でなければ0を返す</inlineHelpText>
        <label>CancelBool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EntryTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <inlineHelpText>お客様が来られる予定の日付を選択してください。</inlineHelpText>
        <label>到着日</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Rroom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>本予約にお部屋を一つ割当てください。
お部屋を2つ以上割り当てる場合は、同一お客様名の新規予約を作成してください。</inlineHelpText>
        <label>部屋</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Room__c.TypeRoomRef__c</field>
                <operation>equals</operation>
                <valueField>$Source.refTypeOfRooms__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>ご予約</relationshipLabel>
        <relationshipName>R00N10000000rzUoEAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>refTypeOfRooms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>部屋タイプ</label>
        <referenceTo>TypeOfRooms__c</referenceTo>
        <relationshipLabel>ご予約</relationshipLabel>
        <relationshipName>typeOfRooms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ご予約</label>
    <nameField>
        <label>予約名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Room__c.object
<CustomObject>
    <description>Master Gest Room, Hall and Resource</description>
    <fields>
        <fullName>CapacityHaku__c</fullName>
        <label>定員 宿泊</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>定員 食事</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Field10__c</fullName>
        <label>定員 会議</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field7__c</fullName>
        <label>ベッド</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>○</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAN__c</fullName>
        <label>有線LAN</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>○</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rnumber__c</fullName>
        <externalId>true</externalId>
        <label>R#</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Seq__c</fullName>
        <inlineHelpText>予定表レポートの表示順序</inlineHelpText>
        <label>Seq#</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TypeRoomRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>部屋タイプ</label>
        <referenceTo>TypeOfRooms__c</referenceTo>
        <relationshipLabel>お部屋</relationshipLabel>
        <relationshipName>TypeRoomRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X3H__c</fullName>
        <formula>Rank__r.X3H__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>貸切料[3H]昼</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X3Hyoru__c</fullName>
        <formula>Rank__r.X3Hyu__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>貸切料[3H]夜</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>お部屋</label>
    <nameField>
        <label>お部屋</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RoomSelector.cls
/*****************************
* 部屋選択画面
******************************/
public with sharing class RoomSelector {

    public List<Room__c> roomLst{get;set;}
    // 部屋タイプID
    private String pRoomTypeId{get;set;}
    // 部屋アサイン済みは対象外フラグ
    private Date pAssingDate{get;set;}
    private Date pAssingEndDate{get;set;}
    private Set<Id> pRoomIdSet{get; set;}
    // 検索条件
    public String c_roomNm{get; set;}
    public void init() {
    	// 前ページから引渡部屋タイプID
    	pRoomTypeId = ApexPages.currentPage().getParameters().get('pidx');
    	// 前ページから引渡アサイン日付
    	String assingDt = ApexPages.currentPage().getParameters().get('pdt');
    	pAssingDate = CommUtils.stringToDate(assingDt);
    	assingDt = ApexPages.currentPage().getParameters().get('pde');
    	pAssingEndDate = CommUtils.stringToDate(assingDt);
    	pRoomIdSet = new Set<Id>();
        // 部屋一覧を検索を行う
        this.queryInfo();
    }
    private static final String QueryHeader = 'select id, name ,Rnumber__c, CapacityHaku__c, Capacity__c, Field10__c, X3H__c, X3Hyoru__c, Field7__c, LAN__c From Room__c';
    private static final String OrderByStr = ' Order by Seq__c limit 200 ';
    public void queryInfo () {
        // 該当日に予約データがないデータだけ、画面を表示する？
        String queryStr = QueryHeader + getWhereStr() + OrderByStr;
        roomLst = Database.query(queryStr);
        // 予約日の日付をチェックする:次のVERSION
    }
    private String getWhereStr() {
        String whereStr = ' where TypeRoomRef__c = :pRoomTypeId ';
        if (!CommUtils.isBlank(c_roomNm)) {
           whereStr += ' AND name Like \'%' + CommUtils.escStr(c_roomNm) + '%\'';
        }
        // 該当日付が存在する場合、表示する部屋は非アサイン条件が必要
        // 2013/10/28 部屋割り当て可能チェックを行う
        if (pAssingDate != null && pAssingEndDate != null) {
        	pRoomIdSet.clear();
        	pAssingEndDate = (pAssingDate < pAssingEndDate ? pAssingEndDate.addDays(-1) : pAssingEndDate);
        	//Id bookingRecTypeId = CommLogicProcess.getLeadBookingRecType();
        	List<Id> bookingRecTypeId = RoomIndicatorInfo.getLeadBookingRecTypeLst();
	        for(AggregateResult r : [select Rroom__c roomNo from Lead__c
	        	where CancelBool__c != :CommConst.LEAD_ST_CANCEL_FLG And RecordTypeId = :bookingRecTypeId
	                And DAY_ONLY(convertTimezone(EntryTime__c)) >= :pAssingDate
	                And DAY_ONLY(convertTimezone(EntryTime__c)) <= :pAssingEndDate
	                And refTypeOfRooms__c = :pRoomTypeId And Rroom__c != null Group by Rroom__c]) {
				pRoomIdSet.add((ID)r.get('roomNo'));
            }
            if (!pRoomIdSet.isEmpty()) whereStr += ' AND id not in :pRoomIdSet ';
        }
        return whereStr;
    }

}