src/objects/QQNAIEvent__c.object
<CustomObject>
    <description>Room assignment state change events</description>
    <label>QQNAIEvent</label>
    <nameField>
        <displayFormat>AIE-{00000000}</displayFormat>
        <label>AIEvent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QQNErrorLog__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>QQNErrorLog</label>
    <nameField>
        <displayFormat>AIERR-{0000000000}</displayFormat>
        <label>ErrorLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QQNAIEventSaverBatch.cls
public class QQNAIEventSaverBatch implements Database.Batchable<sObject>, Database.Stateful {
	private List<QQNAIEvent__c> events;
	// 実行行列
   	public List<String> excuteFields;
    public QQNAIEventSaverBatch(List<QQNAIEvent__c> events) {
    	this.events = events;
    }
    
    public List<QQNAIEvent__c> start(Database.BatchableContext BC) {
    	return events;
    }
    
    public void execute(Database.BatchableContext BC, List<QQNAIEvent__c> scope) {
    	try {insert scope;} catch(Dmlexception ex) {
    		QQNErrorLog__c objErrorLog = new QQNErrorLog__c(Description__c='Error while saving timeline events: '+ ex.getMessage() );
      		insert objErrorLog;}
    }
    
    public void finish(Database.BatchableContext BC) {
    	// 自動機能実行行列
    	QQNRoomTrainBatch.nextExcuteBatch(excuteFields);
    }
}