src/objects/ShopInformation__c.object
<CustomObject>
    <description>Shoppers</description>
    <fields>
        <fullName>Seq__c</fullName>
        <label>Seq#</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ShopCode__c</fullName>
        <externalId>true</externalId>
        <label>店舗コード</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>店舗情報</label>
    <nameField>
        <label>店舗名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BranchShopUtil.cls
/**
* 支店関連設定、取得情報を処理する
**/
public with sharing class BranchShopUtil {
	/* 2014/08/28 未使用になる、ShopInfoUtilに変更する
	public BranchShopUtil() {
		setInitBranShopLst();
	}
	
    // 支店選択リスト
    public List<SelectOption> branchShopLst{get; private set;}
    public String branchShopNm{get; set;}
    public Boolean isShowShop{get{return !branchShopLst.isEmpty();}}
    private void setInitBranShopLst() {
    	branchShopLst = new List<SelectOption>();
        for (ShopInformation__c shop : [select id, name,ShopCode__c from ShopInformation__c order by Seq__c limit 5000]) {
 //		for (ShopInformation__c shop : [select id, name,ShopCode__c from ShopInformation__c where id = null order by Seq__c]) {
        	branchShopLst.add(new SelectOption(shop.ShopCode__c, shop.name));
        }
        if (!branchShopLst.isEmpty()) {
        	// 顧客に設定する支店で初期値に設定する[2013/06/30]
        	String locShopCode = UserUtil.CurrentUser.ShopCode__c;
        	for (SelectOption s : branchShopLst) {
        		if (s.getValue() == locShopCode) branchShopNm = locShopCode;
        	}
        }
    }*/
}