src/objects/StaffSchedule__c.object
<CustomObject>
    <fields>
        <fullName>CommentLst__c</fullName>
        <label>コメント</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>電車遅延による遅刻</fullName>
                </value>
                <value>
                    <fullName>私用にて遅刻</fullName>
                </value>
                <value>
                    <fullName>私用にて早退</fullName>
                </value>
                <value>
                    <fullName>体調不良にて遅刻</fullName>
                </value>
                <value>
                    <fullName>体調不良にて早退</fullName>
                </value>
                <value>
                    <fullName>体調不良にて休み</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SearchKey__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>従業員+&apos;_&apos; + 勤怠日(ID_YYYY/MM/DD)</inlineHelpText>
        <label>SearchKey</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StaffUserRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>従業員</label>
        <referenceTo>User</referenceTo>
        <relationshipName>StaffUserRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StatusLst__c</fullName>
        <label>開始ステータス</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>5:00</fullName>
                </value>
                <value>
                    <fullName>5:30</fullName>
                </value>
                <value>
                    <fullName>6:00</fullName>
                </value>
                <value>
                    <fullName>6:30</fullName>
                </value>
                <value>
                    <fullName>7:00</fullName>
                </value>
                <value>
                    <fullName>7:30</fullName>
                </value>
                <value>
                    <fullName>8:00</fullName>
                </value>
                <value>
                    <fullName>8:30</fullName>
                </value>
                <value>
                    <fullName>9:00</fullName>
                </value>
                <value>
                    <fullName>9:30</fullName>
                </value>
                <value>
                    <fullName>10:00</fullName>
                </value>
                <value>
                    <fullName>10:30</fullName>
                </value>
                <value>
                    <fullName>11:00</fullName>
                </value>
                <value>
                    <fullName>11:30</fullName>
                </value>
                <value>
                    <fullName>12:00</fullName>
                </value>
                <value>
                    <fullName>12:30</fullName>
                </value>
                <value>
                    <fullName>13:00</fullName>
                </value>
                <value>
                    <fullName>16:00</fullName>
                </value>
                <value>
                    <fullName>17:00</fullName>
                </value>
                <value>
                    <fullName>18:00</fullName>
                </value>
                <value>
                    <fullName>21:00</fullName>
                </value>
                <value>
                    <fullName>経理</fullName>
                </value>
                <value>
                    <fullName>公休</fullName>
                </value>
                <value>
                    <fullName>代休</fullName>
                </value>
                <value>
                    <fullName>半休</fullName>
                </value>
                <value>
                    <fullName>希望休</fullName>
                </value>
                <value>
                    <fullName>有休</fullName>
                </value>
                <value>
                    <fullName>夏休</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TimeManagementRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>勤怠管理</label>
        <referenceTo>TimeManagement__c</referenceTo>
        <relationshipName>StaffTimeManagementRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkDay__c</fullName>
        <label>勤怠日</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>シフト</label>
    <nameField>
        <displayFormat>SS-{00000000}</displayFormat>
        <label>採番</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StaffScheduleSf1Ctrl.cls
public with sharing class StaffScheduleSf1Ctrl {

    public User loginUser{get; set;}
    public Date sWorkDay{get; set;}
    public StaffSchedule__c staffObj{get; set;}
    private Map<Date,StaffSchedule__c> sMap{get; set;}
    public String customComment{get; set;}
    public String customStatus{get; set;}
    public List<SelectOption> commentLabLst{get; set;}
    public List<SelectOption> statusLabLst{get; set;}
    public List<String> commentSelLst{get; set;}
    public List<String> statusSelLst{get; set;}
    public Boolean isPostDate{get{return staffObj == null ? false : staffObj.WorkDay__c < Date.today();}}

    public StaffScheduleSf1Ctrl() {
        loginUser = UserUtil.getUser(UserInfo.getUserId());
        sWorkDay = Date.today();
        staffObj = new StaffSchedule__c(WorkDay__c = sWorkDay);
        sMap = new Map<Date,StaffSchedule__c>();
        init(sWorkDay);
    }
    public void init(Date dt) {
        sMap = staffMap(dt);
        commentLabLst = new List<SelectOption>();
        commentLabLst = staffOp(StaffSchedule__c.CommentLst__c.getDescribe());
        statusLabLst = new List<SelectOption>();
        statusLabLst = staffOp(StaffSchedule__c.StatusLst__c.getDescribe());
        commentSelLst = new List<String>();
        statusSelLst = new List<String>();
        customComment = '';
        customStatus = '';
        if (sMap.containsKey(dt)) {
            staffObj = sMap.get(dt);
            String mc = CommUtils.nullToBlank(staffObj.CommentLst__c);
            String ms = CommUtils.nullToBlank(staffObj.StatusLst__c);
            List<String> comSel = mc.split(':');
            List<String> staSel = ms.split(':');
            if (comSel.size() == 2) 
            customComment = comSel[1];
            if (staSel.size() == 2) 
            customStatus = staSel[1];

            if (comSel.size() > 0) {
                String s1 = comSel[0].replace(' ', '');
                commentSelLst = s1.split(',');
            }
            if (staSel.size() > 0) {
                String s2 = staSel[0].replace(' ', '');
                statusSelLst = s2.split(',');
            }
        }else {
            staffObj.WorkDay__c = dt;
        }
    }

    public void gotoDate() {
        init(staffObj.WorkDay__c);
    }
    private List<SelectOption> staffOp(Schema.DescribeFieldResult dfr) {
        List<SelectOption> commentTypeLst = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult = dfr;
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry f : ple) {
            commentTypeLst.add(new SelectOption(f.getValue(),f.getLabel()));
        }
        return commentTypeLst;
    }
    private Map<Date,StaffSchedule__c> staffMap(Date workDate) {
        Map<Date,StaffSchedule__c> staffMap = new Map<Date,StaffSchedule__c>();
        List<StaffSchedule__c> staffList = new List<StaffSchedule__c>();
        staffList = [select Id, Name, StaffUserRef__c, WorkDay__c, StatusLst__c, TimeManagementRef__c, SearchKey__c, CommentLst__c from StaffSchedule__c where StaffUserRef__c = :UserInfo.getUserId() And WorkDay__c = :workDate];
        if (staffList.size() > 0) {
            for (StaffSchedule__c s:staffList ) {
                staffMap.put(s.WorkDay__c, s);
            }
        }
        return staffMap;
    }
    public void upsertData() {
        String tmps = '';
        String tmpc = '';
        staffObj.StatusLst__c = '';
        for (String s:statusSelLst ) {
            tmps += s + ',';
        }
        if (!CommUtils.isBLank(tmps)) tmps = tmps.removeEnd(',');
        staffObj.StatusLst__c += tmps + ((CommUtils.isBlank(customStatus)) ? '' : ':' + customStatus);

        staffObj.CommentLst__c = '';
        for (String s:commentSelLst ) {
            tmpc += s + ',';
        }
        if (!CommUtils.isBLank(tmpc)) tmpc = tmpc.removeEnd(',');
        staffObj.CommentLst__c += tmpc + ((CommUtils.isBlank(customComment)) ? '' : ':' + customComment);
        staffObj.StaffUserRef__c = UserInfo.getUserId();
        staffObj.SearchKey__c = staffObj.StaffUserRef__c + '_' + staffObj.WorkDay__c.format();
        staffObj.Id = null;
        upsert staffObj StaffSchedule__c.SearchKey__c;
    }
}